# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-25 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0001_initial'),
        ('tutorial_app', '0002_removed_settings')
    ]

    operations = [
        migrations.DeleteModel(
            name='SentUpdateType',
        ),
    ]
