# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-30 13:09
from __future__ import unicode_literals

from django.db import migrations

def addAttendance(apps, schema_editor):
    MessageType = apps.get_model('information_app', 'MessageType')
    MessageType.objects.create(name='Attendance')

class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addAttendance),
    ]
