# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-14 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0002_auto_20201130_1839'),
        ('information_app', '0002_sentupdatetype'),
    ]

    operations = [
    ]
