# Generated by Django 3.2.5 on 2021-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0003_admininformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformation',
            name='employeeList',
            field=models.TextField(default='', verbose_name='employeeList'),
        ),
    ]
