# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-10 10:07
from __future__ import unicode_literals

from django.db import migrations

from information_app.db_script.change_notification_to_upper_case import change_notification_to_upper_case


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0004_auto_20210130_1500'),
    ]

    operations = [
        migrations.RunPython(change_notification_to_upper_case)
    ]
