# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from report_card_app.report_card_cbse_app.db_script.populate_term_and_extra_field import populate_term_and_extra_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0038_auto_20191130_2039'),
        ('student_app', '0024_auto_20190901_1142'),
        ('examination_app', '0012_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='-', verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceStartDate', models.DateField(null=True, verbose_name='attendanceStartDate')),
                ('attendanceEndDate', models.DateField(null=True, verbose_name='attendanceEndDate')),
                ('parentExaminationFinalTerm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportcardmapping_final_term', to='examination_app.Examination', verbose_name='parentExaminationFinalTerm')),
                ('parentExaminationNoteBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportcardmapping_note_book', to='examination_app.Examination', verbose_name='parentExaminationNoteBook')),
                ('parentExaminationPeriodicTest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportcardmapping_periodic_test', to='examination_app.Examination', verbose_name='parentExaminationPeriodicTest')),
                ('parentExaminationSubEnrichment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportcardmapping_sub_enrichment', to='examination_app.Examination', verbose_name='parentExaminationSubEnrichment')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2, verbose_name='grade')),
                ('parentExtraField', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='report_card_cbse_app.ExtraField', verbose_name='parentExtraField')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='-', verbose_name='remark')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='-', verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='studentextrafield',
            name='parentTerm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='report_card_cbse_app.Term', verbose_name='parentTerm'),
        ),
        migrations.AddField(
            model_name='reportcardmapping',
            name='parentTerm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='report_card_cbse_app.Term', verbose_name='parentTerm'),
        ),
        migrations.AlterUniqueTogether(
            name='studentremark',
            unique_together=set([('parentStudent', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentextrafield',
            unique_together=set([('parentExtraField', 'parentStudent', 'parentTerm', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='reportcardmapping',
            unique_together=set([('parentSchool', 'parentSession', 'parentTerm')]),
        ),
        migrations.RunPython(populate_term_and_extra_field),
    ]
