# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_cbse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTeacherRemark',
            new_name='StudentRemark',
        ),
    ]
