# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-26 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_cbse_app', '0002_auto_20191125_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentremark',
            name='remark',
            field=models.TextField(blank=True, default='-', verbose_name='remark'),
        ),
    ]
