# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_app', '0001_initial'),
        ('school_app', '0001_initial'),
        ('class_app', '0001_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision')),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'attendance_permission',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentUpdateType', models.CharField(choices=[('SMS', 'SMS'), ('NOTIFICATION', 'NOTIFICATION'), ('NOTIF./SMS', 'NOTIF./SMS'), ('NULL', 'NULL')], default='NULL', max_length=20, verbose_name='sentUpdateType')),
                ('receiverType', models.CharField(choices=[('All Students', 'All Students'), ('Only Absent Students', 'Only Absent Students')], default='All Students', max_length=20, verbose_name='receiverType')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'attendance_settings',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppliedLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfLeave', models.DateField(default='2011-01-01', verbose_name='dateOfLeave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('halfDay', models.BooleanField(default=False, verbose_name='halfDay')),
                ('paidLeave', models.BooleanField(default=True, verbose_name='paidLeave')),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
            options={
                'db_table': 'employee_applied_leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAttendance', models.DateField(default='2011-01-01', verbose_name='dateOfAttendance')),
                ('status', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('HOLIDAY', 'Holiday'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10)),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
            options={
                'db_table': 'employee_attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAttendance', models.DateField(default='2011-01-01', verbose_name='dateOfAttendance')),
                ('status', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('HOLIDAY', 'Holiday'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10)),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_attendance',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set([('parentStudent', 'dateOfAttendance')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=set([('parentEmployee', 'dateOfAttendance')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeeappliedleave',
            unique_together=set([('parentEmployee', 'dateOfLeave')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendancepermission',
            unique_together=set([('parentEmployee', 'parentDivision', 'parentClass', 'parentSession')]),
        ),
    ]
