# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_attendancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='sentUpdateToType',
            field=models.CharField(choices=[('All Students', 'All Students'), ('Only Absent Students', 'Only Absent Students')], default='All Students', max_length=20, verbose_name='sentUpdateToType'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='sentUpdateType',
            field=models.CharField(choices=[('SMS', 'SMS'), ('NOTIFICATION', 'NOTIFICATION'), ('NOTIF./SMS', 'NOTIF./SMS')], default='SMS', max_length=20, verbose_name='sentUpdateType'),
        ),
    ]
