
export const STUDENT_BASE_MODEL = {
    id : 0,
    name : '-----',
    fathersName: '-----',
    mobileNumber: null,
    scholarNumber : null,
    dateOfBirth : null,
    remark : null,
    motherName : null,
    gender : null,
    caste : null,
    newCategoryField : null,
    newReligionField : null,
    fatherOccupation : null,
    address : null,
    familySSMID : null,
    childSSMID : null,
    bankName : null,
    bankAccountNum : null,
    aadharNum : null,
    bloodGroup : null,
    fatherAnnualIncome : null,
    currentBusStop : null,
    admissionSession : null,
    parentSchool : 0,
    parentTransferCertificate : null,
    profileImage : null,
    dateOfAdmission : null,
    bankIfscCode : null,
    secondMobileNumber:  null,
    rte : null
};

