# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 17:43
from __future__ import unicode_literals

from django.db import migrations

from salary_app.db_script.add_print_salary_sheet_task import add_print_salary_sheet_task


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0002_auto_20181018_1524'),
    ]

    operations = [
        migrations.RunPython(add_print_salary_sheet_task),
    ]
