# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-20 18:50
from __future__ import unicode_literals

from django.db import migrations
from enquiry_app.db_script.access_enquiry_app2 import access_enquiry_app


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0003_enquiry_parentemployee'),
    ]

    operations = [
        migrations.RunPython(access_enquiry_app),
    ]
