# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Online', 'Online')], max_length=20, null=True),
        ),
    ]
