# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='aprilMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='aprilMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='augustMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='augustMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='decemberMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='decemberMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='februaryMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='februaryMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='januaryMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='januaryMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='julyMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='julyMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='juneMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='juneMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='marchMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='marchMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='mayMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='mayMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='novemberMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='novemberMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='octoberMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='octoberMaximumLateFee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='septemberMaximumLateFee',
            field=models.IntegerField(null=True, verbose_name='septemberMaximumLateFee'),
        ),
    ]
