# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0003_auto_20190725_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='chequeNumber',
            field=models.IntegerField(null=True, verbose_name='chequeNumber'),
        ),
    ]
