# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-02 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='error',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='error',
            name='errorSource',
            field=models.CharField(choices=[('REST_API_SOURCE', 'rest_api'), ('JAVASCRIPT_SOURCE', 'js_runtime')], max_length=50, verbose_name='Error Source'),
        ),
        migrations.AlterField(
            model_name='error',
            name='prompt',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='error',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
