# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors_app', '0002_auto_20210302_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='url',
            field=models.TextField(),
        ),
    ]
