# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNumber', models.TextField()),
                ('amount', models.IntegerField()),
                ('remark', models.TextField()),
                ('voucherDate', models.DateField()),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
