# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_student_scholarnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarNumber',
            field=models.IntegerField(null=True),
        ),
    ]
