# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20180112_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='generationDateTime',
            field=models.DateField(),
        ),
    ]
