# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_subfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadharNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bankAccountNum',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bankName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bloodGroup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='childSSMID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='familySSMID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fatherAnnualIncome',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fatherOccupation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='motherName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.TextField(null=True),
        ),
    ]
