# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20180123_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='totalFees',
            field=models.IntegerField(default=0),
        ),
    ]
