# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20180126_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollNumber',
            field=models.TextField(null=True),
        ),
    ]
