# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_auto_20180201_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfee',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
