# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import school_app.model_custom_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0011_auto_20180204_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('printName', models.TextField(null=True)),
                ('logo', school_app.model_custom_field.CustomImageField(upload_to='tmp')),
                ('primaryThemeColor', models.TextField(null=True)),
                ('secondaryThemeColor', models.TextField(null=True)),
                ('complexFeeStructure', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
