# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='newCategoryField',
            field=models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Classes'), ('Gen.', 'General')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='newReligionField',
            field=models.CharField(choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Jainism', 'Jainism')], max_length=20, null=True),
        ),
    ]
