# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_auto_20180210_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(default='', null=True),
        ),
    ]
