# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from school_app.db_script.populate_current_session import populate_current_session, shift_student


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0020_auto_20180321_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='currentSession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='currentSession'),
        ),
        migrations.RunPython(populate_current_session),
        migrations.RunPython(shift_student),
    ]
