# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20180406_1312'),
        ('examination_app', '0002_auto_20180406_1312'),
        ('school_app', '0021_school_currentsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concession',
            name='parentStudent',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='parentStudent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentUser',
        ),
        migrations.RemoveField(
            model_name='subfee',
            name='parentFee',
        ),
        migrations.DeleteModel(
            name='Concession',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='SubFee',
        ),
    ]
