# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models

from school_app.db_script.populate_brightstar_for_marksheet import populate_brightstar_for_marksheet


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0023_auto_20180406_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='registrationNumber',
            field=models.TextField(default='-'),
        ),
        migrations.RunPython(populate_brightstar_for_marksheet),
    ]
