# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 12:36
from __future__ import unicode_literals

from django.db import migrations

from school_app.db_script.populate_user_first_name import populate_user_first_name

class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0027_school_smsid'),
    ]

    operations = [
        migrations.RunPython(populate_user_first_name),
    ]
