# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0029_school_mobilenumber'),
        ('school_app', '0028_auto_20180621_1806'),
    ]

    operations = [
    ]
