# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0030_merge_20180828_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='medium',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi')], default='ENGLISH', max_length=15),
        )
    ]
