# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models

from school_app.db_script.populate_school_header_size import populate_school_header_size


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0031_school_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='headerSize',
            field=models.CharField(choices=[('BIG', 'Big'), ('SMALL', 'Small')], default='SMALL', max_length=15),
        ),
        migrations.RunPython(populate_school_header_size),
    ]
