# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dateOfCreation',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_of_creation'),
        ),
        migrations.AddField(
            model_name='school',
            name='dateOfExpiry',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date_of_expiry'),
        ),
    ]
