# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-12 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('advantage', models.TextField(null=True)),
                ('frequency', models.TextField(null=True)),
                ('managedBy', models.TextField(null=True)),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='parentUser')),
            ],
            options={
                'db_table': 'feature',
            },
        ),
    ]
