# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('advantage', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('managedBy', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('productManagerRemark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
    ]
