# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='parentUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='parentUser'),
        ),
    ]
