# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='productManagerRemark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
