# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-28 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='what',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='how',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='why',
        ),
    ]
