# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 09:36
from __future__ import unicode_literals

from django.db import migrations

from fee_second_app.db_script.initialize_fee_database import initialize_fee_database
from student_app.db_script.delete_aatifkhan_profile import delete_aatifkhan_profile


class Migration(migrations.Migration):

    dependencies = [
        ('fee_second_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_aatifkhan_profile),
        migrations.RunPython(initialize_fee_database),
    ]
