# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from fee_second_app.db_script.update_all_student_fee_dues import update_all_student_fees


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_auto_20180807_0927'),
        ('fee_second_app', '0003_auto_20180603_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeDues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_fee_dues',
            },
        ),
        migrations.RunPython(update_all_student_fees),
    ]
