# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from fee_second_app.db_script.transfer_responsibility_from_user_to_employee import transfer_responsibility_from_user_to_employee

class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20180918_1556'),
        ('fee_second_app', '0004_studentfeedues'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionsecond',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.RunPython(transfer_responsibility_from_user_to_employee),
    ]
