# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from attendance_app.db_script.access_attendance_app import access_attendance_app

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0012_auto_20180807_0927'),
        ('class_app', '0003_marksheet'),
        ('school_app', '0029_school_mobilenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSection', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Section', verbose_name='parentSection')),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='parentUser')),
            ],
            options={
                'db_table': 'attendance_permission',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAttendance', models.DateField(auto_now_add=True, verbose_name='dateOfAttendance')),
                ('status', models.CharField(choices=[('ABSENT', 'Absent'), ('HOLIDAY', 'Holiday')], default='ABSENT', max_length=10)),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_attendance',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set([('parentStudent', 'dateOfAttendance', 'status'), ('parentStudent', 'dateOfAttendance')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendancepermission',
            unique_together=set([('parentSchool', 'parentUser', 'parentSection')]),
        ),
        migrations.RunPython(access_attendance_app),
    ]
