# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from attendance_app.db_script.refactor_attendance_permission import refactor_attendance_permission

class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_division'),
        ('employee_app', '0005_employee_dateofleaving'),
        ('school_app', '0032_school_headersize'),
        ('attendance_app', '0006_auto_20180921_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermission',
            name='parentClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass'),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='parentDivision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision'),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.RunPython(refactor_attendance_permission),
        migrations.AlterUniqueTogether(
            name='attendancepermission',
            unique_together=set([('parentEmployee', 'parentDivision', 'parentClass', 'parentSession')]),
        ),
        migrations.RemoveField(
            model_name='attendancepermission',
            name='parentSection',
        ),
    ]
