# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_auto_20181111_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
    ]
