# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-30 02:52
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_manage_sms_id_and_templates_tasks import add_manage_sms_id_and_templates_tasks
from team_app.db_script.remove_setting_pages import remove_setting_pages


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_manage_sms_id_and_templates_tasks),
        migrations.RunPython(remove_setting_pages)
    ]
