# Generated by Django 3.2.5 on 2021-08-22 06:31

from django.db import migrations
from team_app.db_script.add_online_payment_account_page import add_online_payment_account_page
from team_app.db_script.add_purchase_sms_task import add_purchase_sms_to_sms

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_add_block_student_task'),
    ]

    operations = [
        migrations.RunPython(add_online_payment_account_page),
        migrations.RunPython(add_purchase_sms_to_sms),
    ]
