# Generated by Django 3.2.5 on 2021-11-17 12:50

from django.db import migrations

from team_app.db_script.migrate_promote_student_change_class import migrate_promote_student_change_class

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_add_sms_new_pages_remove_settings_pages'),
    ]

    operations = [
        migrations.RunPython(migrate_promote_student_change_class)
    ]
