# Generated by Django 3.2.5 on 2021-10-28 08:43

from django.db import migrations
from team_app.db_script.add_my_design_module import add_my_design_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_add_sms_new_pages_remove_settings_pages'),
    ]

    operations = [
        migrations.RunPython(add_my_design_module),
    ]
