# Generated by Django 3.2.5 on 2021-11-23 06:50

from django.db import migrations

from team_app.db_script.add_demote_student import add_demote_student

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_migrate_promote_student_change_class'),
    ]

    operations = [
        migrations.RunPython(add_demote_student)
    ]
