# Generated by Django 3.2.5 on 2021-10-28 13:41

from django.db import migrations
from team_app.db_script.add_my_design_module import add_my_design_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_auto_20211012_1713'),
    ]

    operations = [
        migrations.RunPython(add_my_design_module),
    ]
