# Generated by Django 3.2.5 on 2021-12-16 13:02

from django.db import migrations

from team_app.db_script.adding_bill_module import adding_bill_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_auto_20211012_1713'),
    ]

    operations = [
        migrations.RunPython(adding_bill_module),
    ]
