# Generated by Django 3.2.5 on 2021-11-25 06:35

from django.db import migrations

from team_app.db_script.modify_update_marks_task_name import modify_update_marks_task_name


class Migration(migrations.Migration):
    dependencies = [
        ('team_app', '0004_auto_20211012_1713'),
    ]

    operations = [
        migrations.RunPython(modify_update_marks_task_name)
    ]
