# Generated by Django 3.2.5 on 2021-12-12 07:04

from django.db import migrations

from team_app.db_script.add_student_task_count import add_student_task_count


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_renaming_task'),
    ]

    operations = [
        migrations.RunPython(add_student_task_count)
    ]
