# Generated by Django 3.2.5 on 2021-12-15 12:13

from django.db import migrations

from team_app.db_script.migrate_promote_student_change_class import migrate_promote_student_change_class
from team_app.db_script.add_unpromote_student import add_unpromote_student

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_renaming_task'),
    ]

    operations = [
        migrations.RunPython(migrate_promote_student_change_class),
        migrations.RunPython(add_unpromote_student)
    ]
