# Generated by Django 3.2.5 on 2022-01-04 07:16

from django.db import migrations

from team_app.db_script.add_activity_Module_trackEmployeeActivity_Task import add_activity_Module_trackEmployeeActivity_Task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_renaming_task'),
    ]

    operations = [
        migrations.RunPython(add_activity_Module_trackEmployeeActivity_Task),
    ]
