# Generated by Django 3.2.5 on 2022-01-10 06:55

from django.db import migrations

from team_app.db_script.add_parentSupport_module import add_parentSupport_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_renaming_task'),
    ]

    operations = [
        migrations.RunPython(add_parentSupport_module)
    ]
