# Generated by Django 3.2.5 on 2022-01-26 04:26

from django.db import migrations

from team_app.db_script.add_activity_Module_trackEmployeeActivity_Task import add_activity_Module_trackEmployeeActivity_Task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_auto_20211215_1743'),
    ]

    operations = [
        migrations.RunPython(add_activity_Module_trackEmployeeActivity_Task)
    ]
