# Generated by Django 3.2.5 on 2022-01-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_auto_20211215_1743'),
        ('team_app', '0006_auto_20220103_1347'),
    ]

    operations = [
    ]
