# Generated by Django 3.2.5 on 2021-12-27 09:19

from django.db import migrations

from team_app.db_script.add_track_employee_activity_task_to_employeePermission import add_track_employee_activity_task_to_employeePermission


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_auto_20211227_1322'),
    ]

    operations = [
        migrations.RunPython(add_track_employee_activity_task_to_employeePermission)
    ]
