# Generated by Django 3.2.5 on 2022-01-26 10:59

from django.db import migrations

from team_app.db_script.add_student_task_count import add_student_task_count


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0007_auto_20220126_0956'),
    ]

    operations = [
        migrations.RunPython(add_student_task_count)
    ]
