# Generated by Django 3.2.5 on 2021-12-12 11:32

from django.db import migrations

from team_app.db_script.add_count_all_task_employeePermission import add_count_all_task_employeePermission


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0007_auto_20211212_1534'),
    ]

    operations = [
        migrations.RunPython(add_count_all_task_employeePermission)
    ]
