# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-15 15:00
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_delete_employee_task import add_delete_employee_task_and_permission


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_auto_20200325_1629'),
    ]

    operations = [
        migrations.RunPython(add_delete_employee_task_and_permission)
    ]
