# Generated by Django 3.2.5 on 2022-03-27 11:50

from django.db import migrations

from team_app.db_script.add_complaints_module import add_complaints_module



class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_auto_20220126_1629'),
    ]

    operations = [
        migrations.RunPython(add_complaints_module)
    ]
