# Generated by Django 3.2.5 on 2022-02-04 11:30

from django.db import migrations
from team_app.db_script.add_parentSupport_module import add_parentSupport_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_auto_20220126_1629'),
    ]

    operations = [
        migrations.RunPython(add_parentSupport_module)
    ]
