# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-16 13:20
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_update_all_task import add_update_all_task_and_permission

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_auto_20200415_2030'),
    ]

    operations = [
        migrations.RunPython(add_update_all_task_and_permission)
    ]
