# Generated by Django 3.2.5 on 2022-06-13 20:26

from django.db import migrations
from team_app.db_script.change_complaint_module_orderNumber import change_complaint_module_orderNumber


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_auto_20220327_1720'),
    ]

    operations = [
        migrations.RunPython(change_complaint_module_orderNumber)
    ]
