# Generated by Django 3.2.5 on 2022-06-18 19:57

from django.db import migrations
from team_app.db_script.add_deprecated_Module_add_Tasks import add_deprecated_Module,add_deprecated_Tasks
from team_app.db_script.move_modules_to_deprecated import move_report_card_mp_board_to_deprecated, move_report_card_cbse_to_deprecated, move_expenses_to_deprecated
from team_app.db_script.remove_id_card_module import remove_id_card_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_auto_20220327_1720'),
    ]

    operations = [
        migrations.RunPython(add_deprecated_Module),
        migrations.RunPython(add_deprecated_Tasks),
        migrations.RunPython(move_report_card_mp_board_to_deprecated),
        migrations.RunPython(move_report_card_cbse_to_deprecated),
        migrations.RunPython(move_expenses_to_deprecated),
        migrations.RunPython(remove_id_card_module)
    ]
