# Generated by Django 3.2.5 on 2022-06-28 12:22

from django.db import migrations
from team_app.db_script.change_complaint_module_orderNumber import change_complaint_module_orderNumber
from team_app.db_script.admin_user_permission_manage_complaints_page import admin_user_permission_manage_complaints_page


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_auto_20220327_1720'),
    ]

    operations = [
        migrations.RunPython(change_complaint_module_orderNumber),
        migrations.RunPython(admin_user_permission_manage_complaints_page)
    ]
