# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-22 17:58
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_print_student_profile_task import add_print_student_profile_task_and_permission

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20200416_1850'),
    ]

    operations = [
        migrations.RunPython(add_print_student_profile_task_and_permission)
    ]
