# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-19 08:51
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_id_card_module import add_id_card_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20200416_1850'),
        ('id_card_app', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_id_card_module)
    ]
