# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-22 09:19
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_manage_parameter_page import add_manage_parameter_page


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20200416_1850'),
    ]

    operations = [
        migrations.RunPython(add_manage_parameter_page)
    ]
