# Generated by Django 3.2.5 on 2022-08-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20220619_0127'),
        ('team_app', '0010_auto_20220628_1752'),
    ]

    operations = [
    ]
