# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-04 18:00
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_custom_report_card_module import add_custom_report_card_module
from team_app.db_script.add_manage_layout_task import add_manage_layout_task
from team_app.db_script.add_set_class_layout_task import add_set_class_layout_task
from team_app.db_script.add_student_remarks_task import add_student_remarks_task
from team_app.db_script.add_generate_final_report_task import add_generate_final_report_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20200303_2003'),
    ]

    operations = [
    	migrations.RunPython(add_custom_report_card_module),
    	migrations.RunPython(add_manage_layout_task),
        migrations.RunPython(add_set_class_layout_task),
        migrations.RunPython(add_student_remarks_task),
        migrations.RunPython(add_generate_final_report_task),
    ]
