# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-08-22 11:03
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_id_card_module import add_id_card_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0011_auto_20200722_2328'),
    ]

    operations = [
        migrations.RunPython(add_id_card_module)
    ]
