# Generated by Django 3.2.5 on 2022-11-14 04:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0001_initial'),
        ('team_app', '0011_merge_0010_auto_20220619_0127_0010_auto_20220628_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parentFeatureFlag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature_flag_app.featureflag', verbose_name='parentFeatureFlag'),
        ),
        migrations.AddField(
            model_name='task',
            name='parentFeatureFlag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature_flag_app.featureflag', verbose_name='parentFeatureFlag'),
        ),
    ]
