# Generated by Django 3.2.5 on 2022-11-14 04:20

from django.db import migrations
from team_app.db_script.add_pages_for_backtrack import add_backtrack_student,add_manage_student_sessions


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0012_auto_20221114_0936'),
    ]

    operations = [
        migrations.RunPython(add_backtrack_student),
        migrations.RunPython(add_manage_student_sessions),
    ]
