# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-28 00:31
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.adding_grade_module import add_grade_module
from team_app.db_script.add_create_grade_task import add_create_grade_task_and_permission
from team_app.db_script.add_grade_student_task import add_grade_student_and_permission
from team_app.db_script.add_view_grade_and_permission import add_view_grade_and_permission
from team_app.db_script.add_custom_report_card_module import add_custom_report_card_module
from team_app.db_script.add_manage_layout_task import add_manage_layout_task
from team_app.db_script.add_set_class_layout_task import add_set_class_layout_task
from team_app.db_script.add_student_remarks_task import add_student_remarks_task
from team_app.db_script.add_generate_final_report_task import add_generate_final_report_task
from team_app.db_script.add_report_card_two_module import add_report_card_two_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0013_task_videourl'),
    ]

    operations = [
        migrations.RunPython(add_grade_module),
        migrations.RunPython(add_create_grade_task_and_permission),
        migrations.RunPython(add_grade_student_and_permission),
        migrations.RunPython(add_view_grade_and_permission),
        migrations.RunPython(add_custom_report_card_module),
        migrations.RunPython(add_manage_layout_task),
        migrations.RunPython(add_set_class_layout_task),
        migrations.RunPython(add_student_remarks_task),
        migrations.RunPython(add_generate_final_report_task),
        migrations.RunPython(add_report_card_two_module)
    ]
