# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-09 11:00
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_schedule_test_to_examination import add_schedule_test_to_examination

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0013_task_videourl'),
    ]

    operations = [
        migrations.RunPython(add_schedule_test_to_examination)

    ]
