# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-20 14:10
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_update_via_excel_task import add_update_via_excel_and_permission

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20201119_1559'),
    ]

    operations = [
        migrations.RunPython(add_update_via_excel_and_permission)
    ]
