# Generated by Django 3.2.5 on 2023-01-08 15:04

from django.db import migrations
from team_app.db_script.add_purchase_sms_2 import add_purchase_sms_2

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20221214_1524'),
    ]

    operations = [
        migrations.RunPython(add_purchase_sms_2),
    ]
