# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 12:08
from __future__ import unicode_literals

from django.db import migrations

from homework_app.db_script.add_settings_task import add_settings_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20201208_1447'),
    ]

    operations = [
        migrations.RunPython(add_settings_task),
    ]
