# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-14 11:08
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_attendance_settings_task import add_attendance_settings_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20201120_1940'),
    ]

    operations = [
        migrations.RunPython(add_attendance_settings_task)
    ]
