# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-26 12:20
from __future__ import unicode_literals

from django.db import migrations
from homework_app.db_script.access_homework_app import access_homework_app


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20201120_1940'),
    ]

    operations = [
        migrations.RunPython(access_homework_app),
    ]
