# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20201209_1630'),
        ('team_app', '0014_auto_20201120_1940'),
    ]

    operations = [
    ]
