# Generated by Django 3.2.5 on 2023-01-06 15:49

from django.db import migrations
from team_app.db_script.add_remove_duplicate_marks import add_remove_duplicate_marks


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_auto_20221214_1524'),
    ]

    operations = [
        migrations.RunPython(add_remove_duplicate_marks),
    ]
