# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-02 18:00
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_tutorials_module import add_tutorials_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_auto_20201226_1750'),
    ]

    operations = [
        migrations.RunPython(add_tutorials_module)
    ]
