# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-23 09:32
from __future__ import unicode_literals

from django.db import migrations
from tutorial_app.db_script.add_tutorial_settings_task import add_tutorial_settings_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_auto_20201214_1418'),
    ]

    operations = [
        migrations.RunPython(add_tutorial_settings_task),
    ]
