# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-21 10:15
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.adding_report_card_3_module_and_tasks import add_report_card_3_module, add_design_report_card_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_auto_20201028_0601'),
    ]

    operations = [
        migrations.RunPython(add_report_card_3_module),
        migrations.RunPython(add_design_report_card_task)
    ]
