# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 13:03
from __future__ import unicode_literals

from django.db import migrations
from homework_app.db_script.populate_settings_task import populate_settings_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_auto_20201215_1738'),
    ]

    operations = [
        migrations.RunPython(populate_settings_task),
    ]
