# Generated by Django 3.2.5 on 2023-01-13 10:10

from django.db import migrations
from team_app.db_script.add_purchase_sms_2 import add_purchase_sms_2


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_auto_20230106_2119'),
    ]

    operations = [
        migrations.RunPython(add_purchase_sms_2)
    ]
