# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-20 15:56
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.adding_report_card_3_module_and_tasks import add_generate_report_card_task



class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0016_auto_20201221_1545'),
    ]

    operations = [
        migrations.RunPython(add_generate_report_card_task),
    ]
