# Generated by Django 3.2.5 on 2023-01-13 22:01

from django.db import migrations
from team_app.db_script.add_add_via_excel_task import add_add_via_excel_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0016_auto_20230113_1540'),
    ]

    operations = [
        migrations.RunPython(add_add_via_excel_task),
    ]
