# Generated by Django 3.2.5 on 2023-02-20 12:19

from django.db import migrations
from team_app.db_script.add_salary2_module import add_salary2_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0017_auto_20230114_0331'),
    ]

    operations = [
        migrations.RunPython(add_salary2_module)
    ]
