# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_merge_20210111_2018'),
        ('team_app', '0017_auto_20210107_1319'),
    ]

    operations = [
    ]
