# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-31 05:43
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_attendance_settings_task import add_attendance_settings_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_auto_20210116_1220'),
    ]

    operations = [
        migrations.RunPython(add_attendance_settings_task),
    ]
