# Generated by Django 3.2.5 on 2023-03-01 08:11

from django.db import migrations
from team_app.db_script.add_leaves_module import add_leaves_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_auto_20230220_1749'),
    ]

    operations = [
        migrations.RunPython(add_leaves_module)
    ]
