# Generated by Django 3.2.5 on 2023-02-25 10:24

from django.db import migrations
from team_app.db_script.add_library_module import add_library_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_auto_20230220_1749'),
    ]

    operations = [
        migrations.RunPython(add_library_module)
    ]
