# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-31 06:06
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.adding_grade_module import add_grade_module
from team_app.db_script.add_create_grade_task import add_create_grade_task_and_permission
from team_app.db_script.add_grade_student_task import add_grade_student_and_permission
from team_app.db_script.add_view_grade_and_permission import add_view_grade_and_permission
from team_app.db_script.add_remarks_task import add_remarks_task
from team_app.db_script.view_remarks_task import view_remarks_task
from team_app.db_script.adding_report_card_3_module_and_tasks import add_report_card_3_module, add_design_report_card_task, add_generate_report_card_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_auto_20210116_1220'),
    ]

    operations = [
        migrations.RunPython(add_grade_module),
        migrations.RunPython(add_create_grade_task_and_permission),
        migrations.RunPython(add_grade_student_and_permission),
        migrations.RunPython(add_view_grade_and_permission),
        migrations.RunPython(add_remarks_task),
        migrations.RunPython(view_remarks_task),
        migrations.RunPython(add_report_card_3_module),
        migrations.RunPython(add_design_report_card_task),
        migrations.RunPython(add_generate_report_card_task),
    ]