# Generated by Django 3.2.5 on 2023-03-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0019_auto_20230225_1554'),
        ('team_app', '0019_auto_20230301_1341'),
    ]

    operations = [
    ]
