# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0019_auto_20210124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parentBoard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
    ]
