# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-25 10:20
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.rc_version_change import rc_versin_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_auto_20210131_1159'),
    ]

    operations = [
        migrations.RunPython(rc_versin_upgrade)
    ]
