# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-08 19:53
from __future__ import unicode_literals

from django.db import migrations
from accounts_app.db_script.add_accounts_app import add_accounts_app

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_auto_20210131_1159'),
    ]

    operations = [
        migrations.RunPython(add_accounts_app),
    ]
