# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-05 12:04
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_event_gallery_module import add_event_gallery_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_auto_20210131_1159'),
    ]

    operations = [
        migrations.RunPython(add_event_gallery_module),
    ]
