# Generated by Django 3.2.5 on 2023-03-30 16:13

from django.db import migrations
from team_app.db_script.add_school_website_module_and_task import add_school_website_module_and_task



class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_merge_0019_auto_20230225_1554_0019_auto_20230301_1341'),
        ('feature_flag_app', '0008_auto_20230330_2143')
    ]

    operations = [
        migrations.RunPython(add_school_website_module_and_task)
    ]
