# Generated by Django 3.2.5 on 2023-03-14 12:00

from django.db import migrations
from team_app.db_script.add_leaves_module import add_manage_plans

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_merge_0019_auto_20230225_1554_0019_auto_20230301_1341'),
    ]

    operations = [
        migrations.RunPython(add_manage_plans)
    ]