# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-08 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_auto_20210125_1639'),
        ('team_app', '0020_auto_20210131_1159'),
    ]

    operations = [
    ]
