# Generated by Django 3.2.5 on 2023-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0021_auto_20230314_1730'),
        ('team_app', '0021_auto_20230330_2143'),
    ]

    operations = [
    ]
