# Generated by Django 3.2.5 on 2023-04-06 12:27

from django.db import migrations

from team_app.db_script.add_fee_receipt_book import add_fee_receipt_book_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0021_auto_20230330_2143'),
    ]

    operations = [
        migrations.RunPython(add_fee_receipt_book_task),
    ]
