# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-12 19:20
from __future__ import unicode_literals

from django.db import migrations
from accounts_app.db_script.add_accounts_app import add_accounts_app


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0021_auto_20210225_1550'),
    ]

    operations = [
        migrations.RunPython(add_accounts_app),
    ]
