# Generated by Django 3.2.5 on 2023-04-08 11:25

from django.db import migrations
from team_app.db_script.add_leaves_module import add_manage_plans

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0021_auto_20230330_2143'),
    ]

    operations = [
        migrations.RunPython(add_manage_plans)
    ]
