# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-21 14:14
from __future__ import unicode_literals

from django.db import migrations
from accounts_app.db_script.add_accounts_app import add_accounts_app


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0022_auto_20210318_1656'),
    ]

    operations = [
        migrations.RunPython(add_accounts_app),
    ]
