# Generated by Django 3.2.5 on 2023-04-11 16:41

from django.db import migrations
from team_app.db_script.add_leaves_module import add_manage_leave_plans

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0022_auto_20230408_1655'),
    ]

    operations = [
        migrations.RunPython(add_manage_leave_plans)
    ]
