# Generated by Django 3.2.5 on 2023-06-23 07:26

from django.db import migrations
from team_app.db_script.add_leaves_module import move_leaves_module

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0022_auto_20230408_1655'),
    ]

    operations = [
        migrations.RunPython(move_leaves_module)
    ]
