# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-28 10:52
from __future__ import unicode_literals

from django.db import migrations

from accounts_app.db_script.rename_my_approval_requests import rename_my_approval_requests
from fees_third_app.db_script.rename_lock_fees import rename_lock_fees


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0023_auto_20210321_1944'),
    ]

    operations = [
        migrations.RunPython(rename_my_approval_requests),
        migrations.RunPython(rename_lock_fees),
    ]
