# Generated by Django 3.2.5 on 2023-06-26 18:52

from django.db import migrations
from team_app.db_script.add_leaves_module import add_manage_leave_plans

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0023_auto_20230623_1256'),
    ]

    operations = [
        migrations.RunPython(add_manage_leave_plans)
    ]
