# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-13 06:03
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_tc_module_and_tasks import add_tc_module_and_tasks


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0023_auto_20210321_1944'),
    ]

    operations = [
        migrations.RunPython(add_tc_module_and_tasks)
    ]
