# Generated by Django 3.2.5 on 2023-07-06 08:03

from django.db import migrations
from team_app.db_script.add_leaves_module import rename_leaves_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0024_auto_20230627_0022'),
    ]

    operations = [
        migrations.RunPython(rename_leaves_module)
    ]
