# Generated by Django 3.2.5 on 2023-07-17 09:17

from django.db import migrations

from team_app.db_script.add_fee_receipt_book import add_fee_receipt_book_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0025_auto_20230706_1333'),
    ]

    operations = [
        migrations.RunPython(add_fee_receipt_book_task)
    ]
