# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-30 02:52
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_manage_sms_id_task import add_manage_sms_id_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0025_auto_20210420_1018'),
    ]

    operations = [
        migrations.RunPython(add_manage_sms_id_task)
    ]
