# Generated by Django 3.2.5 on 2023-08-14 14:11

from django.db import migrations

from team_app.db_script.add_fee_receipt_book import add_fee_receipt_book_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0026_auto_20230724_1648'),
    ]

    operations = [
        migrations.RunPython(add_fee_receipt_book_task)
    ]
