# Generated by Django 3.2.5 on 2023-09-01 08:56

from django.db import migrations
from team_app.db_script.add_library_phase_2_pages import add_library_phase_2_pages


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0026_auto_20230724_1648'),
    ]

    operations = [
        migrations.RunPython(add_library_phase_2_pages),
    ]
