# Generated by Django 3.2.5 on 2023-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0026_billing_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blockWhenSuspended',
            field=models.BooleanField(default=False),
        ),
    ]
