# Generated by Django 3.2.5 on 2023-08-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0008_auto_20230330_2143'),
        ('team_app', '0027_task_blockwhensuspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parentFeatureFlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature_flag_app.featureflag', verbose_name='parentFeatureFlag'),
        ),
    ]
