# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-31 12:42
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.online_class_add_tasks import online_class_add_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0027_auto_20210527_1853'),
    ]

    operations = [
        migrations.RunPython(online_class_add_task)
    ]
