# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-12 05:14
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.online_class_join_all_task import online_class_join_all_task


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0028_auto_20210531_1812'),
    ]

    operations = [
        migrations.RunPython(online_class_join_all_task)
    ]
