# Generated by Django 3.2.5 on 2023-09-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0028_auto_20230909_1222'),
        ('team_app', '0028_auto_20230910_0159'),
    ]

    operations = [
    ]
