# Generated by Django 3.2.5 on 2023-09-09 06:52

from django.db import migrations, models
import django.db.models.deletion

from team_app.db_script.adding_bill_module import adding_bill_module


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0009_auto_20230901_1425'),
        ('team_app', '0029_auto_20230913_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blockWhenSuspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='parentFeatureFlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature_flag_app.featureflag', verbose_name='parentFeatureFlag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='videoUrl',
            field=models.TextField(blank=True, null=True, verbose_name='videoUrl'),
        ),
        migrations.RunPython(adding_bill_module),
    ]
