# Generated by Django 3.2.5 on 2023-09-27 14:21

from django.db import migrations
from team_app.db_script.add_fees_view_list_page import add_fees_view_list_page


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0029_auto_20230913_1019'),
    ]

    operations = [
        migrations.RunPython(add_fees_view_list_page)
    ]
