# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-04 12:21
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.remove_setting_pages import remove_setting_pages


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0029_auto_20210430_0822'),
    ]

    operations = [
        migrations.RunPython(remove_setting_pages)
    ]
