# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-29 12:26
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_purchase_sms_task import add_purchase_sms_to_sms


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0030_auto_20210213_1210'),
    ]

    operations = [
        migrations.RunPython(add_purchase_sms_to_sms)
    ]
