# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-25 11:27
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_my_design_module import add_my_design_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0031_auto_20210707_1805'),
    ]

    operations = [
        migrations.RunPython(add_my_design_module)
    ]
