# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination_app', '0014_auto_20200107_0516'),
        ('school_app', '0039_auto_20200104_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('showLetterHead', models.ImageField(null=True, upload_to='')),
                ('showAttendanceStartDate', models.IntegerField(default=0, null=True, verbose_name='showAttendanceStartDate')),
                ('showAttendanceEndDate', models.IntegerField(default=0, null=True, verbose_name='showAttendanceEndDate')),
                ('showStudentName', models.IntegerField(default=0, null=True, verbose_name='showStudentName')),
                ('showFatherName', models.IntegerField(default=0, null=True, verbose_name='showFatherName')),
                ('showMotherName', models.IntegerField(default=0, null=True, verbose_name='showMotherName')),
                ('showRollNo', models.IntegerField(default=0, null=True, verbose_name='showRollNo')),
                ('showScholarNo', models.IntegerField(default=0, null=True, verbose_name='showScholarNo')),
                ('showDateOfBirth', models.IntegerField(default=0, null=True, verbose_name='showDateOfBirth')),
                ('showDateOfBirthInWords', models.IntegerField(default=0, null=True, verbose_name='showDateOfBirthInWords')),
                ('showAadharNumber', models.IntegerField(default=0, null=True, verbose_name='showAadharNumber')),
                ('showCategory', models.IntegerField(default=0, null=True, verbose_name='showCategory')),
                ('showFamilySSMID', models.IntegerField(default=0, null=True, verbose_name='showFamilySSMID')),
                ('showChildSSMID', models.IntegerField(default=0, null=True, verbose_name='showChildSSMID')),
                ('showClass', models.IntegerField(default=0, null=True, verbose_name='showClass')),
                ('showSection', models.IntegerField(default=0, null=True, verbose_name='showSection')),
                ('showCaste', models.IntegerField(default=0, null=True, verbose_name='showCaste')),
                ('showRemarks', models.IntegerField(default=0, null=True, verbose_name='showRemarks')),
                ('showOverallMarks', models.IntegerField(default=0, null=True, verbose_name='showOverallMarks')),
                ('showResult', models.IntegerField(default=0, null=True, verbose_name='showResult')),
                ('showPercentage', models.IntegerField(default=0, null=True, verbose_name='showPercentage')),
                ('showAttendance', models.IntegerField(default=0, null=True, verbose_name='showAttendance')),
                ('showPromotedToClass', models.IntegerField(default=0, null=True, verbose_name='showPromotedToClass')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'layout',
            },
        ),
        migrations.CreateModel(
            name='LayoutExamColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('name', models.TextField()),
                ('maximumMarksObtainedOne', models.IntegerField(default=0, null=True)),
                ('maximumMarksObtainedTwo', models.IntegerField(default=0, null=True)),
                ('columnType', models.CharField(choices=[('Simple', 'Simple'), ('Oral/Written', 'Oral/Written'), ('Practical/Theory', 'Practical/Theory')], default='Simple', max_length=255, null=True)),
                ('parentExamination', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.Examination', verbose_name='parentExamination')),
                ('parentLayout', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='custom_reportcard.Layout', verbose_name='parentLayout')),
            ],
            options={
                'db_table': 'layout_exam_column',
            },
        ),
        migrations.AlterUniqueTogether(
            name='layoutexamcolumn',
            unique_together=set([('parentLayout', 'parentExamination')]),
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together=set([('name', 'parentSchool', 'parentSession')]),
        ),
    ]
