# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reportcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='reportCardHeading',
            field=models.TextField(default=''),
        ),
    ]
