# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reportcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='reportCardHeading',
            field=models.TextField(default='', null=True, verbose_name='reportCardHeading'),
        ),
    ]
