# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reportcard', '0002_layout_reportcardheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutexamcolumn',
            name='parentLayout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout'),
        ),
    ]
