# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_auto_20191130_2039'),
        ('grade_app', '0001_initial'),
        ('custom_reportcard', '0003_auto_20200310_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.Class', verbose_name='parentClass')),
            ],
            options={
                'db_table': 'class_layout',
            },
        ),
        migrations.CreateModel(
            name='LayoutGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('parentGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.Grade', verbose_name='parentGrade')),
            ],
            options={
                'db_table': 'layout_grade',
            },
        ),
        migrations.CreateModel(
            name='LayoutSubGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('parentLayoutGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.LayoutGrade', verbose_name='parentLayoutGrade')),
                ('parentSubGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.SubGrade', verbose_name='parentSubGrade')),
            ],
            options={
                'db_table': 'layout_sub_grade',
            },
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='showLetterHead',
            new_name='letterHeadImage',
        ),
        migrations.AddField(
            model_name='layout',
            name='showAddress',
            field=models.IntegerField(default=0, null=True, verbose_name='showAddress'),
        ),
        migrations.AddField(
            model_name='layout',
            name='showClassAndSection',
            field=models.IntegerField(default=0, null=True, verbose_name='showClassAndSection'),
        ),
        migrations.AddField(
            model_name='layout',
            name='showDecimal',
            field=models.IntegerField(default=0, null=True, verbose_name='showDecimal'),
        ),
        migrations.AddField(
            model_name='layoutgrade',
            name='parentLayout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout'),
        ),
        migrations.AddField(
            model_name='classlayout',
            name='parentLayout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout'),
        ),
        migrations.AlterUniqueTogether(
            name='layoutsubgrade',
            unique_together=set([('parentLayoutGrade', 'parentSubGrade')]),
        ),
        migrations.AlterUniqueTogether(
            name='layoutgrade',
            unique_together=set([('parentLayout', 'parentGrade')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlayout',
            unique_together=set([('parentLayout', 'parentClass')]),
        ),
    ]
