# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reportcard', '0005_auto_20200311_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentremarks',
            name='remark',
            field=models.TextField(blank=True, default='-', verbose_name='remark'),
        ),
    ]
