# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 10:43
from __future__ import unicode_literals

from django.db import migrations

from examination_app.db_script.change_sbs_test_structure import change_sbs_test_structure

class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0002_auto_20180406_1312'),
    ]

    operations = [
        migrations.RunPython(change_sbs_test_structure),
    ]
