# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from examination_app.db_script.access_examination_app import access_examination_app

class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0033_remove_school_logo'),
        ('subject_app', '0002_auto_20181201_2300'),
        ('examination_app', '0006_examination_testsecond'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsecond',
            name='parentSubject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.SubjectSecond', verbose_name='parentSubject'),
        ),
        migrations.AddField(
            model_name='examination',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AddField(
            model_name='examination',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.AlterUniqueTogether(
            name='testsecond',
            unique_together=set([('parentExamination', 'parentSubject', 'parentClass', 'parentDivision', 'testType')]),
        ),
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together=set([('name', 'parentSchool', 'parentSession')]),
        ),
        migrations.RunPython(access_examination_app),
    ]
