# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0004_auto_20190213_1458'),
        ('student_app', '0020_auto_20190203_2339'),
        ('school_app', '0033_remove_school_logo'),
        ('examination_app', '0008_auto_20181224_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpBoardReportCardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentExaminationAugust', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_august', to='examination_app.Examination', verbose_name='parentExaminationAugust')),
                ('parentExaminationDecember', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_december', to='examination_app.Examination', verbose_name='parentExaminationDecember')),
                ('parentExaminationFebruary', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_february', to='examination_app.Examination', verbose_name='parentExaminationFebruary')),
                ('parentExaminationFinal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_final', to='examination_app.Examination', verbose_name='parentExaminationFinal')),
                ('parentExaminationHalfYearly', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_half_yearly', to='examination_app.Examination', verbose_name='parentExaminationHalfYearly')),
                ('parentExaminationJanuary', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_january', to='examination_app.Examination', verbose_name='parentExaminationJanuary')),
                ('parentExaminationJuly', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_july', to='examination_app.Examination', verbose_name='parentExaminationJuly')),
                ('parentExaminationOctober', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_october', to='examination_app.Examination', verbose_name='parentExaminationOctober')),
                ('parentExaminationProject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_project', to='examination_app.Examination', verbose_name='parentExaminationProject')),
                ('parentExaminationSeptember', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_september', to='examination_app.Examination', verbose_name='parentExaminationSeptember')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'mp_board_report_card_mapping',
            },
        ),
        migrations.CreateModel(
            name='StudentExtraSubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksObtained', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='marksObtained')),
                ('parentExamination', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.Examination', verbose_name='parentExamination')),
                ('parentExtraSubField', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.ExtraSubField', verbose_name='parentExtraSubField')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_extra_sub_field',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentextrasubfield',
            unique_together=set([('parentExamination', 'parentExtraSubField', 'parentStudent')]),
        ),
        migrations.AlterUniqueTogether(
            name='mpboardreportcardmapping',
            unique_together=set([('parentSchool', 'parentSession')]),
        ),
    ]
