# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0009_auto_20190214_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Declared', 'Declared')], default='Created', max_length=20, null=True, verbose_name='examinationStatus'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceAugustEnd',
            field=models.DateField(null=True, verbose_name='attendanceAugustEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceAugustStart',
            field=models.DateField(null=True, verbose_name='attendanceAugustStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceDecemberEnd',
            field=models.DateField(null=True, verbose_name='attendanceDecemberEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceDecemberStart',
            field=models.DateField(null=True, verbose_name='attendanceDecemberStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFebruaryEnd',
            field=models.DateField(null=True, verbose_name='attendanceFebruaryEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFebruaryStart',
            field=models.DateField(null=True, verbose_name='attendanceFebruaryStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFinalEnd',
            field=models.DateField(null=True, verbose_name='attendanceFinalEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFinalHighEnd',
            field=models.DateField(null=True, verbose_name='attendanceFinalHighEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFinalHighStart',
            field=models.DateField(null=True, verbose_name='attendanceFinalHighStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceFinalStart',
            field=models.DateField(null=True, verbose_name='attendanceFinalStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceHalfYearlyEnd',
            field=models.DateField(null=True, verbose_name='attendanceHalfYearlyEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceHalfYearlyHighEnd',
            field=models.DateField(null=True, verbose_name='attendanceHalfYearlyHighEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceHalfYearlyHighStart',
            field=models.DateField(null=True, verbose_name='attendanceHalfYearlyHighStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceHalfYearlyStart',
            field=models.DateField(null=True, verbose_name='attendanceHalfYearlyStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceJanuaryEnd',
            field=models.DateField(null=True, verbose_name='attendanceJanuaryEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceJanuaryStart',
            field=models.DateField(null=True, verbose_name='attendanceJanuaryStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceJulyEnd',
            field=models.DateField(null=True, verbose_name='attendanceJulyEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceJulyStart',
            field=models.DateField(null=True, verbose_name='attendanceJulyStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceOctoberEnd',
            field=models.DateField(null=True, verbose_name='attendanceOctoberEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceOctoberStart',
            field=models.DateField(null=True, verbose_name='attendanceOctoberStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceQuarterlyHighEnd',
            field=models.DateField(null=True, verbose_name='attendanceQuarterlyHighEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceQuarterlyHighStart',
            field=models.DateField(null=True, verbose_name='attendanceQuarterlyHighStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceSeptemberEnd',
            field=models.DateField(null=True, verbose_name='attendanceSeptemberEnd'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='attendanceSeptemberStart',
            field=models.DateField(null=True, verbose_name='attendanceSeptemberStart'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='autoAttendance',
            field=models.BooleanField(default=True, verbose_name='autoAttendance'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationFinalHigh',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_final_high', to='examination_app.Examination', verbose_name='parentExaminationFinalHigh'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationHalfYearlyHigh',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_half_yearly_high', to='examination_app.Examination', verbose_name='parentExaminationHalfYearlyHigh'),
        ),
        migrations.AddField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationQuarterlyHigh',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_quarterly_high', to='examination_app.Examination', verbose_name='parentExaminationQuarterlyHigh'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationAugust',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_august', to='examination_app.Examination', verbose_name='parentExaminationAugust'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationDecember',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_december', to='examination_app.Examination', verbose_name='parentExaminationDecember'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationFebruary',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_february', to='examination_app.Examination', verbose_name='parentExaminationFebruary'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationFinal',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_final', to='examination_app.Examination', verbose_name='parentExaminationFinal'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationHalfYearly',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_half_yearly', to='examination_app.Examination', verbose_name='parentExaminationHalfYearly'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationJanuary',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_january', to='examination_app.Examination', verbose_name='parentExaminationJanuary'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationJuly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_july', to='examination_app.Examination', verbose_name='parentExaminationJuly'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationOctober',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_october', to='examination_app.Examination', verbose_name='parentExaminationOctober'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationProject',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_project', to='examination_app.Examination', verbose_name='parentExaminationProject'),
        ),
        migrations.AlterField(
            model_name='mpboardreportcardmapping',
            name='parentExaminationSeptember',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpboardreportcardmapping_september', to='examination_app.Examination', verbose_name='parentExaminationSeptember'),
        ),
    ]
