# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0011_auto_20190316_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccemarks',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
        migrations.AlterField(
            model_name='studentextrasubfield',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
        migrations.AlterField(
            model_name='studenttestresult',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
    ]
