# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-06 23:43
from __future__ import unicode_literals

from django.db import migrations
from examination_app.db_script.exam_status_not_null import exam_status_not_null


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0012_auto_20190901_1142'),
    ]

    operations = [
         migrations.RunPython(exam_status_not_null),
    ]
