# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-23 16:50
from __future__ import unicode_literals

from django.db import migrations

from examination_app.db_script.scale_marks_from_10_to_2 import scale_marks_from_10_to_2

class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0012_auto_20190901_1142'),
    ]

    operations = [
    	migrations.RunPython(scale_marks_from_10_to_2),
    ]
