# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-21 15:29
from __future__ import unicode_literals

from django.db import migrations

from examination_app.db_script.divide_extra_sub_field_marks_by_5 import divide_extra_sub_field_marks_by_5


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0012_auto_20190901_1142'),
    ]

    operations = [
        migrations.RunPython(divide_extra_sub_field_marks_by_5),
    ]
