# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models
from examination_app.db_script.exam_status_not_null import exam_status_not_null


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0013_auto_20200125_1907'),
    ]

    operations = [
        migrations.RunPython(exam_status_not_null),
        migrations.AlterField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Declared', 'Declared')], default='Created', max_length=20, verbose_name='examinationStatus'),
        ),
    ]
