export const EMPLOYEE_LIST = [
    {
        aadharNumber: null,
        address: null,
        bankAccountNumber: null,
        bankIfscCode: null,
        bankName: null,
        currentPost: null,
        dateOfBirth: null,
        dateOfJoining: null,
        dateOfLeaving: null,
        employeeNumber: null,
        epfAccountNumber: null,
        fatherName: "Dummy Father",
        gender: null,
        id: 1,
        mobileNumber: 4545125456,
        monthlySalary: null,
        motherName: "Dummy Mother",
        name: "Dummy Employee",
        panNumber: null,
        parentSchool: 2,
        passportNumber: null,
        pranNumber: null,
        profileImage: null,
        qualification: null,
        remark: null,
        spouseName: null
    },
    {
        aadharNumber: null,
        address: null,
        bankAccountNumber: null,
        bankIfscCode: null,
        bankName: null,
        currentPost: null,
        dateOfBirth: null,
        dateOfJoining: null,
        dateOfLeaving: null,
        employeeNumber: null,
        epfAccountNumber: null,
        fatherName: "Dummy Father",
        gender: null,
        id: 2,
        mobileNumber: 5845125456,
        monthlySalary: null,
        motherName: "Dummy Mother",
        name: "Dummy Employee 2",
        panNumber: null,
        parentSchool: 2,
        passportNumber: null,
        pranNumber: null,
        profileImage: null,
        qualification: null,
        remark: null,
        spouseName: null
    },
];
