# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorSource', models.CharField(choices=[('REST_API_SOURCE', 'rest_api'), ('JAVASCRIPT_SOURCE_STATUS', 'js_runtime')], max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prompt', models.CharField(max_length=200)),
                ('flatal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'error',
            },
        ),
    ]
