# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorSource', models.CharField(choices=[('REST_API_SOURCE', 'rest_api'), ('JAVASCRIPT_SOURCE', 'js_runtime')], max_length=50, verbose_name='Error Source')),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('prompt', models.CharField(max_length=250)),
                ('fatal', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('frontendUrl', models.TextField(blank=True, null=True)),
                ('postDataBody', models.TextField(blank=True, null=True)),
                ('issueStatus', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Github', 'Github'), ('Resolved', 'Resolved'), ('Discarded', 'Discarded')], default='Pending', max_length=50, verbose_name='issueStatus')),
                ('githubId', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'error',
            },
        ),
    ]
