# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='url',
            field=models.CharField(max_length=1500),
        ),
    ]
