# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('errors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='error',
            name='errorSource',
            field=models.CharField(choices=[('REST_API_SOURCE', 'rest_api'), ('JAVASCRIPT_SOURCE', 'js_runtime')], max_length=50, verbose_name='Error Source'),
        ),
        migrations.AlterField(
            model_name='error',
            name='prompt',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='error',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
