# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors_app', '0004_auto_20210422_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='githubId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='issueStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Github', 'Github'), ('Resolved', 'Resolved'), ('Discarded', 'Discarded')], default='Pending', max_length=50, verbose_name='issueStatus'),
        ),
    ]
