# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-09 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0037_auto_20190712_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('sentDateTime', models.DateTimeField(auto_now_add=True, verbose_name='sentDateTime')),
                ('parentSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='parentUser')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
