# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0001_initial'),
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parentMessageType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='information_app.MessageType'),
        ),
    ]
