# Generated by Django 3.2.5 on 2021-08-26 06:48

from django.db import migrations
from fees_third_app.db_script.tc_fee_patch1 import set_tc_school_fee_rule_to_zero


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_tc_school_fee_rule_to_zero)
    ]
