# Generated by Django 3.2.5 on 2021-08-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('KORANGLE', 'KORANGLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='receiptNumber'),
        ),
        migrations.CreateModel(
            name='OnlineFeePaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeDetailJSON', models.TextField()),
                ('parentFeeReceipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees_third_app.feereceipt')),
            ],
        ),
    ]
