# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0002_auto_20210718_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='chequeNumber',
            field=models.BigIntegerField(null=True, verbose_name='chequeNumber'),
        ),
    ]
