# Generated by Django 3.2.5 on 2021-08-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('school_app', '0001_initial'),
        ('fees_third_app', '0002_auto_20210822_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.order'),
        ),
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.school'),
        ),
    ]
