# Generated by Django 3.2.5 on 2021-10-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20211014_0751'),
        ('employee_app', '0001_initial'),
        ('student_app', '0001_initial'),
        ('school_app', '0002_remove_school_smsid'),
        ('fees_third_app', '0002_auto_20210826_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='discountList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='discountList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountList', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='cancelledBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelledFeeReceiptList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='generationDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('KORANGLE', 'KORANGLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='accounts_app.transaction'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentDiscount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='fees_third_app.discount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentFeeType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='fees_third_app.feetype'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentStudentFee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subDiscountList', to='fees_third_app.studentfee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='parentFeeReceipt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subFeeReceiptList', to='fees_third_app.feereceipt'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='parentFeeType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subFeeReceiptList', to='fees_third_app.feetype'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subFeeReceiptList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='parentStudentFee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subFeeReceiptList', to='fees_third_app.studentfee'),
        ),
        migrations.CreateModel(
            name='FeeReceiptOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeReceiptData', models.JSONField()),
                ('parentFeeReceipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='fees_third_app.feereceipt')),
            ],
        ),
    ]
