# Generated by Django 3.2.5 on 2021-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0002_auto_20210826_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=1, verbose_name='receiptNumber'),
        ),
    ]
