# Generated by Django 3.2.5 on 2021-10-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('fees_third_app', '0003_auto_20211015_1100'),
        ('student_app', '0001_initial'),
        ('school_app', '0002_remove_school_smsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='payment_app.order'),
        ),
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='school_app.school'),
        ),
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptOrderList', to='student_app.student'),
        ),
    ]
