# Generated by Django 3.2.5 on 2021-10-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0003_auto_20211012_1714'),
        ('school_app', '0002_remove_school_smsid'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.order'),
        ),
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.school'),
        ),
    ]
