# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0003_auto_20190726_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
    ]
