# Generated by Django 3.2.5 on 2021-10-14 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
        ('payment_app', '0001_initial'),
        ('school_app', '0002_remove_school_smsid'),
        ('accounts_app', '0003_auto_20211014_0751'),
        ('student_app', '0001_initial'),
        ('fees_third_app', '0004_auto_20211012_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feereceiptorder',
            name='feeDetailJSON',
        ),
        migrations.AddField(
            model_name='feereceiptorder',
            name='feeDetail',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='discountList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='discountList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountList', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='cancelledBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelledFeeReceiptList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptList', to='accounts_app.transaction'),
        ),
        migrations.AlterField(
            model_name='feereceiptorder',
            name='parentFeeReceipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='fees_third_app.feereceipt'),
        ),
        migrations.AlterField(
            model_name='feereceiptorder',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='payment_app.order'),
        ),
        migrations.AlterField(
            model_name='feereceiptorder',
            name='parentSchool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='feeReceiptOrderList', to='school_app.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentDiscount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='fees_third_app.discount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentFeeType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='fees_third_app.feetype'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subDiscountList', to='school_app.session'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='parentStudentFee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subDiscountList', to='fees_third_app.studentfee'),
        ),
    ]
