# Generated by Django 3.2.5 on 2021-12-05 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0004_auto_20211015_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesettings',
            name='percentageTransactionChargeOnSchool',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
