# Generated by Django 3.2.5 on 2022-07-09 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
        ('fees_third_app', '0004_auto_20211015_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeSettings',
            new_name='FeeSchoolSessionSettings',
        ),
        migrations.CreateModel(
            name='FeeSchoolSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printSingleReceipt', models.BooleanField(default=False)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school', unique=True)),
            ],
        ),
    ]
