# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('employee_app', '0012_auto_20200409_1653'),
        ('fees_third_app', '0004_auto_20200406_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeConnectId', models.TextField(default=0, verbose_name='stripeConnectId')),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'online_payment_account',
            },
        ),
    ]
