# Generated by Django 3.2.5 on 2021-10-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
        ('fees_third_app', '0005_auto_20211014_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feereceiptorder',
            old_name='feeDetail',
            new_name='feeReceiptData',
        ),
        migrations.AddField(
            model_name='feereceiptorder',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeReceiptOrderList', to='student_app.student'),
        ),
    ]
