# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-02 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20210402_0839'),
        ('school_app', '0042_schoolsummary'),
        ('fees_third_app', '0005_auto_20201231_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaymentAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeOfPayment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('parentAccountSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.AccountSession')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
                ('parentSession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAccountSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.AccountSession')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
                ('parentSession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session')),
            ],
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='feesettings',
            unique_together=set([('parentSchool', 'parentSession')]),
        ),
    ]
