# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0027_auto_20200816_1155'),
        ('fees_third_app', '0005_onlinepaymentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFeeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='amount')),
                ('status', models.TextField(default=0, verbose_name='status')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'parent_fee_transaction',
            },
        ),
    ]
