# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20210321_2132'),
        ('school_app', '0042_schoolsummary'),
        ('fees_third_app', '0005_auto_20201231_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaymentAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeOfPayment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('parentAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Accounts')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.Accounts')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.Transaction'),
        ),
    ]
