# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('student_app', '0033_auto_20210519_0449'),
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashfreeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeDetailJSON', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.CharField(max_length=20, unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refund Pending', 'Refund Pending'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Forwarded to School', 'Forwarded to School')], default='Pending', max_length=30)),
                ('referenceId', models.CharField(default=None, max_length=30, null=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('parentSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.School')),
            ],
        ),
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('KORANGLE', 'KORANGLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='receiptNumber'),
        ),
        migrations.AddField(
            model_name='cashfreetransaction',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees_third_app.Order'),
        ),
        migrations.AddField(
            model_name='cashfreetransaction',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.Student'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentCashfreeTransaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees_third_app.CashfreeTransaction'),
        ),
    ]
