# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('school_app', '0043_auto_20210414_1604'),
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineFeePaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeDetailJSON', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('KORANGLE', 'KORANGLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='receiptNumber'),
        ),
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentFeeReceipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees_third_app.FeeReceipt'),
        ),
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.Order', unique=True),
        ),
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.School'),
        ),
    ]
