# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-15 10:47
from __future__ import unicode_literals

from django.db import migrations
from fees_third_app.db_script.tc_fee_patch1 import set_tc_school_fee_rule_to_zero

class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.RunPython(set_tc_school_fee_rule_to_zero)
    ]
