# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0033_auto_20210519_0449'),
        ('school_app', '0043_auto_20210414_1604'),
        ('employee_app', '0013_employeepermission_configjson'),
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.TextField(default=-1, verbose_name='vendorId')),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'online_payment_account',
            },
        ),
        migrations.CreateModel(
            name='ParentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='amount')),
                ('status', models.TextField(default=0, verbose_name='status')),
                ('orderId', models.TextField(default=-1, verbose_name='orderId')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'parent_transaction',
            },
        ),
    ]
