# Generated by Django 3.2.5 on 2023-04-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20221104_1530'),
        ('fees_third_app', '0006_viewDefaulterPermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFilterFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedFilterValues', models.TextField(blank=True, null=True)),
                ('parentSchoolFeeRule', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fees_third_app.schoolfeerule', verbose_name='parentSchoolFeeRule')),
                ('parentStudentParameter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.studentparameter', verbose_name='parentStudentParameter')),
            ],
            options={
                'db_table': 'custom_filter_fee',
            },
        ),
    ]
