# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineFeePaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeDetailJSON', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='modeOfPayment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('KORANGLE', 'KORANGLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='receiptNumber'),
        ),
    ]
