# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0007_auto_20210701_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinefeepaymenttransaction',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.Order'),
        ),
    ]
