# Generated by Django 3.2.5 on 2023-08-04 10:21

from django.db import migrations, models
import django.db.models.deletion

from fees_third_app.db_script.add_default_fee_receipt_book import add_default_fee_receipt_book


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('fees_third_app', '0007_customfilterfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceiptBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('receiptNumberPrefix', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feeReceiptBookList', to='school_app.school')),
            ],
            options={
                'db_table': 'fee_receipt_book',
                'unique_together': {('parentSchool', 'name'), ('parentSchool', 'receiptNumberPrefix')},
            },
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentFeeReceiptBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeReceiptList', to='fees_third_app.feereceiptbook'),
        ),
        migrations.AlterUniqueTogether(
            name='feereceipt',
            unique_together={('receiptNumber', 'parentFeeReceiptBook')},
        ),
        migrations.RunPython(add_default_fee_receipt_book),
    ]
