# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('fees_third_app', '0007_auto_20210630_1952'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.Order', unique=True),
        ),
        migrations.AddField(
            model_name='onlinefeepaymenttransaction',
            name='parentSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.School'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentOnlinePaymentTransaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees_third_app.OnlineFeePaymentTransaction'),
        ),
    ]
