# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-11 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_employeepermission_configjson'),
        ('fees_third_app', '0007_onlinepaymentaccount_parenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentaccount',
            name='parentEmployee',
        ),
        migrations.AddField(
            model_name='onlinepaymentaccount',
            name='parentEmployeeAddedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='onlinepaymentaccount',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', unique=True),
        ),
        migrations.AlterField(
            model_name='onlinepaymentaccount',
            name='vendorId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterModelTable(
            name='onlinepaymentaccount',
            table=None,
        ),
    ]
