# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-29 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0007_auto_20210626_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referenceId',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
