# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-11 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0008_auto_20210611_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentaccount',
            name='parentEmployeeAddedBy',
        ),
    ]
