# Generated by Django 3.2.5 on 2023-12-22 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0008_auto_20230814_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfeerule',
            name='aprilAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='aprilLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='aprilMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='augustAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='augustLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='augustMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='decemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='decemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='decemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='februaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='februaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='februaryMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='januaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='januaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='januaryMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='julyAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='julyLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='julyMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='juneAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='juneLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='juneMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='marchAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='marchLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='marchMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='mayAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='mayLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='mayMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='novemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='novemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='novemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='octoberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='octoberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='octoberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='septemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberAmount'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='septemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberLateFee'),
        ),
        migrations.AlterField(
            model_name='schoolfeerule',
            name='septemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='aprilAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='aprilLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='aprilMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='augustAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='augustLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='augustMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='decemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='decemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='decemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='februaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='februaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='februaryMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='januaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='januaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='januaryMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='julyAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='julyLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='julyMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='juneAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='juneLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='juneMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='marchAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='marchLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='marchMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='mayAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='mayLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='mayMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='novemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='novemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='novemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='octoberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='octoberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='octoberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='septemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberAmount'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='septemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberLateFee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='septemberMaximumLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberMaximumLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='aprilAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='aprilLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='augustAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='augustLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='decemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='decemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='februaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='februaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='januaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='januaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='julyAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='julyLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='juneAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='juneLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='marchAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='marchLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='mayAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='mayLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='novemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='novemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='octoberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='octoberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberLateFee'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='septemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberAmount'),
        ),
        migrations.AlterField(
            model_name='subdiscount',
            name='septemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='aprilAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='aprilLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aprilLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='augustAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='augustLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='augustLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='decemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='decemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='decemberLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='februaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='februaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='februaryLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='januaryAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='januaryLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='januaryLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='julyAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='julyLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='julyLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='juneAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='juneLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='juneLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='marchAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='marchLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marchLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='mayAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='mayLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mayLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='novemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='novemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='novemberLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='octoberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='octoberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='octoberLateFee'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='septemberAmount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberAmount'),
        ),
        migrations.AlterField(
            model_name='subfeereceipt',
            name='septemberLateFee',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='septemberLateFee'),
        ),
    ]
