# Generated by Django 3.2.5 on 2023-10-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('fees_third_app', '0009_auto_20231223_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesViewAllReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studentListFilter', models.JSONField(null=True)),
                ('columnListFilter', models.JSONField(null=True)),
                ('searchText', models.TextField(blank=True, null=True)),
                ('searchParameter', models.TextField(null=True)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feesViewAllTableList', to='school_app.school')),
            ],
            options={
                'db_table': 'fees_view_all_report',
            },
        ),
    ]
