# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0033_auto_20210519_0449'),
        ('fees_third_app', '0009_remove_onlinepaymentaccount_parentemployeeaddedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Forwarded to School', 'Forwarded to School')], max_length=30)),
                ('orderId', models.CharField(max_length=20)),
                ('feeDetailJSON', models.TextField()),
                ('parentStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='parenttransaction',
            name='parentStudent',
        ),
        migrations.DeleteModel(
            name='ParentTransaction',
        ),
    ]
