# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0010_auto_20210618_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Forwarded to School', 'Forwarded to School')], default='Pending', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='parentOrder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fees_third_app.Order'),
            preserve_default=False,
        ),
    ]
