# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-19 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0011_auto_20210618_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='CashfreeTransaction',
        ),
    ]
