# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-21 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0012_auto_20210620_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentaccount',
            name='vendorId',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
