# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0013_auto_20210621_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='receiptNumber'),
        ),
    ]
