# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-23 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0014_auto_20210623_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesettings',
            old_name='accountingSettings',
            new_name='accountingSettingsJSON',
        ),
    ]
