# Generated by Django 3.2.5 on 2022-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='marksUpdationStatus',
            field=models.CharField(choices=[('Locked', 'Locked'), ('Unlocked', 'Unlocked')], default='Unlocked', max_length=20, verbose_name='marksUpdationStatus'),
        ),
    ]
