# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-06 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0017_auto_20210305_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='testType',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Written', 'Written'), ('Theory', 'Theory'), ('Practical', 'Practical')], default=None, max_length=11, null=True, verbose_name='testType'),
        ),
    ]
