# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 09:54
from __future__ import unicode_literals

from django.db import migrations

from salary_app.db_script.add_view_record_task import add_view_record_task


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_view_record_task),
    ]
