# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-02 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_schoolsummary'),
        ('accounts_app', '0003_auto_20210321_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountsession',
            unique_together=set([('parentAccount', 'parentSession')]),
        ),
    ]
