# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:21
from __future__ import unicode_literals

import class_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orderNumber', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatureImage', models.ImageField(blank=True, null=True, upload_to=class_app.models.upload_signature_image_to, verbose_name='SignatureImage')),
                ('parentClass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
            ],
            options={
                'db_table': 'class_teacher_signature',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orderNumber', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.AddField(
            model_name='classteachersignature',
            name='parentDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision'),
        ),
        migrations.AddField(
            model_name='classteachersignature',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AlterUniqueTogether(
            name='classteachersignature',
            unique_together=set([('parentSchool', 'parentClass', 'parentDivision')]),
        ),
    ]
