# Generated by Django 3.2.5 on 2022-12-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['orderNumber']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['orderNumber']},
        ),
    ]
