# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import my_design.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=my_design.models.upload_image_assets_to)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to=my_design.models.upload_thumbnail_to)),
                ('publiclyShared', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentLayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_layout', to='my_design.Layout')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_school', to='school_app.School')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='layoutsharing',
            unique_together=set([('parentSchool', 'parentLayout')]),
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together=set([('type', 'parentSchool', 'name')]),
        ),
    ]
