# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='type',
            field=models.CharField(choices=[('REPORT CARD', 'REPORT CARD'), ('TC', 'TC')], max_length=50),
        ),
    ]
