# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-31 11:49
from __future__ import unicode_literals

from django.db import migrations
from my_design.db_script.migrate_layouts import migrate_rc_layout_data, migrate_tc_layout_data


class Migration(migrations.Migration):

    dependencies = [
        ('my_design', '0002_auto_20210730_1553'),
    ]

    operations = [
        migrations.RunPython(migrate_rc_layout_data),
        migrations.RunPython(migrate_tc_layout_data),
    ]
