# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-01 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_design', '0003_auto_20210731_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='content',
            new_name='contentJSON',
        ),
    ]
