# Generated by Django 3.2.5 on 2021-12-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_app', '0001_initial'),
        ('team_app', '0005_renaming_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityDescription', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employee')),
                ('parentTask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_app.task')),
            ],
            options={
                'db_table': 'activity_record',
            },
        ),
    ]
