# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from class_app.db_script.populateDatabaseFirst import populateDatabaseFirst

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0015_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orderNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orderNumber', models.IntegerField(default=0)),
                ('parentClassSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.ClassSession')),
            ],
        ),
    ]
