# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 19:21
from __future__ import unicode_literals

from django.db import migrations

from class_app.db_script.populateDatabaseFirst import populateDatabaseFirst

class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
        ('school_app', '0016_student_friendsection'),
    ]

    operations = [
        migrations.RunPython(populateDatabaseFirst),
    ]
