# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20180302_0051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='classsession',
            table='class_session',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
