# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-25 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_division'),
        ('class_app', '0005_auto_20181125_1155'),
    ]

    operations = [
    ]
