# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-30 15:09
from __future__ import unicode_literals

import class_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0038_auto_20191130_2039'),
        ('class_app', '0006_merge_20181125_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatureImage', models.ImageField(blank=True, null=True, upload_to=class_app.models.upload_signature_image_to, verbose_name='SignatureImage')),
                ('parentClass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'class_teacher_signature',
            },
        ),
        migrations.AlterUniqueTogether(
            name='classteachersignature',
            unique_together=set([('parentSchool', 'parentClass', 'parentDivision')]),
        ),
    ]
