# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-17 07:57
from __future__ import unicode_literals

import class_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_auto_20191116_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteachersignature',
            name='signatureImage',
            field=models.ImageField(blank=True, null=True, upload_to=class_app.models.upload_signature_image_to, verbose_name='SignatureImage'),
        ),
    ]
