# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0027_auto_20200816_1155'),
        ('subject_app', '0006_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkName', models.TextField()),
                ('startDate', models.DateField(default='2011-01-01', verbose_name='startDate')),
                ('endDate', models.DateField(default='2011-01-01', verbose_name='endDate')),
                ('homeworkText', models.TextField(null=True)),
                ('parentClassSubject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.ClassSubject', verbose_name='parentClassSubject')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerImage', models.ImageField(null=True, upload_to='')),
                ('parentHomework', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='homework_app.Homework', verbose_name='parentHomework')),
            ],
            options={
                'db_table': 'homework_answer',
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionImage', models.ImageField(null=True, upload_to='')),
                ('parentHomework', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='homework_app.Homework', verbose_name='parentHomework')),
            ],
            options={
                'db_table': 'homework_question',
            },
        ),
        migrations.CreateModel(
            name='HomeworkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkStatus', models.TextField(choices=[('GIVEN', 'GIVEN'), ('SUBMITTED', 'SUBMITTED'), ('CHECKED', 'CHECKED'), ('ASKED FOR RESUBMISSION', 'ASKED FOR RESUBMISSION')], default='GIVEN')),
                ('submissionDate', models.DateField(default='2011-01-01', verbose_name='submissionDate')),
                ('answerText', models.TextField(null=True)),
                ('parentHomework', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='homework_app.Homework', verbose_name='parentHomework')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'homework_status',
            },
        ),
        migrations.AlterUniqueTogether(
            name='homeworkstatus',
            unique_together=set([('parentStudent', 'parentHomework')]),
        ),
    ]
