# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0027_auto_20200816_1155'),
        ('homework_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkanswer',
            old_name='parentHomework',
            new_name='parentHomeworkQuestion',
        ),
        migrations.RenameField(
            model_name='homeworkanswerimage',
            old_name='parentHomework',
            new_name='parentHomeworkQuestion',
        ),
        migrations.RenameField(
            model_name='homeworkquestionimage',
            old_name='parentHomework',
            new_name='parentHomeworkQuestion',
        ),
        migrations.AlterUniqueTogether(
            name='homeworkanswer',
            unique_together=set([('parentStudent', 'parentHomeworkQuestion')]),
        ),
    ]
