# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import homework_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='answerImage',
            field=models.ImageField(blank=True, null=True, upload_to=homework_app.models.upload_answer_to, verbose_name='answer_image'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to=homework_app.models.upload_question_to, verbose_name='question_image'),
        ),
    ]
