# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0002_auto_20210111_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='parentHomeworkQuestion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.HomeworkQuestion', verbose_name='parentHomeworkQuestion'),
        ),
        migrations.AlterField(
            model_name='homeworkanswerimage',
            name='parentHomeworkQuestion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.HomeworkQuestion', verbose_name='parentHomeworkQuestion'),
        ),
        migrations.AlterField(
            model_name='homeworkquestionimage',
            name='parentHomeworkQuestion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.HomeworkQuestion', verbose_name='parentHomeworkQuestion'),
        ),
    ]
