# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-10 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0002_auto_20201209_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='homeworkstatus',
            name='submissionDate',
        ),
        migrations.AddField(
            model_name='homework',
            name='endDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='endDateTime'),
        ),
        migrations.AddField(
            model_name='homework',
            name='startDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='startDateTime'),
        ),
        migrations.AddField(
            model_name='homeworkstatus',
            name='submissionDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='submissionDateTime'),
        ),
    ]
