# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-10 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0003_auto_20201210_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='startDateTime',
        ),
        migrations.RemoveField(
            model_name='homeworkstatus',
            name='submissionDateTime',
        ),
        migrations.AddField(
            model_name='homework',
            name='endDate',
            field=models.DateField(default='2011-01-01', verbose_name='endDate'),
        ),
        migrations.AddField(
            model_name='homework',
            name='endTime',
            field=models.TimeField(default='23:59:59', null=True, verbose_name='endTime'),
        ),
        migrations.AddField(
            model_name='homework',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='startDate'),
        ),
        migrations.AddField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(default='18:30:33', verbose_name='startTime'),
        ),
        migrations.AddField(
            model_name='homeworkstatus',
            name='submissionDate',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='submissionDate'),
        ),
        migrations.AddField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='18:30:33', null=True),
        ),
    ]
