# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0004_auto_20210111_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkanswerimage',
            name='parentHomeworkQuestion',
        ),
        migrations.RemoveField(
            model_name='homeworkanswerimage',
            name='parentStudent',
        ),
        migrations.AlterField(
            model_name='homeworkanswerimage',
            name='parentHomeworkAnswer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.HomeworkAnswer', verbose_name='parentHomeworkAnswer'),
        ),
    ]
