# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0004_auto_20201210_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='parentClassSubject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subject_app.ClassSubject', verbose_name='parentClassSubject'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(default='15:52:57', verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='parentHomework',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.Homework', verbose_name='parentHomework'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='parentHomework',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.Homework', verbose_name='parentHomework'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='parentHomework',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_app.Homework', verbose_name='parentHomework'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='15:52:57', null=True),
        ),
    ]
