# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-19 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0005_auto_20210111_1524'),
        ('sms_app', '0006_auto_20210420_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksettings',
            name='parentSchool',
        ),
        migrations.DeleteModel(
            name='HomeworkSettings',
        ),
    ]
