# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0005_auto_20201211_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='endDate',
            field=models.DateField(null=True, verbose_name='endDate'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(default='15:31:21', verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='15:31:21', null=True),
        ),
    ]
