# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0005_auto_20210111_1524'),
        ('sms_app', '0006_smsevent_smstemplate'),
        ('information_app', '0002_sentupdatetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksettings',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='homeworksettings',
            name='sendCheckUpdate',
        ),
        migrations.RemoveField(
            model_name='homeworksettings',
            name='sendCreateUpdate',
        ),
        migrations.RemoveField(
            model_name='homeworksettings',
            name='sendDeleteUpdate',
        ),
        migrations.RemoveField(
            model_name='homeworksettings',
            name='sendEditUpdate',
        ),
        migrations.RemoveField(
            model_name='homeworksettings',
            name='sendResubmissionUpdate',
        ),
        migrations.AddField(
            model_name='homeworksettings',
            name='parentEvent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSEvent',
                                    verbose_name='parentEvent'),
        ),
        migrations.AddField(
            model_name='homeworksettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSTemplate',
                                    verbose_name='parentSMSTemplate'),
        ),
        migrations.AlterField(
            model_name='homeworksettings',
            name='sentUpdateType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    to='information_app.SentUpdateType'),
        ),
    ]
