# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0009_auto_20201212_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkanswer',
            name='orderNumber',
            field=models.IntegerField(default=0, verbose_name='orderNumber'),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='orderNumber',
            field=models.IntegerField(default=0, verbose_name='orderNumber'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(default='01:31:22', verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='01:31:22', null=True),
        ),
    ]
