# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0011_auto_20201215_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(default='17:50:13', verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='17:50:13', null=True),
        ),
    ]
