# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0012_auto_20201215_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='startDate',
            field=models.DateField(verbose_name='startDate'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='startTime',
            field=models.TimeField(verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionTime',
            field=models.TimeField(default='17:54:05', null=True),
        ),
    ]
