# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0014_auto_20201215_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstatus',
            name='submissionDate',
            field=models.DateField(null=True, verbose_name='submissionDate'),
        ),
    ]
