# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0039_auto_20200104_2202'),
        ('homework_app', '0015_auto_20201215_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentUpdateType', models.CharField(choices=[('SMS', 'SMS'), ('NOTIFICATION', 'NOTIFICATION'), ('NOTIF./SMS', 'NOTIF./SMS'), ('NULL', 'NULL')], default='NOTIFICATION', max_length=20, verbose_name='sentUpdateType')),
                ('sendCreateUpdate', models.BooleanField(default=True, verbose_name='sendCreateUpdate')),
                ('sendEditUpdate', models.BooleanField(default=True, verbose_name='sendEditUpdate')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'homework_settings',
            },
        ),
    ]
