# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0016_homeworksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksettings',
            name='sendDeleteUpdate',
            field=models.BooleanField(default=True, verbose_name='sendDeleteUpdate'),
        ),
    ]
