# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0027_auto_20200816_1155'),
        ('homework_app', '0017_homeworksettings_senddeleteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkanswer',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
    ]
