# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0018_homeworkanswer_parentstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkstatus',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
    ]
