# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0019_homeworkstatus_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksettings',
            name='sendCheckUpdate',
            field=models.BooleanField(default=True, verbose_name='sendCheckUpdate'),
        ),
        migrations.AddField(
            model_name='homeworksettings',
            name='sendResubmissionUpdate',
            field=models.BooleanField(default=True, verbose_name='sendResubmissionUpdate'),
        ),
    ]
