# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-11 09:53
from __future__ import unicode_literals

from django.db import migrations

from homework_app.db_script.change_homework_answer_model import change_homework_answer_image_model

class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0003_auto_20210111_1521'),
    ]

    operations = [
        migrations.RunPython(change_homework_answer_image_model),
    ]
