# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parentClassId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='message_app.Class')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='parentSubjectId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='message_app.Subject'),
        ),
    ]
