# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_auto_20171025_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parentSubjectId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='message_app.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parentClassId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='message_app.Class'),
        ),
        migrations.AddField(
            model_name='question',
            name='parentChapterId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='message_app.Chapter'),
        ),
    ]
