# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0007_auto_20171121_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
