# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0008_auto_20171121_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='showCode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='showHeading',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='showQuestionHeading',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='showRollNumber',
            field=models.BooleanField(default=False),
        ),
    ]
