# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0009_auto_20171121_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperelement',
            name='elementType',
            field=models.CharField(choices=[('question', 'Question'), ('or', 'Or'), ('section', 'Section'), ('subquestion', 'SubQuestion')], default='question', max_length=20),
        ),
    ]
