# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0010_auto_20171122_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperelement',
            name='elementDbId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
