# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0011_paperelement_elementdbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paperName',
            new_name='name',
        ),
    ]
