# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0012_auto_20171122_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
    ]
