# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0013_remove_paper_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='showHeading',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='showQuestionHeading',
        ),
    ]
