# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0015_auto_20171122_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='parentUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
