# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0018_auto_20171122_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperelement',
            name='elementContent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paperelement',
            name='elementMarks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paperelement',
            name='elementNumber',
            field=models.IntegerField(default=0),
        ),
    ]
