# Generated by Django 3.2.5 on 2023-03-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveTypeName', models.TextField(default='invalid_type', verbose_name='leave_name')),
                ('leaveType', models.IntegerField(default=0)),
                ('color', models.TextField(default='#ffffff', verbose_name='color')),
                ('assignedLeavesMonthWise', models.TextField(default='{}', verbose_name='Leaves Vs Month')),
                ('salaryComponents', models.TextField(default='{}', verbose_name='Leaves Vs Month')),
                ('divisionFactor', models.IntegerField(default=1)),
                ('divisionFactorType', models.IntegerField(default=0)),
                ('parentSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.school', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'employee_leave_type',
                'unique_together': {('leaveTypeName', 'parentSchool')},
            },
        ),
    ]
