# Generated by Django 3.2.5 on 2023-03-08 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetypes',
            old_name='parentSchool',
            new_name='parent_school',
        ),
        migrations.RemoveField(
            model_name='leavetypes',
            name='parentUser',
        ),
        migrations.AddField(
            model_name='leavetypes',
            name='assigned_leaves_monthWise',
            field=models.TextField(default='{}', verbose_name='Leaves Vs Month'),
        ),
        migrations.AddField(
            model_name='leavetypes',
            name='color',
            field=models.TextField(default='#ffffff', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='leavetypes',
            name='salary_components',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[0, 0, 0], size=3),
        ),
    ]
