# Generated by Django 3.2.5 on 2023-03-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('leaves_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeLeaveTypes',
            new_name='SchoolLeaveType',
        ),
        migrations.AlterModelTable(
            name='schoolleavetype',
            table='school_leave_type',
        ),
    ]
