# Generated by Django 3.2.5 on 2023-03-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('leaves_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolleavetype',
            name='leaveType',
            field=models.TextField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolleavetype',
            unique_together={('leaveTypeName', 'parentSchool'), ('color', 'parentSchool')},
        ),
        migrations.CreateModel(
            name='SchoolLeaveTypeMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10, verbose_name='month')),
                ('value', models.IntegerField(default=0)),
                ('remainingLeavesAction', models.CharField(choices=[('CarryForward', 'CarryForward'), ('Encashment', 'Encashment'), ('Lapse', 'Lapse')], default='Lapse', max_length=20)),
                ('parentSchoolLeaveType', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leaves_app.schoolleavetype')),
            ],
            options={
                'db_table': 'school_leave_type_month',
                'unique_together': {('parentSchoolLeaveType', 'month')},
            },
        ),
    ]
