# Generated by Django 3.2.5 on 2023-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves_app', '0002_auto_20230308_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypes',
            name='division_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leavetypes',
            name='division_factor_type',
            field=models.IntegerField(default=0),
        ),
    ]
