# Generated by Django 3.2.5 on 2023-04-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employee_isnonsalariedemployee'),
        ('leaves_app', '0003_schoolleaveplan_schoolleaveplantoschoolleavetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLeavePlanToEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
                ('parentSchoolLeavePlan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leaves_app.schoolleaveplan')),
            ],
            options={
                'db_table': 'school_leave_plan_employee',
                'unique_together': {('parentSchoolLeavePlan', 'parentEmployee')},
            },
        ),
    ]
