# Generated by Django 3.2.5 on 2023-07-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employee_isnonsalariedemployee'),
        ('leaves_app', '0004_schoolleaveplantoemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolleaveplantoemployee',
            name='isCustomized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolleaveplantoemployee',
            name='leavePlanName',
            field=models.TextField(default='invalid_plan', verbose_name='leave_plan_name'),
        ),
        migrations.AlterField(
            model_name='schoolleaveplantoemployee',
            name='parentEmployee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='schoolleaveplantoemployee',
            unique_together=set(),
        ),
    ]
