# Generated by Django 3.2.5 on 2023-04-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employee_isnonsalariedemployee'),
        ('leaves_app', '0004_schoolleaveplantoemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeavePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeLeavePlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves_app.schoolleaveplan')),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
            options={
                'db_table': 'employee_leave_plan',
                'unique_together': {('activeLeavePlan', 'parentEmployee')},
            },
        ),
    ]
