# Generated by Django 3.2.5 on 2023-07-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employee_isnonsalariedemployee'),
        ('leaves_app', '0005_auto_20230703_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveTypeName', models.TextField(default='invalid_type', verbose_name='leave_name')),
                ('leaveType', models.TextField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid')),
                ('color', models.TextField(default='#ffffff', verbose_name='color')),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
                ('parentLeaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves_app.schoolleavetype')),
            ],
            options={
                'db_table': 'employee_leave_type',
                'unique_together': {('parentLeaveType', 'parentEmployee')},
            },
        ),
    ]
