# Generated by Django 3.2.5 on 2023-07-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_app', '0008_alter_schoolmerchantaccount_easebuzzbanklabel'),
        ('school_app', '0004_auto_20221216_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('generationDateTime', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateField(null=True)),
                ('smsDate', models.DateField(null=True)),
                ('smsIntervalDays', models.IntegerField(null=True)),
                ('modalDate', models.DateField(null=True)),
                ('suspensionDate', models.DateField(null=True)),
                ('cancelledDate', models.DateField(null=True)),
                ('paidDate', models.DateTimeField(null=True)),
                ('remark', models.TextField(null=True)),
                ('billPDF', models.FileField(upload_to='')),
                ('parentOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderList', to='payment_app.order')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolList', to='school_app.school')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentBill', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill_app.bill')),
                ('parentOrder', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_app.order')),
            ],
            options={
                'db_table': 'BillOrder',
            },
        ),
    ]
