# Generated by Django 3.2.5 on 2023-10-14 21:15

import bill_app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_app', '0008_alter_schoolmerchantaccount_easebuzzbanklabel'),
        ('school_app', '0004_auto_20221216_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('generationDateTime', models.DateTimeField(auto_now_add=True)),
                ('billDate', models.DateField(default=datetime.datetime.now)),
                ('towards', models.TextField(default='-')),
                ('pageHeaderWarningInterval', models.IntegerField(default=0, null=True)),
                ('modalWarningInterval', models.IntegerField(default=15, null=True)),
                ('functionalityBlockedInterval', models.IntegerField(default=30, null=True)),
                ('cancelledDate', models.DateField(blank=True, null=True)),
                ('paidDate', models.DateTimeField(blank=True, null=True)),
                ('billPDF', models.FileField(blank=True, null=True, upload_to=bill_app.models.upload_bill_to, verbose_name='Bill')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolList', to='school_app.school')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentBill', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billOrderList', to='bill_app.bill')),
                ('parentOrder', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billOrderList', to='payment_app.order')),
            ],
            options={
                'db_table': 'BillOrder',
            },
        ),
    ]
