# Generated by Django 3.2.5 on 2023-07-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_alter_schoolmerchantaccount_easebuzzbanklabel'),
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cancelledDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='modalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paidDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='parentOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderList', to='payment_app.order'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='smsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='smsIntervalDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='suspensionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
