# Generated by Django 3.2.5 on 2023-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_auto_20230718_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
