# Generated by Django 3.2.5 on 2023-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_alter_bill_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billPDF',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
