# Generated by Django 3.2.5 on 2023-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0004_alter_bill_billpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.TextField(default='Instalment No. - Session'),
        ),
    ]
