# Generated by Django 3.2.5 on 2023-07-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_alter_schoolmerchantaccount_easebuzzbanklabel'),
        ('bill_app', '0005_bill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billorder',
            name='parentBill',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billOrderList', to='bill_app.bill'),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='parentOrder',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billOrderList', to='payment_app.order'),
        ),
    ]
