# Generated by Django 3.2.5 on 2023-08-07 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0006_auto_20230720_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='modalDate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='parentOrder',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='smsDate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='smsIntervalDays',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='suspensionDate',
        ),
        migrations.AddField(
            model_name='bill',
            name='billDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='functionalityBlockedInterval',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='modalWarningInterval',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='pageHeaderWarningInterval',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paidDate',
            field=models.DateTimeField(null=True),
        ),
    ]
