# Generated by Django 3.2.5 on 2023-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0007_auto_20230807_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paidDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
