# Generated by Django 3.2.5 on 2023-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0008_alter_bill_paiddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.AddField(
            model_name='bill',
            name='towards',
            field=models.TextField(default='-'),
        ),
    ]
