# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_auto_20180604_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='estimatedCount',
        ),
        migrations.AddField(
            model_name='sms',
            name='contentType',
            field=models.TextField(default='', verbose_name='contentType'),
        ),
        migrations.AddField(
            model_name='sms',
            name='notificationCount',
            field=models.IntegerField(default=0, verbose_name='notificationCount'),
        ),
        migrations.AddField(
            model_name='sms',
            name='notificationMobileNumberList',
            field=models.TextField(blank=True, default='', verbose_name='notificationMobileNumberList'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='mobileNumberList',
            field=models.TextField(blank=True, default='', verbose_name='mobileNumberList'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='requestId',
            field=models.TextField(null=True, verbose_name='requestId'),
        ),
    ]
