# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_second_app', '0005_auto_20180919_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concessionsecond',
            name='parentReceiver',
        ),
        migrations.RemoveField(
            model_name='feereceipt',
            name='parentReceiver',
        ),
    ]
