# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-31 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0012_auto_20200409_1653'),
        ('fees_third_app', '0004_auto_20200406_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='cancelledBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelledBy', to='employee_app.Employee', verbose_name='cancelledBy'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='cancelledDateTime',
            field=models.DateTimeField(null=True, verbose_name='cancelledDateTime'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='cancelledRemark',
            field=models.TextField(null=True, verbose_name='cancelledRemark'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentEmployee', to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
    ]
