# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-06 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from fees_third_app.db_script.lock_fee_to_fee_settings_migration import lock_fees_migration

class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20210402_0839'),
        ('school_app', '0042_schoolsummary'),
        ('fees_third_app', '0005_auto_20201231_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionLocked', models.BooleanField(default=False)),
                ('accountingSettings', models.TextField(null=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
                ('parentSession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session')),
            ],
        ),
        migrations.RunPython(lock_fees_migration),
        migrations.RemoveField(
            model_name='lockfee',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='lockfee',
            name='parentSession',
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.Transaction'),
        ),
        migrations.DeleteModel(
            name='LockFee',
        ),
        migrations.AlterUniqueTogether(
            name='feesettings',
            unique_together=set([('parentSchool', 'parentSession')]),
        ),
    ]
