# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:12
from __future__ import unicode_literals

from django.db import migrations
from fees_third_app.db_script.fix_crroupt_fee_receipts import fix_crroupt_fee_receipts


class Migration(migrations.Migration):

    dependencies = [
        ('fees_third_app', '0006_auto_20210406_1027'),
    ]

    operations = [
        migrations.RunPython(fix_crroupt_fee_receipts)
    ]
