# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from employee_app.db_script.transfer_permissions_to_employee_profile import transfer_permission_to_employee_profile

class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0031_school_medium'),
        ('team_app', '0002_auto_20180522_1534'),
        ('employee_app', '0002_auto_20180525_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('parentSchool', 'mobileNumber')]),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='parentEmployee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='parentTask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='team_app.Task', verbose_name='parentTask'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepermission',
            unique_together=set([('parentTask', 'parentEmployee')]),
        ),
        migrations.RunPython(transfer_permission_to_employee_profile),
    ]
