# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import employee_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_employee_spousename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to=employee_app.models.upload_avatar_to, verbose_name='Avatar'),
        ),
    ]
