# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 16:06
from __future__ import unicode_literals

from django.db import migrations

from employee_app.db_script.employee_i_card import employee_i_card


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_employee_profileimage'),
    ]

    operations = [
        migrations.RunPython(employee_i_card),

    ]
