# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-25 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0005_auto_20181112_1813'),
        ('student_app', '0015_auto_20181111_2134')

    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='parentClass',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='parentSession',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parentClassSession',
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
