# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import school_app.model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('printName', models.TextField(null=True)),
                ('profileImage', models.ImageField(blank=True, upload_to=school_app.model.models.upload_avatar_to, verbose_name='Avatar')),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopName', models.TextField()),
                ('kmDistance', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
            ],
            options={
                'db_table': 'bus_stop',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('printName', models.TextField(null=True)),
                ('profileImage', models.ImageField(blank=True, upload_to=school_app.model.models.upload_avatar_to, verbose_name='Avatar')),
                ('principalSignatureImage', models.ImageField(blank=True, upload_to=school_app.model.models.upload_principal_signature_to, verbose_name='Principal Signature')),
                ('mobileNumber', models.BigIntegerField(null=True)),
                ('expired', models.BooleanField(default=False, verbose_name='expired')),
                ('dateOfExpiry', models.DateField(blank=True, default=None, null=True, verbose_name='date_of_expiry')),
                ('dateOfCreation', models.DateField(blank=True, default=None, null=True, verbose_name='date_of_creation')),
                ('primaryThemeColor', models.TextField(null=True)),
                ('secondaryThemeColor', models.TextField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True, verbose_name='pincode')),
                ('villageCity', models.TextField(blank=True, null=True, verbose_name='villageCity')),
                ('block', models.TextField(blank=True, null=True, verbose_name='block')),
                ('district', models.TextField(blank=True, null=True, verbose_name='district')),
                ('state', models.TextField(blank=True, null=True, verbose_name='state')),
                ('diseCode', models.TextField(null=True)),
                ('registrationNumber', models.TextField(default='426/13.01.1993')),
                ('affiliationNumber', models.TextField(blank=True, null=True)),
                ('smsId', models.CharField(default='KORNGL', max_length=10, verbose_name='smsId')),
                ('opacity', models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='opacity')),
                ('medium', models.CharField(choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi')], default='ENGLISH', max_length=15)),
                ('headerSize', models.CharField(choices=[('BIG', 'Big'), ('SMALL', 'Small')], default='SMALL', max_length=15)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingDays', models.IntegerField(default=0)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'school_session',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.TextField(default='', null=True)),
                ('orderNumber', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.AddField(
            model_name='school',
            name='currentSession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='currentSession'),
        ),
        migrations.AddField(
            model_name='school',
            name='parentBoard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsession',
            unique_together=set([('parentSession', 'parentSchool')]),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together=set([('parentSchool', 'stopName')]),
        ),
    ]
