# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='mobileNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='pincode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='pincode'),
        ),
    ]
