# Generated by Django 3.2.5 on 2021-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_school_smsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpiryInformationJobsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('INITIATED', 'INITIATED'), ('SENT', 'SENT')], default='INITIATED', max_length=30)),
            ],
        ),
    ]
