# Generated by Django 3.2.5 on 2021-11-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_dailyjobsreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyJobsReport',
            new_name='SchoolExpiryInformationJobsReport',
        ),
    ]
