# Generated by Django 3.2.5 on 2022-12-16 16:22

from django.db import migrations
from school_app.db_script.add_session_from_1901 import add_old_sessions


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['orderNumber']},
        ),
        migrations.RunPython(add_old_sessions),
    ]
