# Generated by Django 3.2.5 on 2022-02-23 05:44

from django.db import migrations

from school_app.db_script.add_new_session import add_new_session


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
    ]

    operations = [
        migrations.RunPython(add_new_session)
    ]
