# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models

from school_app.db_script.populate_expiry_date import populate_expiry_date


class Migration(migrations.Migration):
    dependencies = [
        ('school_app', '0039_auto_20200104_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='expired'),
        ),
        migrations.RunPython(populate_expiry_date)
    ]
