# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0040_school_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='dateOfExpiration',
        ),
    ]
