# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import school_app.model.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('printName', models.TextField(null=True)),
                ('profileImage', models.ImageField(blank=True, upload_to=school_app.model.models.upload_avatar_to, verbose_name='Avatar')),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
    ]
