# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_schoolsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='complexFeeStructure',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='affiliationNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='block',
            field=models.TextField(blank=True, null=True, verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='school',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, verbose_name='pincode'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='school',
            name='villageCity',
            field=models.TextField(blank=True, null=True, verbose_name='villageCity'),
        ),
    ]
