# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-17 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0044_auto_20210802_1526'),
        ('sms_app', '0006_auto_20210616_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='smsId',
        ),
    ]
