# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models

from school_app.db_script.populate_sms_balance import populate_sms_balance


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0044_smsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='smsBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_sms_balance)
    ]
