# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='action',
            field=models.CharField(choices=[('SIGN UP', 'SIGN UP'), ('FORGOT PASSWORD', 'FORGOT PASSWORD')], max_length=20, null=True),
        ),
    ]
