# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expense',
        ),
    ]
