# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models

from subject_app.db_script.populate_subject import populate_subject

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0019_auto_20180321_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', unique=True, verbose_name='name')),
                ('orderNumber', models.IntegerField(default=0, verbose_name='orderNumber')),
                ('governmentSubject', models.BooleanField(default=True, verbose_name='governmentSubject')),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['orderNumber'],
            },
        ),
        migrations.RunPython(populate_subject),
    ]
