# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from subject_app.db_script.populate_subject_second import populate_subject
from subject_app.db_script.access_subject_app import access_subject_app


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_auto_20181111_2134'),
        ('class_app', '0006_merge_20181125_1213'),
        ('school_app', '0033_remove_school_logo'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'class_subject',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='-', unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'subject_second',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='parentSubject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.SubjectSecond', verbose_name='parentSubject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='parentSubject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.SubjectSecond', verbose_name='parentSubject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together=set([('parentSubject', 'parentStudent', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set([('parentClass', 'parentDivision', 'parentSchool', 'parentSubject', 'parentSession')]),
        ),
        migrations.RunPython(populate_subject),
        migrations.RunPython(access_subject_app),
    ]
