# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from subject_app.db_script.give_teacher_subject_permissions import give_teacher_subject_permission


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_employee_dateofleaving'),
        ('subject_app', '0002_auto_20181201_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='mainSubject',
            field=models.BooleanField(default=True, verbose_name='mainSubject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='onlyGrade',
            field=models.BooleanField(default=False, verbose_name='onlyGrade'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='parentEmployee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.RunPython(give_teacher_subject_permission),
    ]
