# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0004_auto_20190214_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='orderNumber',
            field=models.IntegerField(default=0, verbose_name='orderNumber'),
        ),
    ]
