# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_app', '0001_initial'),
        ('school_app', '0001_initial'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.TextField()),
                ('topic', models.TextField()),
                ('link', models.TextField()),
                ('orderNumber', models.DecimalField(decimal_places=1, max_digits=8)),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('parentClassSubject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subject_app.ClassSubject', verbose_name='parentClassSubject')),
            ],
            options={
                'db_table': 'tutorial',
            },
        ),
        migrations.CreateModel(
            name='TutorialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendCreateUpdate', models.BooleanField(default=True, verbose_name='sendCreateUpdate')),
                ('sendEditUpdate', models.BooleanField(default=True, verbose_name='sendEditUpdate')),
                ('sendDeleteUpdate', models.BooleanField(default=True, verbose_name='sendDeleteUpdate')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('sentUpdateType', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='information_app.SentUpdateType')),
            ],
        ),
    ]
