# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_app', '0006_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.TextField()),
                ('topic', models.TextField()),
                ('link', models.TextField()),
                ('orderNumber', models.DecimalField(decimal_places=1, max_digits=8)),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('parentClassSubject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.ClassSubject', verbose_name='parentClassSubject')),
            ],
            options={
                'db_table': 'tutorial',
            },
        ),
    ]
