# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-19 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_app', '0001_initial'),
        ('sms_app', '0002_sms_template_addon')
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='sentUpdateType',
        ),
        migrations.DeleteModel(
            name='TutorialSettings',
        ),
    ]
