# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('information_app', '0002_sentupdatetype'),
        ('tutorial_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendCreateUpdate', models.BooleanField(default=True, verbose_name='sendCreateUpdate')),
                ('sendEditUpdate', models.BooleanField(default=True, verbose_name='sendEditUpdate')),
                ('sendDeleteUpdate', models.BooleanField(default=True, verbose_name='sendDeleteUpdate')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('sentUpdateType', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='information_app.SentUpdateType')),
            ],
        ),
    ]
