# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_smsevent_smstemplate'),
        ('tutorial_app', '0002_tutorialsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='sendCreateUpdate',
        ),
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='sendDeleteUpdate',
        ),
        migrations.RemoveField(
            model_name='tutorialsettings',
            name='sendEditUpdate',
        ),
        migrations.AddField(
            model_name='tutorialsettings',
            name='parentEvent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSEvent', verbose_name='parentEvent'),
        ),
        migrations.AddField(
            model_name='tutorialsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSTemplate', verbose_name='parentSMSTemplate'),
        ),
        migrations.AlterModelTable(
            name='tutorialsettings',
            table='tutorial_settings',
        ),
    ]
