# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to=student_app.models.upload_avatar_to, verbose_name='Avatar')),
                ('name', models.CharField(max_length=100)),
                ('fathersName', models.CharField(max_length=100)),
                ('mobileNumber', models.BigIntegerField(null=True)),
                ('secondMobileNumber', models.BigIntegerField(null=True)),
                ('scholarNumber', models.TextField(blank=True, null=True)),
                ('totalFees', models.IntegerField(default=0)),
                ('dateOfBirth', models.DateField(null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('motherName', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('caste', models.TextField(blank=True, null=True)),
                ('newCategoryField', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Classes'), ('Gen.', 'General')], max_length=5, null=True)),
                ('newReligionField', models.CharField(choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Jainism', 'Jainism')], max_length=20, null=True)),
                ('fatherOccupation', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('familySSMID', models.BigIntegerField(null=True)),
                ('childSSMID', models.BigIntegerField(null=True)),
                ('bankName', models.TextField(blank=True, null=True)),
                ('bankIfscCode', models.TextField(blank=True, null=True)),
                ('bankAccountNum', models.TextField(blank=True, null=True)),
                ('aadharNum', models.BigIntegerField(null=True)),
                ('bloodGroup', models.TextField(blank=True, null=True)),
                ('fatherAnnualIncome', models.TextField(blank=True, null=True)),
                ('rte', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
                ('dateOfAdmission', models.DateField(null=True, verbose_name='dateOfAdmission')),
                ('admissionSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='admissionSession')),
                ('currentBusStop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.BusStop', verbose_name='current_bus_stop')),
                ('parentAdmissionClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_app.Class')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameterType', models.CharField(choices=[('TEXT', 'TEXT'), ('FILTER', 'FILTER'), ('DOCUMENT', 'DOCUMENT')], max_length=20)),
                ('filterValues', models.TextField(blank=True, null=True)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'student_parameter',
            },
        ),
        migrations.CreateModel(
            name='StudentParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('document_value', models.FileField(blank=True, max_length=500, null=True, upload_to=student_app.models.upload_document_to)),
                ('document_size', models.TextField(blank=True, null=True)),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
                ('parentStudentParameter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.StudentParameter', verbose_name='parentStudentParameter')),
            ],
            options={
                'db_table': 'student_parameter_value',
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.TextField(blank=True, null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_section',
            },
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateNumber', models.BigIntegerField()),
                ('issueDate', models.DateField()),
                ('leavingDate', models.DateField()),
                ('leavingReason', models.TextField()),
                ('admissionClass', models.TextField()),
                ('lastClassPassed', models.TextField()),
                ('leavingMidSession', models.BooleanField(default=False)),
                ('lastClassAttended', models.TextField(null=True)),
                ('lastClassAttendance', models.IntegerField(null=True)),
                ('attendanceOutOf', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'student_transfer_certificate',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parentTransferCertificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.TransferCertificate', verbose_name='parentTransferCertificate'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsection',
            unique_together=set([('parentStudent', 'parentDivision', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentparametervalue',
            unique_together=set([('parentStudent', 'parentStudentParameter')]),
        ),
    ]
