# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadharNum',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='childSSMID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='familySSMID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondMobileNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
