# Generated by Django 3.2.5 on 2021-12-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAllTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(max_length=50)),
                ('rows', models.JSONField()),
                ('cols', models.JSONField()),
            ],
        ),
    ]
