# Generated by Django 3.2.5 on 2022-01-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
        ('class_app', '0001_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admissionSession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studentList', to='school_app.session', verbose_name='admissionSession'),
        ),
        migrations.AlterField(
            model_name='student',
            name='currentBusStop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studentList', to='school_app.busstop', verbose_name='current_bus_stop'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentAdmissionClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentList', to='class_app.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='studentList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentTransferCertificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentList', to='student_app.transfercertificate', verbose_name='parentTransferCertificate'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='parentClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='studentSectionList', to='class_app.class', verbose_name='parentClass'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='parentDivision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='studentSectionList', to='class_app.division', verbose_name='parentDivision'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='studentSectionList', to='school_app.session', verbose_name='parentSession'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studentSectionList', to='student_app.student', verbose_name='parentStudent'),
        ),
        migrations.CreateModel(
            name='CountAllTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(max_length=50)),
                ('rows', models.JSONField()),
                ('cols', models.JSONField()),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='countAllTableList', to='school_app.school')),
            ],
            options={
                'db_table': 'count_all_table',
            },
        ),
    ]
