# Generated by Django 3.2.5 on 2021-12-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_countalltable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countalltable',
            table='count_all_table',
        ),
    ]
