# Generated by Django 3.2.5 on 2021-12-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
        ('student_app', '0002_auto_20211221_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAllTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(max_length=50)),
                ('rows', models.JSONField()),
                ('cols', models.JSONField()),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='countAllTableList', to='school_app.school')),
            ],
            options={
                'db_table': 'count_all_table',
            },
        ),
    ]
