# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20210717_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='certificateNumber',
            field=models.BigIntegerField(),
        ),
    ]
