# Generated by Django 3.2.5 on 2022-01-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20211115_0204'),
        ('student_app', '0002_auto_20220103_1321'),
    ]

    operations = [
    ]
