# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import student_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20210717_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparametervalue',
            name='document_value',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=student_app.models.upload_document_to),
        ),
    ]
