# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0027_auto_20200816_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparametervalue',
            name='document_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentparametervalue',
            name='document_value',
            field=models.FileField(blank=True, null=True, upload_to='upload_student_parameter_document_to/'),
        ),
        migrations.AlterField(
            model_name='studentparameter',
            name='parameterType',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('FILTER', 'FILTER'), ('DOCUMENT', 'DOCUMENT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentparametervalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
