# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0031_auto_20210116_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admissionClass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
