# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_auto_20191130_2039'),
        ('student_app', '0031_auto_20210116_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentAdmissionClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_app.Class'),
        ),
    ]
