# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('employee_app', '0012_auto_20200409_1653'),
        ('subject_app', '0006_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(null=True, verbose_name='startTime')),
                ('endTime', models.TimeField(null=True, verbose_name='endTime')),
                ('meetingNumber', models.BigIntegerField(blank=True)),
                ('password', models.CharField(blank=True, max_length=10)),
                ('configJSON', models.TextField()),
                ('parentClassSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.ClassSubject')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'db_table': 'ActiveClasses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='onlineclass',
            unique_together=set([('parentSchool', 'parentClassSubject')]),
        ),
    ]
