# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('class_app', '0007_auto_20191130_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(null=True, verbose_name='startTime')),
                ('endTime', models.TimeField(null=True, verbose_name='endTime')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.Division', verbose_name='parentDivision')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'ActiveClasses',
            },
        ),
    ]
