# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0007_auto_20191130_2039'),
        ('school_app', '0043_auto_20210414_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(null=True, verbose_name='startTime')),
                ('endTime', models.TimeField(null=True, verbose_name='endTime')),
                ('meetingNumber', models.BigIntegerField(blank=True)),
                ('password', models.CharField(blank=True, max_length=10)),
                ('configJSON', models.TextField()),
                ('parentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Class')),
                ('parentDivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Division')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'db_table': 'ActiveClasses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='onlineclass',
            unique_together=set([('parentSchool', 'parentClass', 'parentDivision')]),
        ),
    ]
