# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-31 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0006_auto_20190901_1142'),
        ('student_app', '0033_auto_20210519_0449'),
        ('online_classes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('parentClassSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.ClassSubject')),
                ('parentStudentSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.StudentSection')),
            ],
        ),
    ]
