# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0033_auto_20210519_0449'),
        ('subject_app', '0006_auto_20190901_1142'),
        ('online_classes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('parentClassSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.ClassSubject')),
                ('parentStudentSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.StudentSection')),
            ],
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='meetingNumber',
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='password',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='meetingNumber',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='passcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
