# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='mettingNumber',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='passCode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
