# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-31 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0002_studentattendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
