# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-12 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0002_auto_20210607_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='username',
        ),
    ]
