# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-19 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0002_auto_20210519_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestrictedStuden',
            new_name='RestrictedStudent',
        ),
    ]
