# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0002_auto_20210425_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='configJSON',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
