# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-25 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0003_onlineclass_configjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclass',
            old_name='passCode',
            new_name='password',
        ),
    ]
