# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0003_auto_20210612_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='meetingUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
