# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-31 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0003_auto_20210531_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAttendence',
            new_name='StudentAttendance',
        ),
    ]
