# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0004_accountinfo_meetingurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='passcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
