# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0004_auto_20210523_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='configJSON',
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='endTimeJSON',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='startTimeJSON',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
