# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-07 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0004_auto_20210531_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='meetingNumber',
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='duration',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='meetingNumber',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='passcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
