# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-26 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0004_auto_20210426_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclass',
            old_name='mettingNumber',
            new_name='meetingNumber',
        ),
    ]
