# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0004_auto_20210708_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='meetingNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
