# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-23 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0005_auto_20210523_2251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlineclass',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='onlineclass',
            table=None,
        ),
    ]
