# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0006_auto_20210524_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='parentSchool',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='parentEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='accountinfo',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table=None,
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='parentSchool',
        ),
    ]
