# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-24 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes_app', '0007_auto_20210524_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='parentAccountInfo',
        ),
    ]
