# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from team_app.db_script.changing_structure import changing_structure


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0038_auto_20190906_2037'),
        ('team_app', '0003_auto_20180919_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='access',
            name='parentModule',
        ),
        migrations.RemoveField(
            model_name='access',
            name='parentSchool',
        ),
        migrations.AddField(
            model_name='module',
            name='parentBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.AddField(
            model_name='task',
            name='parentBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.RunPython(changing_structure),
    ]
