# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from team_app.db_script.changing_structure import changing_structure
from team_app.db_script.add_mp_board_report_card_module import add_mp_board_report_card_module
from team_app.db_script.add_cbse_report_card_module import add_cbse_report_card_module
from team_app.db_script.add_class_module import add_class_module
from team_app.db_script.add_view_marks_to_examination import add_view_marks_to_examination


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0038_auto_20191130_2039'),
        ('team_app', '0003_auto_20180919_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='access',
            name='parentModule',
        ),
        migrations.RemoveField(
            model_name='access',
            name='parentSchool',
        ),
        migrations.AddField(
            model_name='module',
            name='parentBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.AddField(
            model_name='task',
            name='parentBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.RunPython(changing_structure),
        migrations.RunPython(add_mp_board_report_card_module),
        migrations.RunPython(add_cbse_report_card_module),
        migrations.RunPython(add_class_module),
        migrations.RunPython(add_view_marks_to_examination),
    ]
