# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-20 13:11
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_student_remark_row_mp_board import add_student_remark_row_mp_board


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_auto_20191130_2039'),
    ]

    operations = [
    	migrations.RunPython(add_student_remark_row_mp_board),
    ]
