# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-30 03:07
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_view_marks_to_examination import add_view_marks_to_examination

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_auto_20190908_1908'),
    ]

    operations = [
        migrations.RunPython(add_view_marks_to_examination),
    ]
