# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-05 10:54
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_student_remark_row_mp_board import add_student_remark_row_mp_board


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_auto_20200115_1928'),
    ]

    operations = [
        migrations.RunPython(add_student_remark_row_mp_board),
    ]
