# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-09 17:21
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.rename_view_defaulters import rename_view_defaulters


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_auto_20200205_1624'),
    ]

    operations = [
        migrations.RunPython(rename_view_defaulters),
    ]
