# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-25 10:59
from __future__ import unicode_literals
from team_app.db_script.add_set_roll_number_task import add_set_roll_number_task_and_permission


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0007_auto_20200309_2251'),
    ]

    operations = [
        migrations.RunPython(add_set_roll_number_task_and_permission)
    ]
