# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-04 18:00
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_custom_report_card_module import add_custom_report_card_module
from team_app.db_script.add_manage_layout_task import add_manage_layout_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_auto_20200303_2003'),
    ]

    operations = [
    	migrations.RunPython(add_custom_report_card_module),
    	migrations.RunPython(add_manage_layout_task),
    ]
