# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-07 13:10
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_grade_student_task import add_grade_student_and_permission

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_auto_20200304_2330'),
    ]

    operations = [
        migrations.RunPython(add_grade_student_and_permission),
    ]