# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-10 14:10
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_view_grade_and_permission import add_view_grade_and_permission

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_auto_20200307_1840'),
    ]

    operations = [
        migrations.RunPython(add_view_grade_and_permission)
    ]
