# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-11 14:43
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_student_remarks_task import add_student_remarks_task

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0011_auto_20200310_1940'),
    ]

    operations = [
        migrations.RunPython(add_student_remarks_task)
    ]
