# Generated by Django 3.2.5 on 2022-01-19 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_app', '0001_initial'),
        ('school_app', '0003_schoolexpiryinformationjobsreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defaultText', models.TextField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school')),
            ],
            options={
                'db_table': 'complaint_type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school')),
            ],
            options={
                'db_table': 'complaint_status',
            },
        ),
        migrations.CreateModel(
            name='StatusComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentComplaintType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_support_app.complainttype')),
                ('parentStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_support_app.status')),
            ],
            options={
                'db_table': 'status_complaintType',
            },
        ),
        migrations.CreateModel(
            name='EmployeeComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentComplaintType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_support_app.complainttype')),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
            options={
                'db_table': 'employee_complaintType',
            },
        ),
        migrations.CreateModel(
            name='CountAllParentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(max_length=100)),
                ('rows', models.JSONField()),
                ('cols', models.JSONField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school')),
            ],
            options={
                'db_table': 'count_all_parentSupport',
            },
        ),
        migrations.AddField(
            model_name='complainttype',
            name='parentStatusDefault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_support_app.status'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('parentComplaintType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_support_app.complainttype')),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school')),
                ('parentStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_support_app.status')),
                ('parentStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('parentComplaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_support_app.complaint')),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employee')),
                ('parentStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('parentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_comment',
            },
        ),
    ]
