# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=320)),
                ('method', models.CharField(max_length=10)),
                ('queryString', models.TextField(blank=True, null=True)),
                ('responseSize', models.PositiveIntegerField()),
                ('responseTime', models.FloatField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('parentSchool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
    ]
