# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-21 10:45
from __future__ import unicode_literals

import accounts_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_app', '0012_auto_20200409_1653'),
        ('school_app', '0042_schoolsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.TextField(choices=[('GROUP', 'GROUP'), ('ACCOUNT', 'ACCOUNT')], default='ACCOUNT')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='balance')),
                ('parentAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentAccount', to='accounts_app.Accounts', verbose_name='parentAccount')),
                ('parentGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentGroup', to='accounts_app.Accounts', verbose_name='parentGroup')),
            ],
            options={
                'db_table': 'account_session',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvalId', models.IntegerField(blank=True, null=True, verbose_name='voucherNumber')),
                ('requestedGenerationDateTime', models.DateField(null=True, verbose_name='requestedGenerationDateTime')),
                ('approvedGenerationDateTime', models.DateField(null=True, verbose_name='approvedGenerationDateTime')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('autoAdd', models.BooleanField(default=False)),
                ('transactionDate', models.DateField(null=True, verbose_name='transactionDate')),
                ('requestStatus', models.TextField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DECLINED', 'DECLINED')], default='PENDING', null=True)),
                ('parentEmployeeApprovedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentEmployeeApprovedBy', to='employee_app.Employee')),
                ('parentEmployeeRequestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentEmployeeRequestedBy', to='employee_app.Employee')),
            ],
            options={
                'db_table': 'approval',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transactionType', models.TextField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')])),
                ('parentAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Accounts')),
                ('parentApproval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval', verbose_name='parentApproval')),
            ],
            options={
                'db_table': 'approval_account_details',
            },
        ),
        migrations.CreateModel(
            name='ApprovalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=accounts_app.models.upload_image_to_1, verbose_name='approval_image')),
                ('imageType', models.TextField(choices=[('BILL', 'BILL'), ('QUOTATION', 'QUOTATION')])),
                ('orderNumber', models.IntegerField(default=0, verbose_name='orderNumber')),
                ('parentApproval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval', verbose_name='parentApproval')),
            ],
            options={
                'db_table': 'approval_images',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAmountPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrictedAmount', models.IntegerField(blank=True, default=0, null=True, verbose_name='restrictedAmount')),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
            options={
                'db_table': 'employee_amount_permission',
            },
        ),
        migrations.CreateModel(
            name='Heads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
            ],
            options={
                'db_table': 'heads',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNumber', models.IntegerField(blank=True, null=True, verbose_name='voucherNumber')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('transactionDate', models.DateField(null=True, verbose_name='transactionDate')),
                ('approvalId', models.IntegerField(blank=True, null=True)),
                ('parentEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transactionType', models.TextField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')])),
                ('parentAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Accounts')),
                ('parentTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Transaction', verbose_name='parentTransaction')),
            ],
            options={
                'db_table': 'transaction_account_details',
            },
        ),
        migrations.CreateModel(
            name='TransactionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=accounts_app.models.upload_image_to, verbose_name='transaction_image')),
                ('orderNumber', models.IntegerField(default=0, verbose_name='orderNumber')),
                ('imageType', models.TextField(choices=[('BILL', 'BILL'), ('QUOTATION', 'QUOTATION')])),
                ('parentTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Transaction', verbose_name='parentTransaction')),
            ],
            options={
                'db_table': 'transaction_images',
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.Transaction', verbose_name='parentTransaction'),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='parentHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Heads', verbose_name='parentHead'),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Session', verbose_name='parentSession'),
        ),
    ]
