# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeamountpermission',
            name='restrictedAmount',
            field=models.BigIntegerField(default=0),
        ),
    ]
