# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations
from accounts_app.db_script.populate_heads import populate_heads

class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_heads),
    ]