# Generated by Django 3.2.5 on 2021-07-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='parentGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupAcccountSessions', to='accounts_app.accounts'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='parentHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.heads'),
        ),
    ]
