# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-09 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20210221_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='title',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
