# Generated by Django 3.2.5 on 2021-10-14 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
        ('school_app', '0002_remove_school_smsid'),
        ('accounts_app', '0002_auto_20210718_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionsList', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='transactionaccountdetails',
            name='parentAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactionAccountDetailsList', to='accounts_app.accounts'),
        ),
        migrations.AlterField(
            model_name='transactionaccountdetails',
            name='parentTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionAccountDetailsList', to='accounts_app.transaction'),
        ),
    ]
