# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20210209_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequests',
            name='usedForPayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='autoAdd',
            field=models.BooleanField(default=False),
        ),
    ]
