# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-10 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_lockaccounts'),
        ('accounts_app', '0002_auto_20210309_1713'),
    ]

    operations = [
    ]
