# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_accounts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='title',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
