# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 10:07
from __future__ import unicode_literals

import accounts_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0012_auto_20200409_1653'),
        ('accounts_app', '0004_auto_20210209_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequestAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transactionType', models.TextField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Accounts')),
            ],
            options={
                'db_table': 'approval_request_account_details',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=accounts_app.models.upload_image_to_1, verbose_name='approval_request_image')),
                ('imageType', models.TextField(choices=[('BILL', 'BILL'), ('QUOTATION', 'QUOTATION')])),
            ],
            options={
                'db_table': 'approval_request_images',
            },
        ),
        migrations.RemoveField(
            model_name='approvalrequests',
            name='parentEmployee',
        ),
        migrations.RemoveField(
            model_name='approvalrequests',
            name='usedForPayment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='autoAdd',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionStatus',
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='approvalRequestDate',
            field=models.DateField(null=True, verbose_name='approvalRequestDate'),
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='approvedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to='employee_app.Employee', verbose_name='approvedBy'),
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='autoAdd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='raisedBy',
            field=models.ForeignKey(default=1052, on_delete=django.db.models.deletion.CASCADE, related_name='raisedBy', to='employee_app.Employee', verbose_name='raisedBy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='requestStatus',
            field=models.TextField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DECLINED', 'DECLINED')], default='PENDING', null=True),
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='voucherNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='voucherNumber'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approvalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='approvalId'),
        ),
        migrations.AlterField(
            model_name='approvalrequests',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.Transaction', verbose_name='parentTransaction'),
        ),
        migrations.AddField(
            model_name='approvalrequestimages',
            name='parentApprovalRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ApprovalRequests', verbose_name='parentApprovalRequest'),
        ),
        migrations.AddField(
            model_name='approvalrequestaccountdetails',
            name='parentApprovalRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ApprovalRequests', verbose_name='parentApprovalRequest'),
        ),
    ]
