# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-13 13:11
from __future__ import unicode_literals

import accounts_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_schoolsummary'),
        ('accounts_app', '0004_merge_20210310_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='parentAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acccountSessions', to='accounts_app.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='parentGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupAcccountSessions', to='accounts_app.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='parentHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Heads'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Session'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approvalId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approvedGenerationDateTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='parentEmployeeApprovedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApprovedList', to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='parentEmployeeRequestedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApprovalList', to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='parentTransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Transaction'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='requestedGenerationDateTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='transactionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='approvalaccountdetails',
            name='parentApproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval'),
        ),
        migrations.AlterField(
            model_name='approvalimages',
            name='parentApproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval'),
        ),
        migrations.AlterField(
            model_name='employeeamountpermission',
            name='parentEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeamountpermission',
            name='restrictedAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heads',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lockaccounts',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.AlterField(
            model_name='lockaccounts',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucherNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionaccountdetails',
            name='parentTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Transaction'),
        ),
        migrations.AlterField(
            model_name='transactionimages',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to=accounts_app.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='transactionimages',
            name='orderNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionimages',
            name='parentTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='lockaccounts',
            unique_together=set([('parentSchool', 'parentSession')]),
        ),
    ]
