# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_schoolsummary'),
        ('accounts_app', '0005_auto_20210407_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approvalId',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set([('parentSession', 'approvalId')]),
        ),
    ]
