# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20210313_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsession',
            name='currentBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='openingBalance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lockaccounts',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.AlterField(
            model_name='lockaccounts',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session'),
        ),
        migrations.AlterField(
            model_name='transactionaccountdetails',
            name='parentAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.Accounts'),
        ),
    ]
