# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20210210_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequestimages',
            name='orderNumber',
            field=models.IntegerField(default=0, verbose_name='orderNumber'),
        ),
        migrations.AddField(
            model_name='transactionimages',
            name='orderNumber',
            field=models.IntegerField(default=0, verbose_name='orderNumber'),
        ),
    ]
