# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20210407_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approvalId',
            field=models.IntegerField(blank=True),
        ),
    ]
