# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_auto_20210210_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequests',
            old_name='approvedBy',
            new_name='parentEmployeeApprovedBy',
        ),
        migrations.RenameField(
            model_name='approvalrequests',
            old_name='raisedBy',
            new_name='parentEmployeeRequestedBy',
        ),
        migrations.RenameField(
            model_name='approvalrequests',
            old_name='approvalRequestDate',
            new_name='requestedGenerationDateTime',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='approvalId',
            new_name='parentApproval',
        ),
        migrations.RemoveField(
            model_name='approvalrequests',
            name='amount',
        ),
        migrations.AddField(
            model_name='approvalrequests',
            name='approvedGenerationDateTime',
            field=models.DateField(null=True, verbose_name='approvedGenerationDateTime'),
        ),
    ]
