# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-17 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_auto_20210315_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsession',
            name='balance',
        ),
    ]
