# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_auto_20210210_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequests',
            old_name='voucherNumber',
            new_name='approvalId',
        ),
        migrations.AlterField(
            model_name='approvalrequests',
            name='parentEmployeeApprovedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentEmployeeApprovedBy', to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='approvalrequests',
            name='parentEmployeeRequestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentEmployeeRequestedBy', to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='approvalrequests',
            name='requestedGenerationDateTime',
            field=models.DateField(null=True, verbose_name='requestedGenerationDateTime'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parentApproval',
            field=models.IntegerField(blank=True, null=True, verbose_name='parentApproval'),
        ),
    ]
