# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_auto_20210210_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequestaccountdetails',
            old_name='parentApprovalRequest',
            new_name='parentApproval',
        ),
        migrations.RenameField(
            model_name='approvalrequestimages',
            old_name='parentApprovalRequest',
            new_name='parentApproval',
        ),
    ]
