# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_auto_20210210_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequestaccountdetails',
            name='parentApproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval', verbose_name='parentApproval'),
        ),
        migrations.AlterField(
            model_name='approvalrequestimages',
            name='parentApproval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval', verbose_name='parentApproval'),
        ),
    ]
