# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-10 13:10
from __future__ import unicode_literals

import accounts_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_auto_20210210_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=accounts_app.models.upload_image_to_1, verbose_name='approval_image')),
                ('imageType', models.TextField(choices=[('BILL', 'BILL'), ('QUOTATION', 'QUOTATION')])),
                ('orderNumber', models.IntegerField(default=0, verbose_name='orderNumber')),
                ('parentApproval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Approval', verbose_name='parentApproval')),
            ],
            options={
                'db_table': 'approval_images',
            },
        ),
        migrations.RenameModel(
            old_name='ApprovalRequestAccountDetails',
            new_name='ApprovalAccountDetails',
        ),
        migrations.RemoveField(
            model_name='approvalrequestimages',
            name='parentApproval',
        ),
        migrations.AlterModelTable(
            name='approvalaccountdetails',
            table='approval_account_details',
        ),
        migrations.DeleteModel(
            name='ApprovalRequestImages',
        ),
    ]
