# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-12 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_auto_20210210_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='parentApproval',
            new_name='approvalId',
        ),
    ]
