# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_auto_20210212_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approvalId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
