# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0015_auto_20210212_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='transactionDate',
            field=models.DateField(null=True, verbose_name='transactionDate'),
        ),
    ]
