# Generated by Django 3.2.5 on 2021-08-11 09:18

from django.db import migrations, models
import django.db.models.deletion

from sms_app.db_script.populate_sms_templates import populate_sms_templates
from sms_app.db_script.populate_sms_event_settings import populate_sms_event_settings
from sms_app.db_script.populate_sms_id import populate_sms_id


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('MsgClubDeliveryReport', 'SMSDeliveryReport'),
        migrations.AddField(
            model_name='smsdeliveryreport',
            name='messageId',
            field=models.TextField(null=True, unique=True, verbose_name='messageId'),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='mobileNumber',
            field=models.BigIntegerField(null=True, verbose_name='mobileNumber'),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='requestId',
            field=models.TextField(null=True, verbose_name='requestId'),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='senderId',
            field=models.CharField(max_length=10, null=True, verbose_name='senderId'),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='statusCode',
            field=models.TextField(null=True, verbose_name='statusCode'),
        ),
        migrations.AlterUniqueTogether(
            name='smsdeliveryreport',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='smsdeliveryreport',
            table='sms_delivery_report',
        ),
        migrations.CreateModel(
            name='SMSEventSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMSEventId', models.IntegerField(default=0)),
                ('sendUpdateTypeId', models.IntegerField(default=0)),
                ('customNotificationContent', models.TextField(null=True, verbose_name='customNotificationContent')),
                ('receiverType', models.CharField(choices=[('All Students', 'All Students'), ('Only Absent Students', 'Only Absent Students')], max_length=20, null=True, verbose_name='receiverType')),
            ],
            options={
                'db_table': 'sms_event_settings',
            },
        ),
        migrations.CreateModel(
            name='SMSId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.TextField(verbose_name='entityName')),
                ('entityRegistrationId', models.TextField(verbose_name='entityRegistrationId')),
                ('smsId', models.CharField(max_length=10, verbose_name='smsId')),
                ('smsIdRegistrationNumber', models.TextField(null=True, verbose_name='SMSIdRegistrationNumber')),
                ('smsIdStatus', models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
            ],
            options={
                'db_table': 'sms_id',
                'unique_together': {('smsId', 'entityRegistrationId')},
            },
        ),
        migrations.CreateModel(
            name='SMSIdSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSMSId', models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='sms_app.smsid', verbose_name='parentSMSId')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.school', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'smsid_school',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='createdDate')),
                ('templateId', models.TextField(verbose_name='templateId')),
                ('templateName', models.TextField(verbose_name='templateName')),
                ('rawContent', models.TextField(verbose_name='rawContent')),
                ('mappedContent', models.TextField(blank=True, null=True, verbose_name='mappedContent')),
                ('parentSMSId', models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='sms_app.smsid', verbose_name='parentSenderId')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
        migrations.AddField(
            model_name='sms',
            name='SMSEventId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='mobileNumberContentJson',
            field=models.TextField(default='', verbose_name='contentMobileNumberJson'),
        ),
        migrations.AddField(
            model_name='sms',
            name='remark',
            field=models.TextField(default='SUCCESS', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='sms',
            name='scheduledDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='sentStatus',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10, null=True, verbose_name='sentStatus'),
        ),
        migrations.AddField(
            model_name='sms',
            name='smsGateWayHubVendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sms',
            name='contentType',
            field=models.TextField(default='', verbose_name='contentType(DCS)'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='information_app.messagetype'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.school', verbose_name='parentSchool'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.smstemplate', verbose_name='parentSMSTemplate'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.school', verbose_name='parentSchool'),
        ),
        migrations.AddField(
            model_name='sms',
            name='parentSMSId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.smsid', verbose_name='smsId'),
        ),
        migrations.RunPython(populate_sms_id),
        migrations.RunPython(populate_sms_templates),
        migrations.RunPython(populate_sms_event_settings),
    ]
