# Generated by Django 3.2.5 on 2021-08-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('school_app', '0001_initial'),
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSmsPaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsPurchaseJSON', models.TextField()),
                ('parentOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_app.order', unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.school')),
                ('parentSmsPurchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sms_app.smspurchase')),
            ],
        ),
    ]
