# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgclubdeliveryreport',
            name='mobileNumber',
            field=models.BigIntegerField(verbose_name='mobileNumber'),
        ),
    ]
