# Generated by Django 3.2.5 on 2021-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_DLT_required_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdeliveryreport',
            name='messageId',
            field=models.TextField(null=True, verbose_name='messageId'),
        ),
    ]
