# Generated by Django 3.2.5 on 2021-11-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_dailyjobsreport'),
        ('sms_app', '0002_DLT_required_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('sentDateTime', models.DateTimeField(auto_now_add=True, verbose_name='sentDateTime')),
                ('smsCount', models.IntegerField(default=0, verbose_name='smsCount')),
                ('notificationCount', models.IntegerField(default=0, verbose_name='notificationCount')),
                ('smsMobileNumberList', models.TextField(blank=True, default='', verbose_name='smsMobileNumberList')),
                ('notificationMobileNumberList', models.TextField(blank=True, default='', verbose_name='notificationMobileNumberList')),
                ('employeeNameList', models.TextField(blank=True, default='', verbose_name='employeeNameList')),
                ('parentSMSId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.smsid', verbose_name='smsId')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.school', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'sms_admin',
            },
        ),
    ]
