# Generated by Django 3.2.5 on 2021-10-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('school_app', '0002_remove_school_smsid'),
        ('sms_app', '0002_DLT_required_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspurchase',
            name='numberOfSMS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smspurchase',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='smsPurchaseList', to='school_app.school'),
        ),
        migrations.AlterField(
            model_name='smspurchase',
            name='purchaseDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SmsPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsPurchaseData', models.JSONField()),
                ('parentOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smsPurchaseOrderList', to='payment_app.order', unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smsPurchaseOrderList', to='school_app.school')),
                ('parentSmsPurchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smsPurchaseOrderList', to='sms_app.smspurchase')),
            ],
        ),
    ]
