# Generated by Django 3.2.5 on 2023-07-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_auto_20211015_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smseventsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.smstemplate', verbose_name='parentSMSTemplate'),
        ),
    ]
