# Generated by Django 3.2.5 on 2021-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_smsadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsadmin',
            name='employeeNameList',
        ),
        migrations.AddField(
            model_name='smsadmin',
            name='notificationEmployeeList',
            field=models.TextField(blank=True, default='', verbose_name='notificationEmployeeList'),
        ),
        migrations.AddField(
            model_name='smsadmin',
            name='smsEmployeeList',
            field=models.TextField(blank=True, default='', verbose_name='smsEmployeeList'),
        ),
    ]
