# Generated by Django 3.2.5 on 2021-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_smspurchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smspurchaseorder',
            name='smsPurchaseJSON',
        ),
        migrations.AddField(
            model_name='smspurchaseorder',
            name='smsPurchaseData',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
