# Generated by Django 3.2.5 on 2021-09-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_smsdeliveryreport_messageid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsdeliveryreport',
            unique_together={('requestId', 'mobileNumber', 'messageId')},
        ),
    ]
