# Generated by Django 3.2.5 on 2023-08-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_alter_smseventsettings_parentsmstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='msgClubVendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sms',
            name='parentSMSTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.smstemplate', verbose_name='smsTemplate'),
        ),
        migrations.AddField(
            model_name='sms',
            name='payload',
            field=models.TextField(null=True, verbose_name='payload'),
        ),
        migrations.AddField(
            model_name='sms',
            name='response',
            field=models.TextField(null=True, verbose_name='payload'),
        ),
    ]
