# Generated by Django 3.2.5 on 2021-11-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_auto_20211119_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSAdmin',
        ),
    ]
