# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0044_smsid'),
        ('sms_app', '0005_sms_parentmessagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=50, verbose_name='eventName')),
                ('defaultSMSContent', models.TextField(verbose_name='defaultSMSContent')),
                ('defaultNotificationContent', models.TextField(verbose_name='defaultNotificationContent')),
            ],
            options={
                'db_table': 'sms_event',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='createdDate')),
                ('smsTemplateId', models.TextField(verbose_name='smsTemplateId')),
                ('smsTemplateName', models.TextField(verbose_name='smsTemplateName')),
                ('smsRawContent', models.TextField(verbose_name='smsRawContent')),
                ('smsMappedContent', models.TextField(verbose_name='smsMappedContent')),
                ('registrationStatus', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
                ('parentSMSId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.SMSId', verbose_name='parentSMSId')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
    ]
