# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('payment_app', '0001_initial'),
        ('sms_app', '0005_sms_parentmessagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSmsPaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsPurchaseJSON', models.TextField()),
                ('parentOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_app.Order', unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School')),
                ('parentSmsPurchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sms_app.SMSPurchase')),
            ],
        ),
    ]
