# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-20 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from sms_app.db_script.populate_sender_id import populate_sender_id
from sms_app.db_script.populate_sms_event_settings import populate_sms_event_settings
from sms_app.db_script.populate_sms_events import populate_sms_events
from sms_app.db_script.populate_sms_templates import populate_sms_templates


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0004_auto_20210130_1500'),
        ('sms_app', '0005_sms_parentmessagetype'),
        ('homework_app', '0001_initial'),
        ('tutorial_app', '0002_tutorialsettings'),
        ('attendance_app', '0010_attendancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.TextField(verbose_name='entityName')),
                ('entityRegistrationId', models.TextField(verbose_name='entityName')),
                ('senderId', models.CharField(max_length=10, verbose_name='senderId')),
                ('senderRegistrationId', models.TextField(null=True, verbose_name='senderIdRegistrationNo')),
                ('senderIdStatus', models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'sms_id',
            },
        ),
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=50, verbose_name='eventName')),
                ('defaultSMSContent', models.TextField(verbose_name='defaultSMSContent')),
                ('defaultNotificationContent', models.TextField(verbose_name='defaultNotificationContent')),
            ],
            options={
                'db_table': 'sms_event',
            },
        ),
        migrations.CreateModel(
            name='SMSEventSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationMappedContent', models.TextField(null=True, verbose_name='notificationMappedContent')),
                ('receiverType', models.CharField(choices=[('All Students', 'All Students'), ('Only Absent Students', 'Only Absent Students')], max_length=20, null=True, verbose_name='receiverType')),
                ('parentSMSEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSEvent', verbose_name='parentSMSEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='createdDate')),
                ('templateId', models.TextField(verbose_name='templateId')),
                ('templateName', models.TextField(verbose_name='templateName')),
                ('rawContent', models.TextField(verbose_name='rawContent')),
                ('communicationType', models.CharField(choices=[('SERVICE IMPLICIT', 'SERVICE IMPLICIT'), ('SERVICE EXPLICIT', 'SERVICE EXPLICIT'), ('PROMOTIONAL', 'PROMOTIONAL')], max_length=20, verbose_name='communicationType')),
                ('mappedContent', models.TextField(null=True, verbose_name='mappedContent')),
                ('registrationStatus', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
                ('parentSenderId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SenderId', verbose_name='parentSenderId')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSTemplate', verbose_name='parentSMSTemplate'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSentUpdateType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='information_app.SentUpdateType', verbose_name='parentSentUpdateType'),
        ),
        migrations.AddField(
            model_name='sms',
            name='parentSMSEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sms_app.SMSEvent'),
        ),
        migrations.RunPython(populate_sms_events),
        migrations.RunPython(populate_sender_id),
        migrations.RunPython(populate_sms_event_settings),
        migrations.RunPython(populate_sms_templates),
    ]
