# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from sms_app.db_script.populate_sms_event_settings import populate_sms_event_settings
from sms_app.db_script.populate_sms_events import populate_sms_events
from sms_app.db_script.populate_sms_id import populate_sms_id
from sms_app.db_script.populate_sms_templates import populate_sms_templates


class Migration(migrations.Migration):
    dependencies = [
        ('information_app', '0005_auto_20210510_1537'),
        ('sms_app', '0005_sms_parentmessagetype'),
        ('homework_app', '0001_initial'),
        ('tutorial_app', '0002_tutorialsettings'),
        ('attendance_app', '0010_attendancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=50, verbose_name='eventName')),
                ('defaultSMSContent', models.TextField(verbose_name='defaultSMSContent')),
                ('defaultNotificationContent', models.TextField(verbose_name='defaultNotificationContent')),
            ],
            options={
                'db_table': 'sms_event',
            },
        ),
        migrations.CreateModel(
            name='SMSEventSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customNotificationContent', models.TextField(null=True, verbose_name='customNotificationContent')),
                ('receiverType', models.CharField(
                    choices=[('All Students', 'All Students'), ('Only Absent Students', 'Only Absent Students')],
                    max_length=20, null=True, verbose_name='receiverType')),
                ('parentSMSEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSEvent',
                                                     verbose_name='parentSMSEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SMSId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.TextField(verbose_name='entityName')),
                ('entityRegistrationId', models.TextField(verbose_name='entityRegistrationId')),
                ('smsId', models.CharField(max_length=10, verbose_name='smsId')),
                ('smsIdRegistrationNumber', models.TextField(null=True, verbose_name='SMSIdRegistrationNumber')),
                ('smsIdStatus',
                 models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('PENDING', 'PENDING')], default='PENDING',
                                  max_length=15)),
            ],
            options={
                'db_table': 'sms_id',
            },
        ),
        migrations.CreateModel(
            name='SMSIdSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSMSId',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSId',
                                   verbose_name='parentSMSId')),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School',
                                                   verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'smsid_school',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='createdDate')),
                ('templateId', models.TextField(verbose_name='templateId')),
                ('templateName', models.TextField(verbose_name='templateName')),
                ('rawContent', models.TextField(verbose_name='rawContent')),
                ('communicationType', models.CharField(
                    choices=[('SERVICE IMPLICIT', 'SERVICE IMPLICIT'), ('SERVICE EXPLICIT', 'SERVICE EXPLICIT'),
                             ('TRANSACTIONAL', 'TRANSACTIONAL')], max_length=20, verbose_name='communicationType')),
                ('mappedContent', models.TextField(null=True, blank=True, verbose_name='mappedContent')),
                ('registrationStatus',
                 models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING',
                                  max_length=15)),
                ('parentSMSId',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSId',
                                   verbose_name='parentSenderId')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
        migrations.AddField(
            model_name='sms',
            name='mobileNumberContentJson',
            field=models.TextField(default='', verbose_name='contentMobileNumberJson'),
        ),
        migrations.AddField(
            model_name='sms',
            name='remark',
            field=models.TextField(default='SUCCESS', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='sms',
            name='sentStatus',
            field=models.BooleanField(default=True, verbose_name='sentStatus'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='information_app.MessageType'),
        ),
        migrations.AlterUniqueTogether(
            name='smsid',
            unique_together=set([('smsId', 'entityRegistrationId')]),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(null=True, default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='sms_app.SMSTemplate',
                                    verbose_name='parentSMSTemplate'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School',
                                    verbose_name='parentSchool'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSentUpdateType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='information_app.SentUpdateType', verbose_name='parentSentUpdateType'),
        ),
        migrations.AddField(
            model_name='sms',
            name='parentSMSEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sms_app.SMSEvent'),
        ),
        migrations.AddField(
            model_name='sms',
            name='smsId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sms_app.SMSId',
                                    verbose_name='smsId'),
        ),
        migrations.RunPython(populate_sms_events),
        migrations.RunPython(populate_sms_id),
        migrations.RunPython(populate_sms_event_settings),
        migrations.RunPython(populate_sms_templates),
    ]
