# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-28 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_sms_parentmessagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='smspurchase',
            name='orderId',
            field=models.IntegerField(default=-1, verbose_name='orderId'),
        ),
        migrations.AddField(
            model_name='smspurchase',
            name='payment_capture',
            field=models.BooleanField(default=False, verbose_name='payment_capture'),
        ),
    ]
