# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from sms_app.db_script.populate_sms_event_settings import populate_sms_event_settings
from sms_app.db_script.populate_sms_events import populate_sms_events
from sms_app.db_script.populate_sms_id import populate_sms_id
from sms_app.db_script.populate_sms_templates import populate_sms_templates


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_sms_parentmessagetype'),
        ('homework_app', '0001_initial'),
        ('tutorial_app', '0002_tutorialsettings'),
        ('attendance_app', '0010_attendancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=50, verbose_name='eventName')),
                ('defaultSMSContent', models.TextField(verbose_name='defaultSMSContent')),
                ('defaultNotificationContent', models.TextField(verbose_name='defaultNotificationContent')),
            ],
            options={
                'db_table': 'sms_event',
            },
        ),
        migrations.CreateModel(
            name='SMSEventSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonEventConditions', models.TextField(null=True, verbose_name='jsonEventConditions')),
                ('parentSMSEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSEvent', verbose_name='parentSMSEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SMSId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsId', models.CharField(max_length=10, verbose_name='smsId')),
                ('registrationNumber', models.TextField(null=True, verbose_name='registrationNumber')),
                ('smsIdStatus', models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('PENDING', 'PENDING'), ('NOT REGISTERED', 'NOT REGISTERED')], default='NOT REGISTERED', max_length=15)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'sms_id',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='createdDate')),
                ('smsTemplateId', models.TextField(verbose_name='smsTemplateId')),
                ('smsTemplateName', models.TextField(verbose_name='smsTemplateName')),
                ('smsRawContent', models.TextField(verbose_name='smsRawContent')),
                ('smsMappedContent', models.TextField(null=True, verbose_name='smsMappedContent')),
                ('registrationStatus', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
                ('parentSMSId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSId', verbose_name='parentSMSId')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSMSTemplate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sms_app.SMSTemplate', verbose_name='parentSMSTemplate'),
        ),
        migrations.AddField(
            model_name='smseventsettings',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.RunPython(populate_sms_events),
        migrations.RunPython(populate_sms_id),
        migrations.RunPython(populate_sms_event_settings),
        migrations.RunPython(populate_sms_templates),
    ]
