# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20201228_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspurchase',
            name='orderId',
            field=models.CharField(max_length=200, null=True, verbose_name='orderId'),
        ),
    ]
