# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20210421_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='smsId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sms_app.SMSId', verbose_name='smsId'),
        ),
    ]
