# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20210616_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='fetchedDeliveryStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sms',
            name='smsGateWayHubVendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sms',
            name='contentType',
            field=models.TextField(default='', verbose_name='contentType(DCS)'),
        ),
        migrations.AlterField(
            model_name='smsdeliveryreport',
            name='statusCode',
            field=models.TextField(null=True, verbose_name='statusCode'),
        ),
    ]
