# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_sms_smsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='mobileNumberContentJson',
            field=models.TextField(default='', verbose_name='contentMobileNumberJson'),
        ),
    ]
