# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('sms_app', '0007_auto_20201228_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smspurchase',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='smspurchase',
            name='payment_capture',
        ),
        migrations.AddField(
            model_name='smspurchase',
            name='parentOrder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payment_app.Order'),
            preserve_default=False,
        ),
    ]
