# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_sms_mobilenumbercontentjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sentStatus',
            field=models.BooleanField(default=True, verbose_name='sentStatus'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='information_app.MessageType'),
        ),
    ]
