# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event_gallery_app.models
from event_gallery_app.db_script.add_event_gallery_module import add_event_gallery_module


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('team_app', '0017_auto_20210107_1319')
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.TextField(default='', verbose_name='eventTitle')),
                ('eventDescription', models.TextField(blank=True, null=True, verbose_name='eventDescription')),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('notifyEmployees', models.BooleanField(default=False, verbose_name='notifyEmployees')),
                ('notifyTeachers', models.BooleanField(default=False, verbose_name='notifyTeachers')),
                ('notifyClass1', models.BooleanField(default=False, verbose_name='notifyClass1')),
                ('notifyClass2', models.BooleanField(default=False, verbose_name='notifyClass2')),
                ('notifyClass3', models.BooleanField(default=False, verbose_name='notifyClass3')),
                ('notifyClass4', models.BooleanField(default=False, verbose_name='notifyClass4')),
                ('notifyClass5', models.BooleanField(default=False, verbose_name='notifyClass5')),
                ('notifyClass6', models.BooleanField(default=False, verbose_name='notifyClass6')),
                ('notifyClass7', models.BooleanField(default=False, verbose_name='notifyClass7')),
                ('notifyClass8', models.BooleanField(default=False, verbose_name='notifyClass8')),
                ('notifyClass9', models.BooleanField(default=False, verbose_name='notifyClass9')),
                ('notifyClass10', models.BooleanField(default=False, verbose_name='notifyClass10')),
                ('notifyClass11', models.BooleanField(default=False, verbose_name='notifyClass11')),
                ('notifyClass12', models.BooleanField(default=False, verbose_name='notifyClass12')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField(default='', verbose_name='tagName')),
                ('parentEvent',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.Event',
                                   verbose_name='parentEvent')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventImage', models.ImageField(blank=True, null=True, upload_to=event_gallery_app.models.upload_event_images_to, verbose_name='event_image')),
                ('orderNumber', models.IntegerField(default=0, verbose_name='orderNumber')),
                ('parentEvent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.Event', verbose_name='parentEvent')),
                ('tags', models.ManyToManyField(to='event_gallery_app.EventTag'))
            ],
            options={
                'db_table': 'event_images',
            },
        ),
        migrations.RunPython(add_event_gallery_module)
    ]
