# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event_gallery_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='eventTitle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='eventDescription')),
                ('heldOn', models.DateField(null=True, verbose_name='heldOn')),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('notifyEmployees', models.BooleanField(default=False, verbose_name='notifyEmployees')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventImage', models.ImageField(blank=True, null=True, upload_to=event_gallery_app.models.upload_event_images_to, verbose_name='event_image')),
                ('imageSize', models.TextField(blank=True, null=True, verbose_name='imageSize')),
                ('parentEvent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.Event', verbose_name='parentEvent')),
            ],
            options={
                'db_table': 'event_images',
            },
        ),
        migrations.CreateModel(
            name='EventImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentEventImage', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.EventImage', verbose_name='parentEventImage')),
            ],
            options={
                'db_table': 'event_image_tags',
            },
        ),
        migrations.CreateModel(
            name='EventNotifyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.Class', verbose_name='parentClass')),
                ('parentEvent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.Event', verbose_name='parentEvent')),
            ],
            options={
                'db_table': 'event_notify_class',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField(default='', verbose_name='tagName')),
                ('parentEvent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.Event', verbose_name='parentEvent')),
            ],
            options={
                'db_table': 'event_tag',
            },
        ),
        migrations.AddField(
            model_name='eventimagetags',
            name='parentEventTag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event_gallery_app.EventTag', verbose_name='parentEventTag'),
        ),
    ]
