# Generated by Django 3.2.5 on 2022-01-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_app', '0002_alter_employee_parentschool'),
        ('team_app', '0007_auto_20220126_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityDescription', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activityRecordList', to='employee_app.employee', verbose_name='parentEmployee')),
                ('parentTask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_app.task')),
            ],
            options={
                'db_table': 'activity_record',
            },
        ),
    ]
