# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models
from information_app.db_script.populate_sent_update_type import populate_sent_update_type


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentUpdateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RunPython(populate_sent_update_type),
    ]
