# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-30 09:30
from __future__ import unicode_literals

from django.db import migrations
from information_app.db_script.populate_attendance_type import populate_attendance_type

class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0003_auto_20210119_1324'),
    ]

    operations = [
        migrations.RunPython(populate_attendance_type),
    ]
