# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from examination_app.db_script.populate_maximumMarksAllowed_and_grade import populate_maximumMarksAllowed_and_grade
from examination_app.db_script.populate_test import populate_test

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0003_marksheet'),
        ('subject_app', '0001_initial'),
        ('school_app', '0020_auto_20180321_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximumMarks', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='maximumMarks')),
                ('minimumMarks', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='minimumMarks')),
                ('value', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='MaximumMarksAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(default=1, unique=True, verbose_name='marks')),
                ('orderNumber', models.IntegerField(default=0, verbose_name='marks')),
            ],
            options={
                'db_table': 'maximum_marks_allowed',
                'ordering': ['orderNumber'],
            },
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksObtained', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='marksObtained')),
                ('absent', models.BooleanField(default=False, verbose_name='absent')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_test_result',
                'ordering': ['parentTest__parentSubject__orderNumber'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentMaximumMarks', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.MaximumMarksAllowed', verbose_name='parentMaximumMarks')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentSection', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Section', verbose_name='parentSection')),
                ('parentSubject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.Subject', verbose_name='parentSubject')),
            ],
            options={
                'db_table': 'test',
                'ordering': ['parentSubject__orderNumber'],
            },
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='parentTest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.Test', verbose_name='parentTest'),
        ),
        migrations.AddField(
            model_name='grade',
            name='parentMaximumMarksAllowed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.MaximumMarksAllowed', verbose_name='parentMaximumMarksAllowed'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([('parentSchool', 'parentSection', 'parentSubject')]),
        ),
        migrations.AlterUniqueTogether(
            name='studenttestresult',
            unique_together=set([('parentStudent', 'parentTest')]),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set([('parentMaximumMarksAllowed', 'maximumMarks', 'minimumMarks')]),
        ),
        migrations.RunPython(populate_maximumMarksAllowed_and_grade),
        migrations.RunPython(populate_test),
    ]
