# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestresult',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent'),
        ),
    ]
