# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 04:19
from __future__ import unicode_literals

from django.db import migrations

from examination_app.db_script.change_sbs_test_structure_two import change_sbs_test_structure

class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0003_auto_20180412_1613'),
    ]

    operations = [
        migrations.RunPython(change_sbs_test_structure),
    ]
