# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from examination_app.db_script.refactor_test import refactor_test


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_division'),
        ('subject_app', '0001_initial'),
        ('school_app', '0032_school_headersize'),
        ('examination_app', '0004_auto_20180415_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='parentClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass'),
        ),
        migrations.AddField(
            model_name='test',
            name='parentDivision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision'),
        ),
        migrations.AddField(
            model_name='test',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.RunPython(refactor_test),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([('parentSchool', 'parentClass', 'parentDivision', 'parentSession', 'parentSubject')]),
        ),
        migrations.RemoveField(
            model_name='test',
            name='parentSection',
        ),
    ]
