# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0006_merge_20181125_1213'),
        ('examination_app', '0005_auto_20181112_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='-', verbose_name='name')),
            ],
            options={
                'db_table': 'examination',
            },
        ),
        migrations.CreateModel(
            name='TestSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='startTime')),
                ('endTime', models.DateTimeField(verbose_name='endTime')),
                ('testType', models.CharField(choices=[('Oral', 'Oral'), ('Written', 'Written'), ('Theory', 'Theory'), ('Practical', 'Practical')], default=None, max_length=10, null=True, verbose_name='testType')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass')),
                ('parentDivision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision')),
                ('parentExamination', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.Examination', verbose_name='parentExamination')),
            ],
            options={
                'db_table': 'test_second',
            },
        ),
    ]
