# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from examination_app.db_script.intialize_student_test import initialize_test
from examination_app.db_script.access_update_marks import access_update_marks
from examination_app.db_script.access_print_marksheet import access_print_marksheet


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0003_auto_20181221_2208'),
        ('student_app', '0015_auto_20181111_2134'),
        ('examination_app', '0007_auto_20181201_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testType', models.CharField(choices=[('Oral', 'Oral'), ('Written', 'Written'), ('Theory', 'Theory'), ('Practical', 'Practical')], default=None, max_length=10, null=True, verbose_name='testType')),
                ('marksObtained', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='marksObtained')),
                ('parentExamination', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='examination_app.Examination', verbose_name='parentExamination')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
                ('parentSubject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='subject_app.SubjectSecond', verbose_name='parentSubject')),
            ],
            options={
                'db_table': 'student_test',
            },
        ),
        migrations.AddField(
            model_name='testsecond',
            name='maximumMarks',
            field=models.PositiveIntegerField(default=100, verbose_name='maximumMarks'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttest',
            unique_together=set([('parentExamination', 'parentSubject', 'parentStudent', 'testType')]),
        ),
        migrations.RunPython(initialize_test),
        migrations.RunPython(access_update_marks),
        migrations.RunPython(access_print_marksheet),
    ]
