# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-16 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from examination_app.db_script.access_update_cce_marks import access_update_cce_marks


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0035_school_opacity'),
        ('student_app', '0020_auto_20190203_2339'),
        ('examination_app', '0010_auto_20190222_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCEMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksObtained', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='marksObtained')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'cce_marks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ccemarks',
            unique_together=set([('parentStudent', 'parentSession')]),
        ),
        migrations.RunPython(access_update_cce_marks),
    ]
