# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0016_auto_20201112_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='marksObtained',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='marksObtained'),
        ),
    ]
