# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_app', '0019_studenttest_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='marksObtained',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='marksObtained'),
        ),
    ]
