# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 05:01
from __future__ import unicode_literals

from django.db import migrations

from user_app.db_script.create_user import create_user


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20181220_1131'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
