# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import employee_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadharNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobileNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeparametervalue',
            name='document_value',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=employee_app.models.upload_document_to),
        ),
    ]
