# Generated by Django 3.2.5 on 2022-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_parentschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isNonSalariedEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
