# Generated by Django 3.2.5 on 2023-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employee_isnonsalariedemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='panNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
