# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0012_auto_20200409_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='configJSON',
            field=models.TextField(default='{}'),
        ),
    ]
