# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import employee_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
        ('employee_app', '0013_employeepermission_configjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameterType', models.CharField(choices=[('TEXT', 'TEXT'), ('FILTER', 'FILTER'), ('DOCUMENT', 'DOCUMENT')], max_length=20)),
                ('filterValues', models.TextField(blank=True, null=True)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'employee_parameter',
            },
        ),
        migrations.CreateModel(
            name='EmployeeParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('document_value', models.FileField(blank=True, null=True, upload_to=employee_app.models.upload_document_to)),
                ('document_size', models.TextField(blank=True, null=True)),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee', verbose_name='parentEmployee')),
                ('parentEmployeeParameter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_app.EmployeeParameter', verbose_name='parentEmployeeParameter')),
            ],
            options={
                'db_table': 'employee_parameter_value',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeeparametervalue',
            unique_together=set([('parentEmployee', 'parentEmployeeParameter')]),
        ),
    ]
