# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_app', '0001_initial'),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('sentDateTime', models.DateTimeField(auto_now_add=True, verbose_name='sentDateTime')),
                ('parentMessageType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='information_app.MessageType')),
                ('parentSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
