# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_auto_20210503_1446'),
        ('notification_app', '0002_notification_parentmessagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parentSMSEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.SMSEvent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_app.MessageType'),
        ),
    ]
