# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_notification_parentmessagetype'),
        ('sms_app', '0006_auto_20210616_1911')
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='SMSEventId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_app.MessageType'),
        ),
    ]
