# Generated by Django 3.2.5 on 2021-08-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_notification_parentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='SMSEventId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='parentMessageType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_app.messagetype'),
        ),
    ]
