# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 08:51
from __future__ import unicode_literals

from vehicle_app.db_script.access_vehicle_app import access_vehicle_app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0026_remove_school_user'),
    ]

    operations = [
        migrations.RunPython(access_vehicle_app),
    ]
