export const STUDENT_LIST = [
    {
        name : 'Student 1',
        fathersName : 'Father',
        class : {
            name : 'Class 12'
        },
        section : {
            name : 'Section A'
        },
        mobileNumber : '1234567891',
        secondMobileNumber : '7418529637',
        feesDueTillMonth : 5000,
        feesDueOverall : 6000,
        totalFeesThisSession : 8000,
        feesPaidThisSession : 4000,
        discountThisSession : 1000
    },
    {
        id : 1,
        name : 'Mahima Surana',
        fathersName:  'Sunil Surana',
        mobileNumber: '9874852136',
        scholarNumber : '139',
        totalFees : '0',
        dateOfBirth : '2009-09-18',
        remark : '',
        motherName : 'Mamta Surana',
        gender : 'Female',
        caste : 'Surana',
        newCategoryField : 'ST',
        newReligionFeild : 'Hinduism',
        fatherOccupation : '',
        address : '',
        familySSMID : '',
        childSSMID : '',
        bankName : '',
        bankAccountNum : '',
        aadharNum : '777444446447',
        bloodGroup : 'AB -',
        fatherAnnualIncome : '',
        currentBusStop : '828',
        admissionSession : '3',
        parentSchool : '2',
        parentTransferCertificate : '',
        profileImage : '',
        dateOfAdmission : '2019-05-19',
        bankIfscCode : '',
        secondMobileNumber:  '0',
        rte : ''
    },
    {
        id : 2,
        name : 'Manoj Kushwah',
        fathersName:  'Raju Kushwah',
        mobileNumber: '9874852136',
        scholarNumber : '103',
        totalFees : '0',
        dateOfBirth : '1993-11-15',
        remark : '',
        motherName : 'Radha Kushwah',
        gender : 'Male',
        caste : 'Kushwah',
        newCategoryField : 'ST',
        newReligionFeild : 'Hinduism',
        fatherOccupation : '',
        address : '',
        familySSMID : '',
        childSSMID : '',
        bankName : 'SBI',
        bankAccountNum : '',
        aadharNum : '',
        bloodGroup : 'A -',
        fatherAnnualIncome : '',
        currentBusStop : '828',
        admissionSession : '2',
        parentSchool : '2',
        parentTransferCertificate : '',
        profileImage : '',
        dateOfAdmission : '2018-04-18',
        bankIfscCode : '',
        secondMobileNumber:  '0',
        rte : ''
    },
];
