# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 12:42
from __future__ import unicode_literals

from django.db import migrations

from enquiry_app.db_script.access_enquiry_app import access_enquiry_app


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(access_enquiry_app),
    ]
