# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_auto_20190603_0957'),
        ('enquiry_app', '0002_auto_20180526_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee'),
        ),
    ]
