# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 21:29
from __future__ import unicode_literals

from django.db import migrations


from employee_app.db_script.access_employee_app import access_employee_app

class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(access_employee_app),
    ]
