# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0031_school_medium'),
        ('employee_app', '0003_auto_20180918_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSessionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidLeaveNumber', models.IntegerField(null=True, verbose_name='paidLeaveNumber')),
            ],
            options={
                'db_table': 'employee_session_detail',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='monthlySalary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeesessiondetail',
            name='parentEmployee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.AddField(
            model_name='employeesessiondetail',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesessiondetail',
            unique_together=set([('parentEmployee', 'parentSession')]),
        ),
    ]
