# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-04 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_auto_20180929_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dateOfLeaving',
            field=models.DateField(null=True),
        ),
    ]
