# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_employee_spousename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pranNumber',
            field=models.TextField(null=True),
        ),
    ]
