# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-03 04:27
from __future__ import unicode_literals

from django.db import migrations


from employee_app.db_script.employee_experience_certi import employee_experience_certi


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_auto_20190413_2136'),
    ]

    operations = [
        migrations.RunPython(employee_experience_certi),
    ]
