# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0002_auto_20180406_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('remark', models.TextField()),
                ('generationDateTime', models.DateField(auto_now_add=True)),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student')),
            ],
            options={
                'db_table': 'concession',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('remark', models.TextField()),
                ('generationDateTime', models.DateField()),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student')),
            ],
            options={
                'db_table': 'fee',
            },
        ),
        migrations.CreateModel(
            name='SubFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('parentFee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='fee_app.Fee')),
            ],
            options={
                'db_table': 'sub_fee',
            },
        ),
    ]
