# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concession',
            name='parentStudent',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='parentStudent',
        ),
        migrations.RemoveField(
            model_name='subfee',
            name='parentFee',
        ),
        migrations.DeleteModel(
            name='Concession',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='SubFee',
        ),
    ]
