# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0039_auto_20200104_2202'),
        ('student_app', '0024_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='StudentSubGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeObtained', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_sub_grade',
            },
        ),
        migrations.CreateModel(
            name='SubGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.Grade')),
            ],
            options={
                'db_table': 'sub_grade',
            },
        ),
        migrations.AddField(
            model_name='studentsubgrade',
            name='parentSubGrade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.SubGrade', verbose_name='parentSubGrade'),
        ),
    ]
