# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0025_auto_20180429_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'access',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='parentUser')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default='', unique=True, verbose_name='path')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('icon', models.TextField(default='', verbose_name='icon')),
                ('orderNumber', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default='', verbose_name='path')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('orderNumber', models.IntegerField(default=1)),
                ('parentModule', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='team_app.Module', verbose_name='parentModule')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='parentTask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='team_app.Task', verbose_name='parentTask'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parentUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='parentUser'),
        ),
        migrations.AddField(
            model_name='access',
            name='parentModule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='team_app.Module', verbose_name='parentModule'),
        ),
        migrations.AddField(
            model_name='access',
            name='parentSchool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('parentModule', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('parentUser', 'parentTask', 'parentSchool')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('parentUser', 'parentSchool')]),
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set([('parentSchool', 'parentModule')]),
        ),
    ]
