# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 10:04
from __future__ import unicode_literals

from django.db import migrations


from team_app.db_script.populate_team_app import populate_team_app
from team_app.db_script.delete_schools import delete_schools


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_schools),
        migrations.RunPython(populate_team_app),
    ]
