# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 10:05
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.remove_team_app_from_school_and_employee import remove_team_app_access_from_school_and_employee

class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_auto_20180522_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='member',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parentUser',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parentSchool',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parentTask',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parentUser',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RunPython(remove_team_app_access_from_school_and_employee),
    ]
