# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-15 13:58
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.change_name import changeName


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_auto_20191130_2039'),
    ]

    operations = [
        migrations.RunPython(changeName),
    ]
