# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-16 06:50
from __future__ import unicode_literals

from django.db import migrations
from team_app.db_script.add_schedule_test_to_examination import add_schedule_test_to_examination


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0017_auto_20210107_1319'),
    ]

    operations = [
         migrations.RunPython(add_schedule_test_to_examination)
    ]
