# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-18 11:26
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.add_event_gallery_module import add_event_gallery_module


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0021_auto_20210225_1550'),
    ]

    operations = [
        migrations.RunPython(add_event_gallery_module)
    ]
