# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-20 04:48
from __future__ import unicode_literals

from django.db import migrations
from accounts_app.db_script.rename_my_approval_requests import rename_my_approval_requests
from fees_third_app.db_script.rename_lock_fees import rename_lock_fees


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0024_auto_20210413_1133'),
    ]

    operations = [
        migrations.RunPython(rename_my_approval_requests),
        migrations.RunPython(rename_lock_fees),
    ]
