# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-07 12:35
from __future__ import unicode_literals

from django.db import migrations

from team_app.db_script.rename_online_class import rename_online_class


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0030_auto_20210213_1210'),
    ]

    operations = [
        migrations.RunPython(rename_online_class)
    ]
