# Generated by Django 3.2.5 on 2022-11-14 04:06

from django.db import migrations, models
from feature_flag_app.db_script.add_backtrack_feature_flag import add_backtrack_feature_flag


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
            ],
            options={
                'db_table': 'feature_flag',
            },
        ),
        migrations.RunPython(add_backtrack_feature_flag),
    ]
