# Generated by Django 3.2.5 on 2022-12-14 09:48

from django.db import migrations
from feature_flag_app.db_script.add_updateViaExcel_feature_flag import add_updateViaExcel_feature_flag


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_updateViaExcel_feature_flag),
    ]
