# Generated by Django 3.2.5 on 2023-02-25 10:24

from django.db import migrations
from feature_flag_app.db_script.add_library_flag import add_library_feature_flag

class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0004_auto_20230220_1626'),
    ]

    operations = [
        migrations.RunPython(add_library_feature_flag)
    ]
