# Generated by Django 3.2.5 on 2023-03-01 08:21
from django.db import migrations
from feature_flag_app.db_script.add_leaves_feature_flag import add_leaves_feature_flag

class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0004_auto_20230220_1626'),
    ]

    operations = [
        migrations.RunPython(add_leaves_feature_flag)
    ]

