# Generated by Django 3.2.5 on 2023-03-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0005_auto_20230225_1554'),
        ('feature_flag_app', '0005_auto_20230301_1351'),
    ]

    operations = [
    ]
