# Generated by Django 3.2.5 on 2023-03-30 16:13

from django.db import migrations
from feature_flag_app.db_script.add_school_website_feature_flag import add_school_website_feature_flag



class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0007_auto_20230312_1459'),
    ]

    operations = [
        migrations.RunPython(add_school_website_feature_flag)
    ]

