# Generated by Django 3.2.5 on 2023-09-01 08:55

from django.db import migrations
from feature_flag_app.db_script.add_library_phase_2_feature_flag import add_library_phase_2_feature_flag


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flag_app', '0008_auto_20230330_2143'),
    ]

    operations = [
        migrations.RunPython(add_library_phase_2_feature_flag)
    ]
