# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from fee_second_app.db_script.add_my_collection_task import add_my_collection_task

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fee_second_app', '0002_auto_20180426_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionsecond',
            name='parentReceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='parentReceiver'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='parentReceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='parentReceiver'),
        ),
        migrations.RunPython(add_my_collection_task),
    ]
