# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import report_card_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=report_card_app.models.upload_image_assets_to)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardLayoutNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to=report_card_app.models.upload_thumbnail_to)),
                ('publiclyShared', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.AddField(
            model_name='layoutsharing',
            name='parentLayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_card_app.ReportCardLayoutNew'),
        ),
        migrations.AddField(
            model_name='layoutsharing',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcardlayoutnew',
            unique_together=set([('parentSchool', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='layoutsharing',
            unique_together=set([('parentSchool', 'parentLayout')]),
        ),
    ]
