# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-22 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_app', '0001_initial'),
    ]

    operations = [
    ]
