# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('report_card_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_cards/imageAssets')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardLayoutNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
        migrations.AddField(
            model_name='imageassets',
            name='parentLayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_card_app.ReportCardLayoutNew'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcardlayoutnew',
            unique_together=set([('parentSchool', 'name')]),
        ),
    ]
