# Generated by Django 3.2.5 on 2022-02-03 14:29

from django.db import migrations
from report_card_app.db_script.custom_resolution_name_patch import customNameFix

class Migration(migrations.Migration):

    dependencies = [
        ('report_card_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(customNameFix),
    ]
