# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import report_card_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_app', '0002_auto_20210222_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageassets',
            name='image',
            field=models.ImageField(upload_to=report_card_app.models.upload_image_assets_to),
        ),
        migrations.AlterField(
            model_name='reportcardlayoutnew',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=report_card_app.models.upload_thumbnail_to),
        ),
    ]
