# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('report_card_app', '0002_auto_20201221_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='reportcardlayoutnew',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layoutaccess',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_card_app.ReportCardLayoutNew'),
        ),
        migrations.AddField(
            model_name='layoutaccess',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.AlterUniqueTogether(
            name='layoutaccess',
            unique_together=set([('school', 'layout')]),
        ),
    ]
