# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0041_auto_20201202_2027'),
        ('report_card_app', '0003_auto_20210121_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayoutAccess',
            new_name='LayoutSharing',
        ),
        migrations.RenameField(
            model_name='layoutsharing',
            old_name='layout',
            new_name='parentLayout',
        ),
        migrations.RenameField(
            model_name='layoutsharing',
            old_name='school',
            new_name='parentSchool',
        ),
        migrations.AddField(
            model_name='reportcardlayoutnew',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='report_cards/layout_thumbnails'),
        ),
        migrations.AlterUniqueTogether(
            name='layoutsharing',
            unique_together=set([('parentSchool', 'parentLayout')]),
        ),
    ]
