# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-24 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card_app', '0004_auto_20210124_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcardlayoutnew',
            old_name='public',
            new_name='publiclyShared',
        ),
    ]
