# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0023_auto_20180406_1443'),
        ('student_app', '0002_auto_20180406_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currentBusStop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.BusStop', verbose_name='current_bus_stop'),
        ),
    ]
