# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_currentbusstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rte',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True),
        ),
    ]
