# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 03:57
from __future__ import unicode_literals

from django.db import migrations

from student_app.db_script.adding_i_card_page import adding_i_card_page


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_student_profileimage'),
    ]

    operations = [
        migrations.RunPython(adding_i_card_page),
    ]
