# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_auto_20190101_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bankIfscCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
