# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from student_app.db_script.delete_student import delete_student


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0023_auto_20190606_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent'),
        ),
        migrations.RunPython(delete_student),
    ]
