# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0028_auto_20210105_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
