# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0030_auto_20210115_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
    ]
