# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0032_student_parentadmissionclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fatherOccupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
