# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubgrade',
            name='gradeObtained',
            field=models.TextField(blank=True, verbose_name='gradeObtained'),
        ),
    ]
