# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-08 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feature_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=feature_app.models.upload_avatar_to, verbose_name='Avatar')),
                ('title', models.TextField()),
                ('why', models.TextField()),
                ('how', models.TextField(null=True)),
                ('what', models.TextField()),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='parentUser')),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='FeaturePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=feature_app.models.upload_avatar_to, verbose_name='Avatar')),
                ('parentFeature', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feature_app.Feature', verbose_name='parentFeature')),
            ],
            options={
                'db_table': 'feature_photo',
            },
        ),
    ]
