export const SUB_FEE_RECEIPT_LIST = [
    {
        id : '25123',
        isAnnually : '1',
        aprilAmount : '0',
        aprilLateFee : '',
        mayAmount : '',
        mayLateFee : '',
        juneAmount : '',
        juneLateFee : '',
        julyAmount : '',
        julyLateFee : '',
        augustAmount : '',
        augustLateFee : '',
        septemberAmount : '',
        septemberLateFee : '',
        octoberAmount : '',
        octoberLateFee : '',
        novemberAmount : '',
        novemberLateFee : '',
        decemberAmount : '',
        decemberLateFee : '',
        januaryAmount : '',
        januaryLateFee : '',
        februaryAmount : '',
        februaryLateFee : '',
        marchAmount : '',
        marchLateFee : '',
        parentFeeReceipt : '16670',
        parentFeeType : '99',
        parentSession : '3',
        parentStudentFee : '1'
    }
];
