# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0024_auto_20190901_1142'),
        ('class_app', '0007_auto_20191130_2039'),
        ('examination_app', '0014_auto_20200107_0516'),
        ('grade_app', '0001_initial'),
        ('school_app', '0039_auto_20200104_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_app.Class', verbose_name='parentClass')),
            ],
            options={
                'db_table': 'class_layout',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('reportCardHeading', models.TextField(default='', null=True, blank=True, verbose_name='reportCardHeading')),
                ('showLetterHeadImage', models.BooleanField(default=False, verbose_name='showLetterHeadImage')),
                ('attendanceStartDate', models.DateField(null=True, verbose_name='attendanceStartDate')),
                ('attendanceEndDate', models.DateField(null=True, verbose_name='attendanceEndDate')),
                ('decimalPlaces', models.IntegerField(default=0, null=True, verbose_name='decimalPlaces')),
                ('passingPercentage', models.IntegerField(default=33, null=True, verbose_name='passingPercentage')),
                ('studentNameOrderNumber', models.IntegerField(default=0, null=True, verbose_name='studentNameOrderNumber')),
                ('fatherNameOrderNumber', models.IntegerField(default=0, null=True, verbose_name='fatherNameOrderNumber')),
                ('motherNameOrderNumber', models.IntegerField(default=0, null=True, verbose_name='motherNameOrderNumber')),
                ('rollNoOrderNumber', models.IntegerField(default=0, null=True, verbose_name='rollNoOrderNumber')),
                ('scholarNoOrderNumber', models.IntegerField(default=0, null=True, verbose_name='scholarNoOrderNumber')),
                ('dateOfBirthOrderNumber', models.IntegerField(default=0, null=True, verbose_name='dateOfBirthOrderNumber')),
                ('dateOfBirthInWordsOrderNumber', models.IntegerField(default=0, null=True, verbose_name='dateOfBirthInWordsOrderNumber')),
                ('aadharNumberOrderNumber', models.IntegerField(default=0, null=True, verbose_name='aadharNumberOrderNumber')),
                ('categoryOrderNumber', models.IntegerField(default=0, null=True, verbose_name='categoryOrderNumber')),
                ('familySSMIDOrderNumber', models.IntegerField(default=0, null=True, verbose_name='familySSMIDOrderNumber')),
                ('childSSMIDOrderNumber', models.IntegerField(default=0, null=True, verbose_name='childSSMIDOrderNumber')),
                ('classOrderNumber', models.IntegerField(default=0, null=True, verbose_name='classOrderNumber')),
                ('sectionOrderNumber', models.IntegerField(default=0, null=True, verbose_name='sectionOrderNumber')),
                ('casteOrderNumber', models.IntegerField(default=0, null=True, verbose_name='casteOrderNumber')),
                ('classAndSectionOrderNumber', models.IntegerField(default=0, null=True, verbose_name='classAndSectionOrderNumber')),
                ('addressOrderNumber', models.IntegerField(default=0, null=True, verbose_name='addressOrderNumber')),
                ('overallMarksOrderNumber', models.IntegerField(default=0, null=True, verbose_name='overallMarksOrderNumber')),
                ('attendanceOrderNumber', models.IntegerField(default=0, null=True, verbose_name='attendanceOrderNumber')),
                ('resultOrderNumber', models.IntegerField(default=0, null=True, verbose_name='resultOrderNumber')),
                ('percentageOrderNumber', models.IntegerField(default=0, null=True, verbose_name='percentageOrderNumber')),
                ('promotedToClassOrderNumber', models.IntegerField(default=0, null=True, verbose_name='promotedToClassOrderNumber')),
                ('remarksOrderNumber', models.IntegerField(default=0, null=True, verbose_name='remarksOrderNumber')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.School', verbose_name='parentSchool')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.Session', verbose_name='parentSession')),
            ],
            options={
                'db_table': 'layout',
            },
        ),
        migrations.CreateModel(
            name='LayoutExamColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('name', models.TextField()),
                ('maximumMarksObtainedOne', models.IntegerField(default=0, null=True)),
                ('maximumMarksObtainedTwo', models.IntegerField(default=0, null=True)),
                ('columnType', models.CharField(choices=[('Simple', 'Simple'), ('Oral/Written', 'Oral/Written'), ('Practical/Theory', 'Practical/Theory')], default='Simple', max_length=255, null=True)),
                ('parentExamination', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='examination_app.Examination', verbose_name='parentExamination')),
                ('parentLayout', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout')),
            ],
            options={
                'db_table': 'layout_exam_column',
            },
        ),
        migrations.CreateModel(
            name='LayoutGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('parentGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.Grade', verbose_name='parentGrade')),
                ('parentLayout', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout')),
            ],
            options={
                'db_table': 'layout_grade',
            },
        ),
        migrations.CreateModel(
            name='LayoutSubGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=0, null=True)),
                ('parentLayoutGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.LayoutGrade', verbose_name='parentLayoutGrade')),
                ('parentSubGrade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grade_app.SubGrade', verbose_name='parentSubGrade')),
            ],
            options={
                'db_table': 'layout_sub_grade',
            },
        ),
        migrations.CreateModel(
            name='StudentRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='-', verbose_name='remark')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_remarks',
            },
        ),
        migrations.AddField(
            model_name='classlayout',
            name='parentLayout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_reportcard.Layout', verbose_name='parentLayout'),
        ),
        migrations.AlterUniqueTogether(
            name='studentremarks',
            unique_together=set([('parentStudent', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='layoutsubgrade',
            unique_together=set([('parentLayoutGrade', 'parentSubGrade')]),
        ),
        migrations.AlterUniqueTogether(
            name='layoutgrade',
            unique_together=set([('parentLayout', 'parentGrade')]),
        ),
        migrations.AlterUniqueTogether(
            name='layoutexamcolumn',
            unique_together=set([('parentLayout', 'parentExamination')]),
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together=set([('name', 'parentSchool', 'parentSession')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlayout',
            unique_together=set([('parentLayout', 'parentClass')]),
        ),
    ]
