# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_app.db_script.populate_student_section


class Migration(migrations.Migration):

    # replaces = [('student_app', '0001_marksheet'), ('student_app', '0002_marksheet')]

    dependencies = [
        ('school_app', '0018_marksheet'),
        ('class_app', '0003_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.TextField(null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('parentSection', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Section', verbose_name='parentSection')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Student', verbose_name='parentStudent')),
            ],
            options={
                'db_table': 'student_section',
            },
        ),
        migrations.RunPython(
            code=student_app.db_script.populate_student_section.populate_student_section,
        ),
    ]
