# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0001_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathersName', models.CharField(max_length=100)),
                ('mobileNumber', models.IntegerField(null=True)),
                ('scholarNumber', models.TextField(null=True)),
                ('totalFees', models.IntegerField(default=0)),
                ('dateOfBirth', models.DateField(null=True)),
                ('remark', models.TextField(null=True)),
                ('motherName', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('caste', models.TextField(null=True)),
                ('newCategoryField', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Classes'), ('Gen.', 'General')], max_length=5, null=True)),
                ('newReligionField', models.CharField(choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Jainism', 'Jainism')], max_length=20, null=True)),
                ('fatherOccupation', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('familySSMID', models.IntegerField(null=True)),
                ('childSSMID', models.IntegerField(null=True)),
                ('bankName', models.TextField(null=True)),
                ('bankAccountNum', models.TextField(null=True)),
                ('aadharNum', models.IntegerField(null=True)),
                ('bloodGroup', models.TextField(null=True)),
                ('fatherAnnualIncome', models.TextField(null=True)),
                ('parentUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='parentStudent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='student_app.Student', verbose_name='parentStudent'),
        ),
    ]
