# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_student_parentschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parentUser',
        ),
    ]
