# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-06 07:55
from __future__ import unicode_literals

from django.db import migrations, models

from student_app.db_script.populate_date_of_admission import populate_date_of_admission


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_auto_20180807_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateOfAdmission',
            field=models.DateField(null=True, verbose_name='dateOfAdmission'),
        ),
        migrations.RunPython(populate_date_of_admission),
    ]
