# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-06 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0013_student_dateofadmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercertificate',
            name='admissionDate',
        ),
    ]
