# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from student_app.db_script.refactor_student_section import refactor_student_section


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0032_school_headersize'),
        ('class_app', '0004_division'),
        ('student_app', '0014_remove_transfercertificate_admissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='parentClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class', verbose_name='parentClass'),
        ),
        migrations.AddField(
            model_name='studentsection',
            name='parentDivision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Division', verbose_name='parentDivision'),
        ),
        migrations.AddField(
            model_name='studentsection',
            name='parentSession',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.RunPython(refactor_student_section),
        migrations.RemoveField(
            model_name='studentsection',
            name='parentSection',
        ),
        migrations.AlterUniqueTogether(
            name='studentsection',
            unique_together=set([('parentStudent', 'parentDivision', 'parentSession')]),
        ),
    ]
