# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-01 06:22
from __future__ import unicode_literals

from django.db import migrations

from student_app.db_script.add_update_all import add_update_all


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_auto_20181226_1235'),
    ]

    operations = [
        migrations.RunPython(add_update_all),
    ]
