# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0018_student_bankifsccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='secondMobileNumber',
            field=models.IntegerField(null=True),
        ),
    ]
