# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-29 07:12
from __future__ import unicode_literals

from django.db import migrations

from student_app.db_script.change_profile_image_url import change_profile_image_url


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0020_auto_20190203_2339'),
    ]

    operations = [
        migrations.RunPython(change_profile_image_url),
    ]
