# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import student_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0022_auto_20190410_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=student_app.models.upload_avatar_to, verbose_name='Avatar'),
        ),
    ]
