# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-30 17:01
from __future__ import unicode_literals

from django.db import migrations

from student_app.db_script.delete_student import delete_student


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0023_auto_20190606_1810'),
    ]

    operations = [
        migrations.RunPython(delete_student),
    ]
