# # -*- coding: utf-8 -*-
# # Generated by Django 1.11.6 on 2020-02-14 15:50
from __future__ import unicode_literals

from django.db import migrations
from student_app.db_script.delete_unknown_rte import delete_unknown_rte


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0024_auto_20190901_1142'),
    ]

    operations = [
        migrations.RunPython(delete_unknown_rte)
    ]
