# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0024_auto_20190901_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='rollNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
