# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-20 21:34
from __future__ import unicode_literals

from django.db import migrations, models
from student_app.db_script.delete_unknown_rte import delete_unknown_rte


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0025_auto_20200320_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rte',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.RunPython(delete_unknown_rte),
    ]
