# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0026_remove_school_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('sentDateTime', models.DateTimeField(auto_now_add=True, verbose_name='sentDateTime')),
                ('estimatedCount', models.IntegerField(default=0, verbose_name='estimatedCount')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('mobileNumberList', models.TextField(default='', verbose_name='mobileNumberList')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'sms',
            },
        ),
        migrations.CreateModel(
            name='SMSPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSMS', models.IntegerField(default=0, verbose_name='numberOfSMS')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('purchaseDateTime', models.DateTimeField(auto_now_add=True, verbose_name='purchaseDateTime')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool')),
            ],
            options={
                'db_table': 'sms_purchase',
            },
        ),
    ]
