# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 10:05
from __future__ import unicode_literals

from django.db import migrations

from sms_app.db_script.access_sms_app import access_sms_app


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(access_sms_app),
    ]
