# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_auto_20180528_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgClubDeliveryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.TextField(verbose_name='requestId')),
                ('mobileNumber', models.IntegerField(verbose_name='mobileNumber')),
                ('status', models.TextField(verbose_name='status')),
                ('statusCode', models.TextField(verbose_name='statusCode')),
                ('deliveredDateTime', models.DateTimeField(null=True, verbose_name='deliveredDateTime')),
                ('senderId', models.CharField(default='KORNGL', max_length=10, verbose_name='senderId')),
            ],
            options={
                'db_table': 'msg_club_delivery_report',
            },
        ),
        migrations.AddField(
            model_name='sms',
            name='requestId',
            field=models.TextField(null=True, unique=True, verbose_name='requestId'),
        ),
        migrations.AlterUniqueTogether(
            name='msgclubdeliveryreport',
            unique_together=set([('requestId', 'mobileNumber')]),
        ),
    ]
