# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:13
from __future__ import unicode_literals

from django.db import migrations
from sms_app.db_script.fix_crroupt_sms import fix_crroupt_sms


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_sms_parentmessagetype'),
    ]

    operations = [
        migrations.RunPython(fix_crroupt_sms)
    ]
