# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0043_auto_20210414_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.CharField(max_length=20, unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refund Pending', 'Refund Pending'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('referenceId', models.CharField(default=None, max_length=30, null=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
