# Generated by Django 3.2.5 on 2021-08-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refund Pending', 'Refund Pending'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('referenceId', models.CharField(blank=True, max_length=30, null=True)),
                ('refundId', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.CharField(max_length=20, unique=True)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.school', unique=True)),
            ],
        ),
    ]
