# Generated by Django 3.2.5 on 2021-10-14 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_school_smsid'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='orderId',
        ),
        migrations.AlterField(
            model_name='schoolmerchantaccount',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SchoolMerchantAccountList', to='school_app.school', unique=True),
        ),
    ]
