# Generated by Django 3.2.5 on 2021-12-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_school_smsid'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBankAccountUpdationPermissionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankAccountUpdationPermissionCount', models.IntegerField(default=0)),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SchoolBankAccountUpdationPermissionList', to='school_app.school', unique=True)),
            ],
        ),
    ]
