# Generated by Django 3.2.5 on 2021-12-05 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_schoolbankaccountupdationpermissioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='isEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='percentageOfPlatformFeeOnSchool',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
