# Generated by Django 3.2.5 on 2021-12-05 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_schoolmerchantaccount_isenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='percentageTransactionChargeOnSchool',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
