# Generated by Django 3.2.5 on 2022-08-05 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_auto_20211205_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmerchantaccount',
            name='percentageOfPlatformFeeOnSchool',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
