# Generated by Django 3.2.5 on 2023-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_auto_20230117_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='easebuzzBankLabel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='isAllowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='maxPlatformFeeOnSchool',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolmerchantaccount',
            name='platformFeeOnSchoolType',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], default='Percentage', max_length=15),
        ),
    ]
