# Generated by Django 3.2.5 on 2023-03-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_auto_20230321_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmerchantaccount',
            name='isAllowed',
        ),
    ]
