# Generated by Django 3.2.5 on 2023-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_remove_schoolmerchantaccount_isallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmerchantaccount',
            name='easebuzzBankLabel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
