# Generated by Django 3.2.5 on 2021-10-28 08:55

from django.db import migrations, models
import django.db.models.deletion
import generic_design_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0002_remove_school_smsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=generic_design_app.models.upload_image_assets_to)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REPORT CARD', 'REPORT CARD'), ('TC', 'TC')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to=generic_design_app.models.upload_thumbnail_to)),
                ('publiclyShared', models.BooleanField(default=False)),
                ('content', models.JSONField()),
                ('parentSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layoutList', to='school_app.school')),
            ],
            options={
                'unique_together': {('type', 'parentSchool', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LayoutShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentLayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layoutShareList', to='generic_design_app.layout')),
                ('parentSchoolSharedWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layoutSharedWithMeList', to='school_app.school')),
            ],
            options={
                'unique_together': {('parentSchoolSharedWith', 'parentLayout')},
            },
        ),
    ]
