# Generated by Django 3.2.5 on 2021-10-28 08:55

from django.db import migrations
from generic_design_app.db_script.migrate_layouts import migrate_rc_layout_data, migrate_tc_layout_data


class Migration(migrations.Migration):

    dependencies = [
        ('generic_design_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_rc_layout_data),
        migrations.RunPython(migrate_tc_layout_data),
    ]
