# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_schoolsummary'),
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificatenew',
            name='parentSession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='school_app.SchoolSession'),
            preserve_default=False,
        ),
    ]
