# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from tc_app.db_script.populateTCSettingsForAllSchools import populateTcSettings


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificatesettings',
            name='parentSchool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.RunPython(populateTcSettings)
    ]
