# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-08 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcimageassets',
            name='parentLayout',
        ),
    ]
