# Generated by Django 3.2.5 on 2021-10-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificatenew',
            name='parentStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='transfercertificatenew',
            name='parentStudentSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.studentsection'),
        ),
    ]
