# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificatenew',
            name='lastClassAttended',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
