# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-08 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0002_transfercertificatenew_lastclassattended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfercertificatenew',
            old_name='lastClassAttended',
            new_name='lastClassPassed',
        ),
    ]
