# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import tc_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0002_auto_20210228_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tclayout',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=tc_app.models.upload_thumbnail_to),
        ),
    ]
