# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0003_auto_20210302_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificatenew',
            name='cancelledBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tc_set', to='employee_app.Employee'),
        ),
        migrations.AlterField(
            model_name='transfercertificatenew',
            name='issuedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tc_set', to='employee_app.Employee'),
        ),
    ]
