# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-03-08 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0005_transfercertificatenew_certificatefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfercertificatesettings',
            old_name='lastCertificateNumber',
            new_name='nextCertificateNumber',
        ),
    ]
