# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 06:06
from __future__ import unicode_literals

from django.db import migrations

from user_app.db_script.create_user import create_user


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
