# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0038_auto_20191130_2039'),
        ('student_app', '0024_auto_20190901_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='-', verbose_name='remark')),
                ('parentSession', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='studentremark_parent_session', to='school_app.Session', verbose_name='parentSession')),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studentremark_parent_student', to='student_app.Student', verbose_name='parentStudent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentremark',
            unique_together=set([('parentStudent', 'parentSession')]),
        ),
    ]
