# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.BigIntegerField()),
                ('otp', models.IntegerField()),
                ('generationDateTime', models.DateTimeField(auto_now_add=True, verbose_name='generationDateTime')),
                ('action', models.CharField(choices=[('SIGN UP', 'SIGN UP'), ('FORGOT PASSWORD', 'FORGOT PASSWORD')], max_length=20, null=True)),
            ],
        ),
    ]
