# Generated by Django 3.2.5 on 2021-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='action',
            field=models.CharField(choices=[('SIGN UP', 'SIGN UP'), ('FORGOT PASSWORD', 'FORGOT PASSWORD'), ('CREATE SCHOOL', 'CREATE SCHOOL')], max_length=20, null=True),
        ),
    ]
