# Generated by Django 3.2.5 on 2022-04-09 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication_app', '0002_alter_otp_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(null=True, verbose_name='token')),
                ('last_active', models.DateTimeField(auto_now_add=True, verbose_name='last active')),
                ('login_date', models.DateTimeField(auto_now_add=True, verbose_name='login date')),
                ('device_name', models.TextField(null=True, verbose_name='device name')),
                ('mobile', models.BigIntegerField(default=0)),
                ('parentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_list',
            },
        ),
    ]
