# Generated by Django 3.2.5 on 2022-03-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_devicelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelist',
            old_name='user_id',
            new_name='parentUser',
        ),
    ]
