# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
        ('employee_app', '0001_initial'),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('enquirerName', models.CharField(max_length=100)),
                ('dateOfEnquiry', models.DateField(auto_now_add=True, verbose_name='dateOfEnquiry')),
                ('mobileNumber', models.BigIntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('parentClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='class_app.Class')),
                ('parentEmployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee')),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.School')),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
    ]
