# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-07-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobileNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
