# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0004_auto_20200321_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='parentEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.Employee'),
        ),
    ]
