# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from attendance_app.db_script.add_record_employee_attendance_task import add_record_employee_attendance_task


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20180525_0259'),
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAttendance', models.DateField(default='2011-01-01', verbose_name='dateOfAttendance')),
                ('status', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=10)),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
        ),
        migrations.RunPython(add_record_employee_attendance_task),
    ]
