# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('HOLIDAY', 'Holiday'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('HOLIDAY', 'Holiday'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10),
        ),
    ]
