# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from attendance_app.db_script.transfer_attend_permissions_from_user_to_employee import transfer_attend_permissions_from_user_to_employee

class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20180918_1556'),
        ('attendance_app', '0003_auto_20180916_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermission',
            name='parentEmployee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee'),
        ),
        migrations.RunPython(transfer_attend_permissions_from_user_to_employee),
    ]
