# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20180918_1556'),
        ('attendance_app', '0005_auto_20180919_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppliedLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfLeave', models.DateField(default='2011-01-01', verbose_name='dateOfLeave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('halfDay', models.BooleanField(default=False, verbose_name='halfDay')),
                ('paidLeave', models.BooleanField(default=True, verbose_name='paidLeave')),
                ('parentEmployee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_app.Employee', verbose_name='parentEmployee')),
            ],
            options={
                'db_table': 'employee_applied_leave',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=set([('parentEmployee', 'dateOfAttendance')]),
        ),
        migrations.AlterModelTable(
            name='employeeattendance',
            table='employee_attendance',
        ),
        migrations.AlterUniqueTogether(
            name='employeeappliedleave',
            unique_together=set([('parentEmployee', 'dateOfLeave')]),
        ),
    ]
