# Generated by Django 3.2.5 on 2023-03-30 12:07

from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='backImage',
            field=models.ImageField(blank=True, null=True, upload_to=library_app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='frontImage',
            field=models.ImageField(blank=True, null=True, upload_to=library_app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='printedCost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='typeOfBook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
