# Generated by Django 3.2.5 on 2023-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20230330_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='printedCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
