# Generated by Django 3.2.5 on 2023-04-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('library_app', '0003_alter_book_numberofpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('bookNumber', 'parentSchool')},
        ),
    ]
