# Generated by Django 3.2.5 on 2023-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20230330_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='printedCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
