# Generated by Django 3.2.5 on 2023-09-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_pannumber'),
        ('school_app', '0004_auto_20221216_2152'),
        ('student_app', '0003_auto_20221104_1530'),
        ('library_app', '0003_auto_20230420_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='canEmployeeIssue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='canStudentIssue',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SchoolLibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxStudentIssueCount', models.IntegerField(default=5)),
                ('maxEmployeeIssueCount', models.IntegerField(default=10)),
                ('parentSchool', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.school')),
            ],
            options={
                'db_table': 'school_library_settings',
            },
        ),
        migrations.CreateModel(
            name='BookIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueTime', models.DateTimeField(auto_now_add=True)),
                ('depositTime', models.DateTimeField(default=None, null=True)),
                ('parentBook', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_issue_record', to='library_app.book')),
                ('parentEmployee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_issue_record', to='employee_app.employee')),
                ('parentStudent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_issue_record', to='student_app.student')),
            ],
            options={
                'db_table': 'book_issue_record',
            },
        ),
    ]
