# Generated by Django 3.2.5 on 2023-09-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20221216_2152'),
        ('library_app', '0004_auto_20230902_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollibrarysettings',
            name='parentSchool',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.school'),
        ),
    ]
