# Generated by Django 3.2.5 on 2023-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_printedcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
