
name: Test Pr Size

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "buil"
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Check change size
              run: |
                  sudo bash ./scripts/small_changes_check.sh

