# This is a basic workflow to help you get started with Actions

name: Test - Formatting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Installing Dependencies
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Testing Linting
      env:
      run: |
        cd frontend
        ./scripts/ng-lint/run_linter_ci.sh

