# This is a basic workflow to help you get started with Actions

name: Test Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
        node-version: [10.16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - uses: chrislennon/action-aws-cli@v1.1
#    - name: Setup Aws cli 

    # Installing Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        cd frontend
        npm ci

    - name: Checking Migration
      run: |
        cd backend
        ./manage.py makemigrations --check

    - name: Karma Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd frontend
        aws configure list
        sh scripts/karma/run-tests-karma-github.sh

    - name: Protractor Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd frontend
        aws configure list
        cp src/environments/environment.ts src/environments/environment.prod.ts
        sh scripts/protractor/run-tests-e2e-github.sh
        sh scripts/protractor/check-coverage-e2e-github.sh
        sh scripts/feature/check-feature-coverage-github.sh
        kill -9 `ps aux | grep testserver | awk '{ print $2 }'`
