# This is a basic workflow to help you get started with Actions

name: Test Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        #types: [labeled]
    # pull_request_review:
    #   branches: [ master ]
    #   types: [ submitted ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        #if: contains( github.event.pull_request.labels.*.name, 'Run Tests')
        # if: github.event.review.state == 'approved'
        # The type of runner that the job will run on
        runs-on: ubuntu-20.04


        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2


            - name: Small Changes
              run: |
                  ./frontend/scripts/diff_changes/small_changes.sh




