# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobileNUmber',
            new_name='mobileNumber',
        ),
    ]
