# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20171101_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.TextField(default='---'),
        ),
    ]
