# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_student_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('remark', models.TextField()),
                ('generationDate', models.DateField()),
                ('parentStudent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Student')),
            ],
        ),
    ]
