# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='generationDate',
            new_name='generationDateTime',
        ),
    ]
