# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_auto_20171102_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='generationDateTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
