# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_auto_20180112_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.TextField()),
                ('amount', models.IntegerField()),
                ('parentFee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Fee')),
            ],
        ),
    ]
