# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_auto_20171102_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='orderNumber',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
