# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_class_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='totalFees',
            field=models.IntegerField(null=True),
        ),
    ]
