# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_student_friendsection'),
				('class_app', '0002_auto_20180302_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='parentUser',
        ),
        migrations.RemoveField(
            model_name='sessionclass',
            name='parentClass',
        ),
        migrations.RemoveField(
            model_name='sessionclass',
            name='parentSession',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentClass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sessionClass',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parentClass',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='SessionClass',
        ),
    ]
