# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0018_marksheet'),
        ('student_app', '0001_marksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='parentStudent',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='parentSubject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='friendSection',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollNumber',
        ),
        migrations.AlterField(
            model_name='schoolsession',
            name='parentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.School', verbose_name='parentSchool'),
        ),
        migrations.AlterField(
            model_name='schoolsession',
            name='parentSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.Session', verbose_name='parentSession'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsession',
            unique_together=set([('parentSession', 'parentSchool')]),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
