# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models

from school_app.db_script.populate_school_session import populate_school_session, populate_eklavya_dise_code_and_address


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0019_auto_20180321_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='diseCode',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(populate_school_session),
        migrations.RunPython(populate_eklavya_dise_code_and_address),
    ]
