# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0024_school_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registrationNumber',
            field=models.TextField(default='426/13.01.1993'),
        ),
    ]
