# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0025_auto_20180429_1533'),
        ('team_app', '0002_auto_20180522_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
