# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0026_remove_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='smsId',
            field=models.CharField(default='KORNGL', max_length=10, verbose_name='smsId'),
        ),
    ]
