# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import school_app.model.models

from school_app.db_script.add_profile_images import add_profile_images


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0027_school_smsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to=school_app.model.models.upload_avatar_to, verbose_name='Avatar'),
        ),
        migrations.RunPython(add_profile_images),
    ]
