# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0028_school_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
    ]
