# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0032_school_headersize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AlterField(
            model_name='school',
            name='complexFeeStructure',
            field=models.BooleanField(default=False),
        ),
    ]
