# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import school_app.model.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0033_remove_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='affiliationNumber',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principalSignatureImage',
            field=models.ImageField(blank=True, upload_to=school_app.model.models.upload_principal_signature_to, verbose_name='Principal Signature'),
        ),
    ]
