# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0034_auto_20190227_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='opacity'),
        ),
    ]
