# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0035_school_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dateOfExpiration',
            field=models.DateField(default='2019-04-30', verbose_name='dateOfExpiration'),
        ),
    ]
