# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-12 06:55
from __future__ import unicode_literals

from django.db import migrations
from school_app.db_script.change_session import change_session


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0036_school_dateofexpiration'),
    ]

    operations = [
        migrations.RunPython(change_session),
    ]
