# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from school_app.db_script.populate_board import populate_board


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0037_auto_20190712_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='block',
            field=models.TextField(null=True, verbose_name='block'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.TextField(null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='school',
            name='pincode',
            field=models.IntegerField(null=True, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.TextField(null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='school',
            name='villageCity',
            field=models.TextField(null=True, verbose_name='villageCity'),
        ),
        migrations.AddField(
            model_name='school',
            name='parentBoard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='school_app.Board', verbose_name='parentBoard'),
        ),
        migrations.RunPython(populate_board),
    ]
