# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-04 16:32
from __future__ import unicode_literals

from django.db import migrations
from school_app.db_script.add_session import add_session

class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0038_auto_20191130_2039'),
    ]

    operations = [
        migrations.RunPython(add_session),
    ]
