# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0038_auto_20190906_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='block',
            field=models.TextField(null=True, verbose_name='block'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.TextField(null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='school',
            name='pincode',
            field=models.IntegerField(null=True, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.TextField(null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='school',
            name='villageCity',
            field=models.TextField(null=True, verbose_name='villageCity'),
        ),
    ]
